### ISSUE TITLE
Blank window from system tray

### ISSUE THREAD

**Issue by beefeater7** [hluk/CopyQ#1406] opened 2020-06-11 20:29 UTC
There is a discrepancy between using Space and Enter to open CopyQ from Windows systray. Space works fine but Enter bugs out displaying all-white content. Interacting with the window is possible. Menu bar dropdowns display and so on.

**To Reproduce**
1. Win+B
2. Arrow to CopyQ
3. Enter
4. Result:
![Annotation 2020-06-11 221436](https://user-images.githubusercontent.com/10468970/84434803-fb22f000-ac30-11ea-8d40-87f59963b89b.png)
Window cannot be closed by X. Pressing systray icon again does the trick.

**Expected behavior**
Enter behaves like Space in this context

**Version, OS and Environment**
 - v3.11.1
 - Windows 10

**Comment by hluk** [comment] 2020-06-12 12:06
Duplicate of #1228.

**Closed by hluk** 2020-06-12 12:06 UTC
Labels: bug
