### ISSUE TITLE
History windows blinks at start on 2.5.0, which it did not at 2.4.8

### ISSUE THREAD

**Issue by MortenZdk** [hluk/CopyQ#438] opened 2016-01-27 10:04 UTC
When using a shortcut (Ctrl+Shift+C) on ver. 2.5.0 to open the history windows, the windows blinks like it is being drawn twice.  I did not experience this at ver. 2.4.8.

Setup: Windows 7, 64-bit, latest graphics card driver, and have not experienced other programs doing anything similar.

**Comment by hluk** [comment] 2016-01-30 07:58
I never noticed this. It's probably impossible for me to fix this without being able to reproduce it first (there are lot of code changes after 2.4.8 version).

Can you try to resize and move the window? Perhaps it to fix some bad position and size (note: I removed some of this behavior after 2.5.0 because it didn't work well on multiple monitors).

If this won't help, can you check how it behaves in version [2.4.9](https://github.com/hluk/CopyQ/releases/tag/v2.4.9)?

**Comment by MortenZdk** [comment] 2016-01-31 07:35
Did some experiments with resize and move of window.  It shows that if the history window is not maximized, then there is no "blink".  When the history window is maximized, it appears like the history window is first drawn as the window if was previously maximized from, and then the currently maximized window is drawn.  That what I took as blink.  Note that after I have shown the history window I exit this by escape.

The issue is also there in 2.4.9, and even more visible, since the time is longer between showing the previous non-maximized window before showing the final maximized window.

**Comment by hluk** [comment] 2016-01-31 10:14
Ahh, I see what is wrong - it seems to be partially fixed with [a recent commit](https://github.com/hluk/CopyQ/commit/f0baa65c9982bb31d9f2fdbb795c20f7e18e3a28). I'll do some more testing.

You can work around this issue now by *not maximizing* the window - just resize the window or ---if you use shortcut to show/hide window--- use following command instead of the default one (paste to command list Command dialog <kbd>F6</kbd> and change the shortcut).

```ini
[Command]
Name=Show/hide main window
Command="
    copyq:
    if (focused())
      hide()
    else
      showAt(0,0,9999,9999)"
Icon=\xf022
GlobalShortcut=ctrl+`
```

**Closed** 2016-01-31 10:31 UTC
Labels: bug

**Comment by MortenZdk** [comment] 2016-01-31 11:18
Thanks for looking into this, and I appreciate you effort.
