### ISSUE TITLE
CopyQ should remember clipboard monitoring state even if the process gets stopped.

### ISSUE THREAD

**Issue by pre55** [hluk/CopyQ#470] opened 2016-03-18 09:42 UTC
There could be a checkbox which enables or disables remembering of clipboard monitoring state.
Imho it should be checked (enabled) by default.

**Comment by hluk** [comment] 2016-03-18 16:27
Isn't this same as #458?

"Disable Clipboard Storing" is meant to be temporary. If you want disable storing altogether you can unset "Tab for storing clipboard" in "History" config tab (though this won't disable automatic commands).

**Comment by pre55** [comment] 2016-03-19 16:28
This workaround won't be the best solution, because you _have to_ change the "tab for storing clipboard" to unset remembering the clipboard monitoring state. This could easily be fixed by a checkbox called "Remember Clipboard monitoring state even if the process gets stopped." or something similar.

Concerning #458, i'd say i'ts just very similar.

**Comment by pre55** [comment] 2016-03-22 16:14
So, do you plan to implement #458 or #470 or both or none?
Just being courious.

**Comment by hluk** [comment] 2016-03-23 08:57
I'm not sure yet how to handle this. I didn't have time to think about it much.

One way to disable monitoring when application starts is to have an environment variable -- that might be the simplest solution (meaning no GUI modifications and no new strings to translate) -- I can start with that.

Other way is to have a custom command -- you could start using that right away without waiting on new version of the app. I'll get back to you if I come up with something.

**Comment by hluk** [comment] 2016-04-03 07:00
To change monitoring state permanently, you can use following automatic command (ideally it should be first in the list of commands so no other automatic command is invoked).

```ini
[Command]
Automatic=true
Command="
    copyq:
    var option = 'disable_monitoring'
    var disabled = str(settings(option)) === 'true'
    
    if (str(data('application/x-copyq-shortcut'))) {
      disabled = !disabled
      settings(option, disabled)
      popup('', disabled ? 'Monitoring disabled' : 'Monitoring enabled')
    }
    
    if (disabled) {
      ignore()
      updateTitle('')
    }"
GlobalShortcut=meta+alt+x
Icon=\xf05e
Name=Toggle Monitoring
```

**Comment by pre55** [comment] 2016-04-20 21:51
I don't know what I'm doin wrong:

First I hit F6 and add click [+] to add a new command.
Then I name the command.
Activate automatic.
Finally I copy / paste your command:
![CopyQ_F6_paste_code](http://abload.de/img/copyq_f6_paste_codee6ovf.png)

After I restarted CopyQ this error window pops up:
![CopyQ_error_starting_process](http://abload.de/img/copyq_error_starting_uzpuf.png)
(Saying: "Error: The process couldn't be started: No such file or directory")

**Comment by hluk** [comment] 2016-04-21 06:44
Paste the command into the command list in Command dialog -- you can use the button "Paste Commands" in the bottom part of the dialog.

**Comment by hluk** [comment] 2016-04-21 07:03
@pre55 I've added section to FAQ about [adding and sharing commands](https://github.com/hluk/CopyQ/wiki/FAQ#12).

**Comment by pre55** [comment] 2016-04-24 20:41
I found the "Paste Command" this time. ^^
► http://abload.de/img/copyq_commandl3c82.png
But the code doesn't disable clipboard monitoring at CopyQ's startup.
Shouldn't it do that?

**Comment by hluk** [comment] 2016-04-25 09:52
It restores last monitoring state the first time you copy something to clipboard after CopyQ is started. To toggle monitoring state, you need to use the global shortcut assigned to the command (<kbd>Meta</kbd>+<kbd>Alt</kbd>+<kbd>X</kbd> by default).

**Comment by pre55** [comment] 2016-04-27 14:03
At the moment that Toggle Monitoring [Command] doesn't work for me - but I'm quite sure it does!
Please give me short instructions what I should do, to see that it does work.

Is it possible to write a [Command] which disables monitoring [Meta+Alt+X] after CopyQ got started? (What does "Meta" stand for?)

If not, I'll better wait for an upcoming Version of CopyQ where disabling monitoring is available by cmd start up environment variable.

**Comment by hluk** [comment] 2016-04-28 05:51
(<kbd>Meta</kbd> is just the Windows key.)

The problem is there are no commands that are executed when application starts -- only when clipboard changes. Better way to handle this is to start `copyq disable` after CopyQ starts (but you need to know where to put the command on your system).

I haven't implemented persistent disabling clipboard and it probably won't be in next version which I plan to release ASAP.

Can you give me more description on your workflow?

**Comment by pre55** [comment] 2016-04-28 16:54
##### Workflow description:
**1.** only the toggle monitoring [command] active and at 1st position.
(as seen on http://abload.de/img/copyq_commandl3c82.png)
**2.** I copy some txt-string, during CopyQs clipboard monitoring is active. 
(http://abload.de/img/copyq_successful_copy1bano.png)
**3. ** Clipboard Monitoring stays enabled. :question:

##### CopyQ disable:
> Better way to handle this is to start `copyq disable` after CopyQ starts

I wrote a dirty BATCH script which helps, but it's surely not the best solution:
`@echo off`
`start C:\Portable\CopyQ\copyq`
`echo Waiting 1 second.`
`timeout /t 1 /nobreak`
`C:\Portable\CopyQ\copyq disable`

Do you have any better solution?

**Comment by hluk** [comment] 2016-05-01 07:28
By "workflow" I meant: What you need to achieve, how you handle clipboard and when you need it to be stored in CopyQ?

E.g. if you need to copy something and add it to CopyQ only once in a while it's better to bind a global shortcut to copy & add item command.

**Closed** 2017-12-19 13:13 UTC
