### ISSUE TITLE
Main Window-Mouse Interaction Misbehavior

### ISSUE THREAD

**Issue by G-i-o** [hluk/CopyQ#1724] opened 2021-07-26 14:48 UTC
Hello.

Erratic behavior when moving an item from one position/line to another or to another tab with the mouse.

**TO REPRODUCE:**
❶ Click to select the item holding the mouse button down.
❷ Move the item to the desired position.
❸ Release the mouse button.

**UNEXPECTED BEHAVIOR:** After the item is dropped to the selected position the mouse acts like the button was never released and as it hovers another item, the latter gets automatically selected and dragged wherever the mouse go.
The only way to release the mouse button is to click again the same button as soon as the same or another item gets automatically selected instead of keeping moving the mouse.

**Version, OS and Environment:**
- Version: 4.1
- OS: Linux Manjaro (Kernel 5.12.19) 
- DE: KDE 5.84.0 / Plasma 5.22.3
 - WM: KWin

Thank You. 🙏🏽

**Comment by hluk** [comment] 2021-07-31 07:07
Duplicate of #1692. Unfortunately, I cannot fix this in the app. :(

**Closed by hluk** 2021-07-31 07:07 UTC
Labels: bug
