### ISSUE TITLE
Cinnamon desktop 3.2.2 on 16.04, no tray icon

### ISSUE THREAD

**Issue by genachka** [hluk/CopyQ#595] opened 2016-12-01 00:20 UTC
With CopyQ 2.7.1, on start up there was no tray icon visible with Cinnamon but it does show the processes are running. When kill the processes and start up CopyQ again, the icon shows up.

With CopyQ 2.8.0 I can't seem to get the tray icon at all. Not on startup, not on the work around that worked with 2.7.1.

**Comment by hluk** [comment] 2016-12-01 07:37
I've recently fixed dependencies for deb packages -- make sure that `libqt5svg5` package is installed -- this should fix the icon.

**Comment by genachka** [comment] 2016-12-01 14:43
I couldn't install due to dependency issues as well but did see and used the package in https://github.com/hluk/CopyQ/issues/587#issuecomment-263133832.

Just checked and I do have `libqt5svg5` installed: `libqt5svg5 is already the newest version (5.5.1-2build1).`

**Comment by genachka** [comment] 2016-12-15 00:53
Any other thoughts on how I can get the icon to show up on Cinnamon? Using the keyboard shortcut works to display CopyQ but it would be good to get the icon working still.

**Comment by hluk** [comment] 2016-12-17 08:33
Could this be related to https://github.com/linuxmint/Cinnamon/issues/2846? Perhaps using different systray app can solve this.

**Comment by genachka** [comment] 2016-12-17 15:39
Perhaps. But with CopyQ 2.7.1 it wasn't showing up on login, but I had a workaround -- exiting CopyQ after login and then loading CopyQ again the icon would show up. However that stopped working with CopyQ 2.8.x.

**Comment by hluk** [comment] 2016-12-17 16:34
Official packages for CopyQ are now built with new Qt libraries. So it's possible that this is Cinnamon or Qt issue.

Damn, I just tried to google this issue and #431 came up as the first result. So let's move the discussion there.

Closing as duplicate of #431.

**Closed by hluk** 2016-12-17 16:34 UTC
