### ISSUE TITLE
Incorrect path of dependent dylibs for OS X build

### ISSUE THREAD

**Issue by meoow** [hluk/CopyQ#386] opened 2015-09-22 13:23 UTC
The copyq binary itself has correct path, but the bundled Qt framework are still pointing their  dependence to `/usr/local/Cellar/qt5/5.5.0/lib/`. It seems the app wasn't correctly packaged via `macdeployqt`.
```sh
$ otool -L /Applications/CopyQ.app/Contents/Frameworks/QtSvg.framework/QtSvg | sed 's/ (compatibility version.*$//'
/Applications/CopyQ.app/Contents/Frameworks/QtSvg.framework/QtSvg:
	@executable_path/../Frameworks/QtSvg.framework/Versions/5/QtSvg
	/usr/local/Cellar/qt5/5.5.0/lib/QtWidgets.framework/QtWidgets
	/usr/local/Cellar/qt5/5.5.0/lib/QtGui.framework/QtGui
	/usr/local/Cellar/qt5/5.5.0/lib/QtCore.framework/QtCore
	/System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
	/usr/lib/libz.1.dylib
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
	/System/Library/Frameworks/AGL.framework/Versions/A/AGL
	/usr/lib/libc++.1.dylib
	/usr/lib/libSystem.B.dylib
```

**Comment by meoow** [comment] 2015-09-22 14:48
Even after I correct all paths, it still complains:  
```
CopyQ  Started Background activity for: CopyQ Server
This application failed to start because it could not find or load the Qt platform plugin "cocoa".

Available platform plugins are: cocoa.

Reinstalling the application may fix this problem.
Abort trap: 6
```

**Comment by hluk** [comment] 2015-09-30 19:33
I spent some time trying to fix this on Travis CI but without any success.

As @meoow said, it is possibly issue with `macdeployqt` (or it's missing some arguments).

Verbose log from `macdeployqt` [on Travis](https://travis-ci.org/hluk/CopyQ/jobs/82979430#L3077).

Same errors are mentioned in https://github.com/Homebrew/homebrew/issues/42191.

If anyone finds a way to fix it, let me know.

**Comment by rygwdn** [comment] 2015-10-18 16:56
This is indeed caused by https://github.com/Homebrew/homebrew/issues/42191. Travis uses qt5 installed with homebrew. For now a build done with the official qt.io version should work. I'll upload one for 2.4.9 and people can try it out.

**Comment by rygwdn** [comment] 2015-10-18 17:12
I uploaded a new build to the [2.4.9 release](https://github.com/hluk/CopyQ/releases/tag/v2.4.9).

**Comment by hluk** [comment] 2015-10-19 07:19
Thanks Ryan. Is that 2.4.9 tag build with Qt 5.5.1 or some script to fix macdeployqt?

**Comment by rygwdn** [comment] 2015-10-19 09:47
Thats the 2.4.9 tag built with Qt 5.5.1 from qt.io instead of homebrew. The only differences from the original 2.4.9 build were the distribution of Qt and that I applied https://github.com/hluk/CopyQ/commit/8bcfc64aa57aa8fa21c7981c37c7d04fc987fcfb locally to get it to build.

**Comment by hluk** [comment] 2015-10-19 09:53
Qt 5.5.1 was committed few hours ago to homebrew repo ([commit](https://github.com/Homebrew/homebrew/commit/01f0faab565c8233c2bf31d73aa1e14afaf88d94)). I hope there won't be any problems with next automated build.

**Comment by rygwdn** [comment] 2015-10-19 13:11
It looks like [the issue still exists](https://github.com/Homebrew/homebrew/issues/42191#issuecomment-149025927) with the homebrew version of 5.5.1.

**Comment by rygwdn** [comment] 2015-11-14 14:30
https://github.com/Homebrew/homebrew/issues/42191 is fixed, and it looks like the latest CopyQ build (2.5.0) works now!

**Comment by hluk** [comment] 2015-11-14 14:55
That's great!

**Closed by hluk** 2015-11-14 14:55 UTC
