### ISSUE TITLE
Blank history screen - no history saved

### ISSUE THREAD

**Issue by pacid** [hluk/CopyQ#1730] opened 2021-08-14 12:53 UTC
**Describe the bug**
Blank history screen - no history saved

**To Reproduce**
1. Copy one text
2. Copy second text
3. Open the tray
4. See image
![image](https://user-images.githubusercontent.com/1618052/129446831-2aeaff7e-59cb-4e64-ba80-8ffb6f3efff7.png)

That's with 30 items to be stored in history
**Expected behavior**
Multiple items stored in tray

**Version**
CopyQ Clipboard Manager v3.2.0
Built with: Qt 5.9.3, LibQxt 0.7.0
Ubuntu 18.04

**Additional comments**
That started happening after some recent update in Ubuntu. Maybe a lib or CopyQ itself. Not sure.

**Comment by hluk** [comment] 2021-08-16 07:28
It could be caused by a corrupted data file or a missing plugin.

Can you share logs (F12 shortcut from main window)?

**Comment by pacid** [comment] 2021-08-16 15:11
Hi hluk! Thanks for the quick reply. Here are the logs. Hope that helps!


ERROR [2019-07-13 12:05:53.585] Client-31105: Connection lost!
ERROR [2019-07-13 12:05:53.585] Client-31112: Connection lost!
ERROR [2021-01-23 20:13:13.498] Client-27512: Cannot connect to server! Start CopyQ server first.
Note [2021-01-23 20:13:13.500] Server-24458: Command “Show main wind…r mouse cursor”
Note [2021-01-23 20:13:13.500] Server-24458:    Exit code: 1
Note [2021-01-23 20:13:13.500] Server-24458:    1. copyq:  showAt()
ERROR [2021-02-10 23:01:23.864] Client-16210: Cannot connect to server! Start CopyQ server first.
Note [2021-02-10 23:01:23.865] Server-10720: Command “Show main wind…r mouse cursor”
Note [2021-02-10 23:01:23.865] Server-10720:    Exit code: 1
Note [2021-02-10 23:01:23.865] Server-10720:    1. copyq:  showAt()
ERROR [2021-02-22 12:05:54.186] Client-21178: Cannot connect to server! Start CopyQ server first.
Note [2021-02-22 12:05:54.188] Server-16569: Command “Show main wind…r mouse cursor”
Note [2021-02-22 12:05:54.188] Server-16569:    Exit code: 1
Note [2021-02-22 12:05:54.188] Server-16569:    1. copyq:  showAt()
ERROR [2021-02-22 12:05:57.306] Client-21179: Cannot connect to server! Start CopyQ server first.
Note [2021-02-22 12:05:57.307] Server-16569: Command “Show main wind…r mouse cursor”
Note [2021-02-22 12:05:57.307] Server-16569:    Exit code: 1
Note [2021-02-22 12:05:57.307] Server-16569:    1. copyq:  showAt()

**Comment by hluk** [comment] 2021-08-18 06:10
I don't see any error related to loading the tabs.

I noticed that you are using very old CopyQ version. This is likely to be related to some bug that is already fixed in more recent versions. Can you update?

**Comment by pacid** [comment] 2021-08-18 07:32
Thank you. Well I tried installing some two recent versions but there's a dependency hell, tried satisfying them but in the end failed. Using Ubuntu 18.04 as I want to focus on my app not on updating all the software. i guess I will need to update to something newer to make it easier but who knows what then is going to break. Thanks for your replies! Much appreciated.

**Comment by pacid** [comment] 2021-08-23 15:06
If anyone has a solution for this please advise. I don't want to upgrade 18.04 LTS to a newer version. It's only 3 years since the release. The 20.04 LTS probably brings more problems than it solves.

**Comment by hluk** [comment] 2024-03-26 12:30
Closing this. It is likely cause by a missing plugin or an old bug that was fixed in recent releases.

**Closed by hluk** 2024-03-26 12:30 UTC
Labels: bug
