### ISSUE TITLE
CopyQ starts maximized instead of in tray

### ISSUE THREAD

**Issue by MycroftHolmes1989** [hluk/CopyQ#1061] opened 2018-12-28 13:59 UTC
When autostart is enabled, the main window of CopyQ opens up instead of in tray. Only when I exit CopyQ and restart it does it actually show up in tray.
This doesn't happen in Wayland though.
OS: Ubuntu 18.10 x86_64
Kernel: 4.18.0-13-generic
DE: GNOME 3.30.1
WM: GNOME Shell

**Comment by hluk** [comment] 2018-12-28 15:09
This is probably duplicate of #1048. Looks like CopyQ is started before the desktop environment is properly set up. The app cannot detect tray so it tries to minimize the main window instead but it also fails (window manager not running yet?).

You can try enabling the option mentioned in [this comment](https://github.com/hluk/CopyQ/issues/1048#issuecomment-443187399).

**Comment by hluk** [comment] 2018-12-28 16:12
Closing as duplicate of #1048.

Probably not much I can do with this issue. The problem is either in DE (window manager) or Qt framework.

**Closed by hluk** 2018-12-28 16:12 UTC

**Comment by MycroftHolmes1989** [comment] 2018-12-28 16:13
Probably DE, because it works well with Wayland.

**Comment by hluk** [comment] 2018-12-28 16:18
I'll try to change the tray initialization a bit so that it waits a bit more before creating the icon and hides the main window (if not focused) after the icon is in tray.
