### ISSUE TITLE
New install of CopyQ not  importing of clipboard content: not linking with Wayland clipboard?

### ISSUE THREAD

**Issue by cpsyctc2** [hluk/CopyQ#2847] opened 2024-09-20 08:34 UTC
**Describe the bug**
Cannot get  CopyQ to import from clipboard

**To Reproduce**
My main laptop died yesterday.  It was running Ubuntu 22.04, latest state and I'm not sure what version of CopyQ (but would have been latest based on daily updates of all packages and using the Ubuntu ppa.  I have installed CopyQ 9.0.0~noble from the ppa on my fallback machine which is running Ubuntu 24.04.1 LTS and imported a fairly recent exported cpq file.  That seems to have gone fine, i.e. I can see all the tabs and content but I cannot get CopyQ to import from the clipboard.

**Expected behavior**
I expect the latest cut or copy to go into the clipboard in CopyQ and be pasteable from there.  Not happening.  Single press on the CopyQ icon in the status bar always shows "Clipboard: <EMPTY>" and opening CopyQ just shows the old contents of the imported clipboard tab.  I think the clue is that the old clipboard tab is now "clipboard (1)" and there is a new clipboard tab at the top of tab list named "clipboard" but this stays resolutely empty .

**Screenshots**
Not sure these would say more than the above.

**Version, OS and Environment**
CopyQ Clipboard Manager 9.0.0~noble
Qt: 5.15.13
KNotifications: 5.115.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 24.04.1 LTS

**Additional context**
Aha

CopyQ Warning [2024-09-20 10:18:44.843] <monitorClipboard-224566>: [default] QtWarning: Activating Wayland clipboard took 5000 ms
CopyQ ERROR [2024-09-20 10:18:44.849] <monitorClipboard-224566>: [default] QtCritical: Failed to activate Wayland clipboard
CopyQ ERROR [2024-09-20 10:20:06.090] <Server-224481>: Null data in clipboard
CopyQ ERROR [2024-09-20 10:20:56.172] <Server-224481>: Null data in clipboard

Something I need to do to get Wayland cooperating with CopyQ

P.S. CopyQ has been, for heaven knows how many years now, my #1 utility.  Has saved probably months of my work life.  Thank you!

**Comment by robertstrom** [comment] 2024-09-22 00:28
See my post below **CopyQ on Pop!_OS 2024 - Wayland**. It has a lot of information on my struggles / findings of trying to get CopyQ working on a Wayland desktop environment.

**NOTE:** no one on the CopyQ team has responded to it in any way. Not sure if they are ignoring posts about Wayland or what.

I feel the same way about CopyQ. I have been using a clipboard manager since the mid to late 1990's (Clipmate on Windows). I still use that program on my main Windows systems because it has years and years (literally decades) of saved clips but CopyQ is my go to for Linux and macOS and I use it on test Windows systems. I even donate to / support the project monetarily.

This Wayland thing seems to really be throwing a number of programs a huge curve ball.

Flameshot, my go to screenshot program has similar issues when you attempt to run on a system using the Wayland Display Manager.

I have tried the workarounds listed here - https://copyq.readthedocs.io/en/latest/known-issues.html - but that did not work for me. I finally was able to get CopyQ working on the Pop!_OS 24.04 Alpha but I don't believe that the solution will help those not running the Pop!_OS operating system. I got a hint from a Pop!_OS support person. The hint was to add this to the `/etc/environment` file

```
COSMIC_DATA_CONTROL_ENABLED=1
```

This is pretty specific to the Cosmic desktop (which is using Wayland). I was also only able to get CopyQ to work if I used the Flatpak install version. It tried with the current .deb version and that did not work. What's really strange about that is that the Pop!_OS support person said that they were using the .deb install.

Even though I have it working there are still issues.

- Auto start is not working even though I set the value manually (the Auto start check box does not even exist in the GUI) using this command `flatpak run com.github.hluk.copyq config autostart true` and I checked that it was set to **true** using this command `flatpak run com.github.hluk.copyq config | grep -i auto`
- The program will not store the size and location as I have come to expect. It always opens up in the same place (not the last place where you placed it) and the same size (not the last size that you set it to). I expect that CopyQ would store these values after clicking the X or exiting the program. It does on non-Wayland systems
- I have installed the backup on exit script and that it not working for me
- I cannot get shortcuts to work - in particular the one to Show the window
- I'm sure that there are other issues, but those are what I know about for sure right now

This is also obviously / definitely not just a Pop!_OS 24.04 Alpha issue. I have installed some other Linux distros that run Wayland and CopyQ does not work on them either. Example:

I installed Zorin Educational into a QEMU virtual machine. This is the output of the command `inxi --system --graphics --width 80`

```
rstrom@zorin-educational:~$ inxi --system --graphics --width 80
System:
  Host: zorin-educational Kernel: 6.8.0-45-generic x86_64 bits: 64
    Desktop: GNOME 43.9 Distro: Zorin OS 17.2
Graphics:
  Device-1: Red Hat Virtio GPU driver: virtio-pci v: 1
  Display: wayland server: X.Org v: 1.22.1.1 with: Xwayland v: 22.1.1
    compositor: gnome-shell driver: X: loaded: modesetting unloaded: fbdev,vesa
    gpu: virtio-pci resolution: 1920x1080~60Hz
  OpenGL: renderer: llvmpipe (LLVM 15.0.7 256 bits)
    v: 4.5 Mesa 23.2.1-1ubuntu3.1~22.04.2
```

I can install CopyQ and it runs but it does zero copying and pasting. I have currently installed the Flatpak version. I have not yet tested the .deb version with the workaround. One issue with the Flatpak version is that I have no idea how to configure CopyQ to auto start or to start with the specific parameters mentioned in the workaround. I am not a fan of Flatpaks or Snaps.

On the Zorin install I see the same error as you do when I run CopyQ using the command line `flatpak run com.github.hluk.copyq`

```
rstrom@zorin-educational:~$ flatpak run com.github.hluk.copyq 
Warning: [default] QtWarning: QSocketNotifier: Can only be used with threads started with QThread
Warning: [qt.qpa.qgnomeplatform] QtWarning: Could not find color scheme  ""
Warning: [default] QtWarning: Activating Wayland clipboard took 5000 ms
ERROR: [default] QtCritical: Failed to activate Wayland clipboard

```

**But** while tying this I decided to try something. On Zorin, with the Flatpak version installed I tried using the command in the CopyQ Known Issues documentation linked above `env QT_QPA_PLATFORM=xcb copyq` and that did not work. I really did not expect it to. But then I tried a combination of that command and the Flatpak command to start CopyQ

```
env QT_QPA_PLATFORM=xcb flatpak run com.github.hluk.copyq
```

This command started CopyQ and copy and paste is working in the Zorin Flatpak installation. I will test with the .deb version later.

Summary ... **Wayland is a royal PITA**. It appears to be the future patch forward but there are still so many issues. I am not a developer but ... Why are these so hard to get working?

HTH,

Robert

**Comment by cpsyctc2** [comment] 2024-09-22 18:27
Hm.  Totally agree about Wayland.  Oddly enough it caused me nasty headaches when my last laptop arrived (the one that just died and caused some of this mess).  That  was Wayland and the then nVidia drivers for the machine.  For months it also meant that many things only run at a usable pace if I turned _off_ hardware acceleration.  That was with the then new Ubuntu (22.04).  I am now very jaundiced about Ubuntu and certainly about Wayland.  Utterly bizarrely, I now have CopyQ running fine (OK on about 2 minutes testing) on one machine running U24 and not on the other and nothing I do seems to get the copying from the clipboard to work on the latter machine.  I need to turn to other things for a few days so will let this stew for now.  Many thanks for the very detailed update and let's hope whatever is causing all this gets sorted.  Very best, Chris

**Comment by robertstrom** [comment] 2024-09-22 20:53
So after playing with the Flatpak install on the Zorin VM I uninstalled the Flatpak CopyQ install (and told it to delete everything, not just the program) and installed the .deb version of CopyQ (the latest version 9) that was downloaded from the CopyQ GitHub site and it is just working! Crazy, crazy!! The backup on exit even worked. Still cannot get shortcuts to work (the one that is the most important - Show / Hide in particular). Some of the other items that I listed above as not working are not working, but not all.

The inconsistencies of what works and what does not are infuriating. It seems that Wayland implementations are not standardized on the various distros. Acckkkkkkkkkk!!!

Hopefully CopyQ developers are looking at these Wayland issues. If they are looking for testers I am game. I have CopyQ working fine on my main computers and have test systems that I can use to test various new builds.

**Comment by hluk** [comment] 2024-09-23 09:39
**Autostart** is not supported in the Flatpak app itself. It needs to be configured in the desktop environment: https://github.com/hluk/CopyQ/issues/2517#issuecomment-1779450657

> The program will not store the size and location as I have come to expect. It always opens up in the same place (not the last place where you placed it) and the same size (not the last size that you set it to). 

This is interesting. At least in KDE and Sway window manager, the app can set window size at least. Generally, setting window positions on Wayland is not supported. There could a protocol to set window geometry supported by some Wayland compositors because e.g. `krunner` can position itself at top of the screen - but it does not get keyboard focus :facepalm:. But using these protocols is somewhat difficult to implement. I would prefer to wait until Qt itself supports it ...if ever. :cry: 

I somehow got used to all the Wayland issues and keep run the app in Sway window manager. From my POV, the annoying issues are:
- the windows open in the middle of the screen - not a big deal since at least the size can be set
- pasting does not work by just activating the item from CopyQ - need to do additional Ctrl+V
- global shortcuts need to be configured in the desktop environment itself

> The inconsistencies of what works and what does not are infuriating. It seems that Wayland implementations are not standardized on the various distros.

Yeah, this is very annoying. For example, latest Gnome versions do not support access to the clipboard in inactive applications (this makes clipboard managers unusable). In other Wayland compositors there is a protocol to work around this (used by CopyQ), but it is not great.

**Comment by hluk** [comment] 2024-09-26 14:52
> So is there anything being done to standardize Wayland and to provide the capabilities of the likes of password managers and screenshot programs the access that they need?

The only thing that I can think of are the protocols: https://gitlab.freedesktop.org/wayland/wayland-protocols

The problem is that compositors/desktop-environments implement them inconsistently.

BTW, I tried using [KWayland](https://invent.kde.org/plasma/kwayland) library to see it can set window position (specific protocol must be supported by the compositor), but could [not get it working](https://github.com/hluk/CopyQ/commit/f4d48d0b841e4f16085d2a35d893cee2c0813468#diff-ccbbe1a5c4cce3d314df2f0974552ebe7e560d070d2da1c6c06c2ca8415987d1R330) (at least on Sway).

> In macOS you have the ability to allow programs access to what they need to access. You are prompted and then need to specifically allow them (many times you need to authenticate with your credentials to do so).

Yes, I would like that. If an app wants to access clipboard, ask me for a permission (once). I'm not sure how well it can be implemented since on Linux the apps are not signed, and I think there might be no safe way to identify a running app.

> Have you had any communication with the Wayland project about this?

Nope, I haven't talked to anyone in the Wayland project.

**Comment by cpsyctc2** [comment] 2024-09-26 18:55
As ever, so grateful to @hluk for this and for CopyQ.  I am out of my depth with those technical details but if I can help with any debugging information I am more than happy to try.  I may be of use as I am in the odd situation of having CopyQ working fine on one recently rebuilt Ubuntu 24.04.1 LTS where copyq -v reports:
```
CopyQ Clipboard Manager 7.1.0
Qt: 5.15.12
KNotifications: 5.115.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 24.04.1 LTS
```
I do see warnings in the CopyQ log on that machine, mostly repeats of this:
```
Warning [2024-09-26 20:24:17.695] <Server-7747>: [default] QtWarning: [31mQVariantMap DBusMenuExporterDBus::getProperties(int, const QStringList&) const[0m: Condition failed: action
```

However, I have totally failed to get it to work on another machine also built recently (a week earlier than this one) also with Ubuntu 24.04.1 LTS.  No installation I tried on that machine allows transfer of the clipboard contents to CopyQ.  For the moment I have abandoned the fight with that machine as it's a fallback machine so I can (currently) live without CopyQ on it.

I run updates daily on both machines but still sometimes see differences between the OS or gnome on the two machines which baffle me and they do have different hardware (both Intel CPUs).  I think I have purged all vestiges of CopyQ from the "bad" machine and am happy to try anything that might be helpful on that machine.  Just tell me what to do if you think this might help!  Very best both (and all), Chris

**Comment by hluk** [comment] 2024-09-27 06:17
> I do see warnings in the CopyQ log on that machine

That warning seems to be related to a DBus service running in the system (or possibly not running or misbehaving) or perhaps some problems with the Wayland protocols.

---

I think the easiest solution to **work around most problems on Wayland** is to set `QT_QPA_PLATFORM=xcb` environment variable when starting the app:

```bash
copyq exit  # close any running instance first
env QT_QPA_PLATFORM=xcb copyq --start-server
```

This will use some X11 compatibility layer (XWayland).

**Comment by cpsyctc2** [comment] 2024-09-30 19:10
Been a bit overloaded with work, back again.  I'm 99% sure I tried that on the machine where CopyQ fails to liaise with the clipboard and it made no difference but I am 1% sure.  Before I start experimenting again, can you (@hluk) tell me which route to reinstall CopyQ on the machine you would prefer me to use from a debugging/exploring point of view.  I am guessing it would be to put the /etc/apt pointer to your repository and then install with `apt update` and `apt install copyq` but I thought I should check.  TIA, Chris

**Comment by cpsyctc2** [comment] 2024-10-01 06:09
I really appreciate, as ever, all your time on this.  I can confirm that, with a clean install from the repository (as per docs!) and using 
`
copyq exit  # close any running instance first
env QT_QPA_PLATFORM=xcb copyq --start-server
`
CopyQ is now up and running on the other machine with import from and export to the clipboard there.  Hooray!

Many thanks again, Chris

**Comment by hluk** [comment] 2024-10-02 05:39
Glad it works now. I will close this since there is no action I can take now.

**Closed by hluk** 2024-10-02 05:39 UTC
Labels: bug, Wayland

**Comment by andresimi** [comment] 2024-10-02 20:57
I can confirm that this worked with the flatpak version in Fedora 40 Workstation Wayland.
I addedd this in the CopyQ configuration inside Flatseal.
![image](https://github.com/user-attachments/assets/9609cef4-d4cf-4f22-aab1-af5649ad03b1)

**Comment by robertstrom** [comment] 2024-10-12 17:42
@hluk - In a conversation with the folks working on the System 76 Cosmic DE (which is using Wayland) I was pointed to this video. Thought that I would pass it along. [Why YOU should write a Wayland compositor – Victoria Brekenfeld – HiP22 Berlin](https://www.youtube.com/watch?v=FUif2GxwgBc)

**Comment by russoue** [comment] 2025-01-11 22:39
> Hello, The command "QT_QPA_PLATFORM=xcb" worked for me. However, the keyboard shortcut to show the window still doesn't work. Do you have any solution?
> 
> ## Software information:
> * Wayland
> * Copyq Flatpak
> * Pantheon Desktop

It started working for me after I set the shortcut in `Preferences -> Shortcuts -> Show/hide main window`.

**Comment by russoue** [comment] 2025-01-11 22:43
However, I should note that CopyQ copying and the keyboard shortcut don't work if I quit it and not run the following -
```
env QT_QPA_PLATFORM=xcb copyq --start-server
```

**Comment by anchan42** [comment] 2025-02-25 12:42
I found that the shotcut setting is not working consistantly. I have to create a script and then assign system shotcut key to it.
`#!/bin/bash

# Check if CopyQ is running
if ! pgrep -x "copyq" > /dev/null; then
    # If CopyQ is not running, start it
    env QT_QPA_PLATFORM=xcb copyq --start-server &
    sleep 1  # Give it a moment to start
fi

# Get the current window visibility state
VISIBLE=$(copyq eval "visible()")

if [ "$VISIBLE" = "true" ]; then
    # If window is visible, hide it
    copyq hide
else
    # If window is hidden, show it
    copyq show
fi`

**Comment by lifeboy** [comment] 2025-03-14 12:05
This is indeed a most frustrating issue.  I have installed the flatpak version (on above recommendation), but it doesn't work "out of the box" either.  So I tried the following:

```
$ env | grep QT
QT_ACCESSIBILITY=1
QTWEBENGINE_DICTIONARIES_PATH=/usr/share/hunspell-bdic/
QT_QPA_PLATFORM=xcb
QT_IM_MODULE=ibus

```

```
$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=copyq com.github.hluk.copyq --start-server
$ terminate called after throwing an instance of '(anonymous namespace)::ExceptionQtFatal'
  what():  This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland-egl, linuxfb, xcb, vnc, eglfs, minimal, offscreen, vkkhrdisplay, minimalegl, wayland.

```

If I add "show", it still doesn't work.

```
$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=copyq com.github.hluk.copyq --start-server show
terminate called after throwing an instance of '(anonymous namespace)::ExceptionQtFatal'
  what():  This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland-egl, linuxfb, xcb, vnc, eglfs, minimal, offscreen, vkkhrdisplay, minimalegl, wayland.

ERROR: Cannot connect to server! Start CopyQ server first.
```

Without the env for QT, it runs, but it doesn't save an copy or cut operations.


```
# System Details Report
---

## Report details
- **Date generated:**                              2025-03-14 14:04:55

## Hardware Information:
- **Hardware Model:**                              ASUSTeK COMPUTER INC. ZenBook UX425EA_UX425EA
- **Memory:**                                      16.0 GiB
- **Processor:**                                   11th Gen Intel® Core™ i7-1165G7 × 8
- **Graphics:**                                    Intel® Xe Graphics (TGL GT2)
- **Disk Capacity:**                               512.1 GB

## Software Information:
- **Firmware Version:**                            UX425EA.319
- **OS Name:**                                     Ubuntu 24.04.2 LTS
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.11.0-17-generic

```

**Comment by arunvkrishnan** [comment] 2026-08-05 08:07
# Fixing CopyQ (Enter-to-paste) on Ubuntu 26.04 / GNOME / Wayland

If you upgraded from Ubuntu 22.04/23.x to 26.04 and your old CopyQ workflow
(`Ctrl+Shift+V` → arrow keys → `Enter` to paste directly into the focused
window) suddenly breaks with errors like:

```
Warning: Failed to get current window for pasting from clipboard
Note: Exception in command: ScriptError: Failed to paste clipboard
```

...it's because **Ubuntu 26.04's GNOME session dropped X11 entirely** (GNOME
50 removed the X11 session upstream, so there's no more "Ubuntu on Xorg"
option at login). CopyQ's paste-to-focused-window trick relied on X11 APIs
that Wayland blocks for security. Here's the fix.

## 1. Get CopyQ 14+ (needed for the GNOME clipboard extension)

The `ppa:hluk/copyq` PPA was stuck on 13.0.0 as of writing, and there was no
`.deb` in the GitHub release assets for 16.0.0 — only AppImage, Windows,
macOS builds. Used the AppImage:

```bash
wget https://github.com/hluk/CopyQ/releases/download/v16.0.0/CopyQ-16.0.0-x86_64.AppImage
chmod +x CopyQ-16.0.0-x86_64.AppImage
sudo ln -s /full/path/to/CopyQ-16.0.0-x86_64.AppImage /usr/local/bin/copyq
```
(Use the absolute path, not `~`, in the symlink target — `sudo` doesn't
always expand `~` the way you'd expect.)

## 2. Register a `.desktop` file (fixes GNOME portal "App info not found" warning)

```bash
mkdir -p ~/.local/share/applications
cat > ~/.local/share/applications/com.github.hluk.copyq.desktop << 'EOF'
[Desktop Entry]
Type=Application
Name=CopyQ
Comment=Clipboard Manager
Exec=copyq
Icon=copyq
Terminal=false
Categories=Utility;
StartupWMClass=CopyQ
EOF
update-desktop-database ~/.local/share/applications
```

## 3. Install the GNOME clipboard-monitor extension (bundled inside the AppImage)

```bash
./CopyQ-16.0.0-x86_64.AppImage --appimage-extract
cp -r squashfs-root/usr/share/gnome-shell/extensions/copyq-clipboard@hluk.github.com \
      ~/.local/share/gnome-shell/extensions/
```
Log out/in (GNOME only scans for new extensions at session start — no
soft-restart trick on Wayland), then:
```bash
gnome-extensions enable copyq-clipboard@hluk.github.com
```

## 4. Install `ydotool` (lets the paste-injection actually happen)

```bash
sudo apt install ydotool
sudo usermod -aG input $USER   # then log out/in
```
If `systemctl enable --now ydotoold` says the unit doesn't exist:
```bash
sudo tee /etc/systemd/system/ydotoold.service > /dev/null <<'EOF'
[Unit]
Description=ydotool daemon

[Service]
ExecStart=/usr/bin/ydotoold
Restart=always

[Install]
WantedBy=default.target
EOF
sudo systemctl daemon-reload
sudo systemctl enable --now ydotoold
```

## 5. Add the "Wayland Support" command

This isn't browsable inside CopyQ's UI — grab the raw script and import it:
```bash
sudo apt install wl-clipboard
curl -s https://raw.githubusercontent.com/hluk/copyq-commands/master/commands/wayland-support.ini | wl-copy
```
In CopyQ: `F6` (Command dialog) → **Paste Commands** (or `Ctrl+V`) → confirm
the "Wayland Support" entry appears → **OK**. Add it as its **own** command —
it doesn't nest inside anything else. It works by overriding CopyQ's internal
`paste()`/`copy()` functions to shell out to `ydotool` instead of X11 calls.

Source: [[hluk/copyq-commands](https://github.com/hluk/copyq-commands)](https://github.com/hluk/copyq-commands)
(`commands/wayland-support.ini`).

## 6. Enable paste settings + bind the shortcut via GNOME

- CopyQ **Preferences → History** → enable "Paste to current window"
- CopyQ **Preferences → Tray** → enable "Paste activated item to current window"
- **GNOME Settings → Keyboard → Custom Shortcuts → +**
  - Command: `copyq toggle`
  - Shortcut: `Ctrl+Shift+V`

(Bind it here rather than inside CopyQ — GNOME's own shortcut portal support
for third-party apps is still shaky.)

## 7. Test

`Ctrl+C` → `Ctrl+Shift+V` → arrow to item → `Enter`. Confirmed working in
Sublime, IntelliJ, MS Teams, and browser (Azure DevOps comment box) text
fields — including image paste.

---

**Environment:** Ubuntu 26.04 LTS, GNOME (default/Wayland session), CopyQ 16.0.0.
