### ISSUE TITLE
Can't use Notepad++ as external editor (Windows)

### ISSUE THREAD

**Issue by glolsh** [hluk/CopyQ#1193] opened 2019-08-14 04:05 UTC
**Describe the bug**
When I use command: notepad++ %1 to use notepad plus plus as external editor - it opens notepad app with message  `
"C:\Users\_user_\AppData\Local\Temp\CopyQ.ey6800.txt" doesn't exist. Create it?
`
I checked this directory. No such file is there. But when I use simple Notepad (windows preinstalled) - it is there.

**Prerequisites**
Notepad++ x64 installed

**To Reproduce**
1. Go to Preferences
2. Paste command notepad++ %1 in external editor command field
3. Save
4. Call Copyq
5. Ctrl+E (call external editor)
6. Get message

**Expected behavior**
Selected clipboard can be edited in External Editor Notepad++
temp file is created in C:\Users\_user_\AppData\Local\Temp

**Version, OS and Environment**
OS Windows 10
Copyq 3.9.0

**Additional context**
Maybe there is no bug here, then please add info how to work with Notepad++ to Docs

**Comment by hluk** [comment] 2019-08-14 15:54
> I checked this directory. No such file is there. But when I use simple Notepad (windows preinstalled) - it is there.

The temporary file is removed after editor is closed, that's expected behavior.

This is also the reason that editors like `gvim` need special argument (`gvim -f`) to launch in "foreground" instead of launching separate detached process and exiting immediately.

Is that the case also with notepad++? I cannot test this now and I fail to find help for arguments online.

**Comment by glolsh** [comment] 2019-08-15 02:19
@hluk Sadly - I checked directory WHILE editor is opened. No file here. In other hand - when windows notepad is opened - file is here, so I suspect that file is not created when notepad++ is in charge)

**Comment by hluk** [comment] 2019-08-15 06:12
Did you check if executing `notepad++` from command line (`cmd` or `powershell`) immediately quits the process but editor is launched?

Otherwise, I see no reason for CopyQ to remove the file.

**Comment by glolsh** [comment] 2019-08-15 08:00
Yep, you're right. I suspect there is no solutions here and now.

**Comment by hluk** [comment] 2019-08-15 11:35
You could try `notepad++ --help` or something to list parameters. There could be one that allows it to be executed in foreground.

See also: https://notepad-plus-plus.org/community/topic/15236/how-to-launch-notepad-synchronously

**Comment by glolsh** [comment] 2019-08-19 01:28
> You could try notepad++ --help or something to list parameters. There could be one that allows it to be executed in foreground.
Tried, nothing too much usable.

This one should work (if started from cmd it waits till Notepad++ is closed), but it fails to start from Copyq
`START /wait "" "C:\Program Files\Notepad++\notepad++.exe" -multiInst %1`

**Comment by hluk** [comment] 2019-08-25 06:42
Yeah, looks like those commands no longer work. I couldn't find a way to launch notepad++ in foreground.

**Comment by glolsh** [comment] 2019-08-26 07:21
Those commands work if launched outside copyq. (at least Notepad++ is not separating itself from CMD)

**Comment by hluk** [comment] 2019-08-26 07:41
Oh, I the command didn't work for me when launched from console or batch script.

BTW, in CopyQ I think you will have to prefix `START` with `cmd /k`.

```
cmd /k START /wait "" "notepad++.exe" -multiInst %1
```

**Comment by glolsh** [comment] 2019-08-27 08:57
No luck here. Guess it won't work. Suggest external editor for Windows?

**Comment by hluk** [comment] 2019-08-27 10:15
Well, notepad works, but I usually use build-in editor.

**Comment by glolsh** [comment] 2019-08-28 02:03
Will you attempt to find a solution on your side or we close this issue as "Won't fix"?))

**Comment by hluk** [comment] 2019-08-28 06:07
> Will you attempt to find a solution on your side or we close this issue as "Won't fix"?))

I don't see other way to know that the file is still being edited. While the file is open in notepad++, it's not locked and I don't see any `.swp` file.

If you don't have other ideas then you can close this.

**Closed** 2019-08-29 02:25 UTC
Labels: bug

**Comment by RSchiaffino** [comment] 2024-02-08 17:24
Works for me in CopyQ with 
"C:\Program Files\NotePad++\Notepad++.exe" %1
as the "External editor comman" in the preferences
