### ISSUE TITLE
Icon of the system tray hidden

### ISSUE THREAD

**Issue by wetware05** [hluk/CopyQ#1343] opened 2020-04-07 11:20 UTC
**Describe the bug**
The icon of the system tray, in windows 10, always appears hidden when turning on the computer (if it is put back to its place, either manually, or through the configuration of the taskbar, in the next reboot will happen again). It doesn't happen 100% of the time. It is very uncomfortable, repositioning it over and over again. I thought that something could be wrong with the system, but recently I installed the system from 0 and the same happens, then it must be for something in Copyq.

**Version, OS and Environment**
Windows 10 1909
CopyQ 3.10

**Comment by hluk** [comment] 2020-04-08 16:54
Closing as duplicate of #1258.

Workaround is to use different CopyQ build: https://ci.appveyor.com/project/hluk/copyq/builds/30554651/job/bi7n6lpdjvqy4e5x/artifacts

**Closed** 2020-04-08 16:54 UTC
Labels: bug
