### ISSUE TITLE
Slow on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by panzelva** [hluk/CopyQ#1382] opened 2020-05-12 16:48 UTC
**Describe the bug**
After upgrade to Ubuntu 20.04 LTS, CopyQ is very slow and chopy. Copying and pasting takes several seconds and when opening CopyQ, its main screen its very laggy.

**To Reproduce**
Use CopyQ on Ubuntu 20.04 LTS.

**Version, OS and Environment**
CopyQ Clipboard Manager v3.10.0
Qt: 5.12.5
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 20.04 LTS

**Comment by andrej-zirko** [comment] 2020-05-14 11:34
I can confirm this. It's laggy and barely usable.

ii  copyq                                         3.10.0-1                                   amd64        Advanced clipboard manager with editing and scripting features

**Comment by hluk** [comment] 2020-05-14 17:45
Can you upgrade to the latest version (v3.11.1 at this time)?

**Comment by andrej-zirko** [comment] 2020-05-14 18:39
I upgraded to latest version using PPA. Unfortunately the issue persists. Please let me know if there are any logs I can provide.

ii  copyq                                         3.11.1~focal                               amd64        Advanced clipboard manager with editing and scripting features

**Comment by hluk** [comment] 2020-05-15 11:37
Wait, is new Ubuntu using Wayland now? In that case, I think CopyQ is stuck accessing clipboard. You can try starting the app with:

```
env QT_QPA_PLATFORM=xcb copyq
```

See details in [this comment](https://github.com/hluk/CopyQ/issues/27#issuecomment-549766568).

**Comment by andrej-zirko** [comment] 2020-05-15 11:51
Ubuntu doesn't run Wayland by default yet. I don't run wayland. I tried QT_QPA_PLATFORM anyways and it didn't helpt.

The issue seems to be related to UI itself. When I browse the clipboard history, the cursor barely moves, surprisingly gnome-shell process hits 100% CPU and CPU fans are instantly on.

**Comment by hluk** [comment] 2020-05-15 12:33
Can you check logs? Ideally, launch the app with `env COPYQ_LOG_LEVEL=DEBUG copyq` and check logs from main window (F12 shortcut).

**Comment by andrej-zirko** [comment] 2020-05-15 12:58
I checked the logs. Unfortunately nothing was logged when I browsed through the clipboard history.
Scrolling through history jumps and gnome-shell CPU usage goes really high. It settles down, once copyQ is closed.  

[copyq.log](https://github.com/hluk/CopyQ/files/4634404/copyq.log)
![CopyQ](https://user-images.githubusercontent.com/7345510/82052730-6cb46080-96bc-11ea-8f5a-518dfaf819ac.gif)

**Comment by hluk** [comment] 2020-05-15 13:18
Thanks, for the recording. It looks like gnome-shell is eating the CPU even when the app window is closed and CopyQ is not doing much. Could be an issue in gnome-shell or its window manager.

I'll try to reproduce it in a VM.

**Comment by andrej-zirko** [comment] 2020-05-15 13:32
I noticed it now too. That's cause by the recording I'm afraid. I tried without recording and as soon as the CopyQ window is closed, usage drops.
I didn't find any other apps causing this issue. If you have any sample app using the same UI component in mind, please let me know. I could test some other app. 

I'm using CopyQ on my Mac without any issues. I'd love to use the same on my Ubuntu.

**Comment by hluk** [comment] 2020-05-15 16:18
I cannot reproduce this in VM unless I change the scaling factor in Gnome, but then I'm not sure if it isn't problem in the VM provider. It could be some scaling issue in Qt or some gnome part.

Can you try start the app with following?

```
env QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCALE_FACTOR=1 QT_SCREEN_SCALE_FACTORS=1 copyq
```

**Comment by hluk** [comment] 2020-05-15 16:56
I think I found the reason for the slowdown. It's because gnome asks the application to provide a high resolution icon and CopyQ often changes its window/tray icon to show that it's running some commands/scripts. In this case, when you browse items in the list, it's checking if it can enable some menu/toolbar actions (i.e. menu commands with filters set).

**Workaround** now is to disable these menu items in Command dialog (F6 shortcut). By default, **the commands to disable** are:
- **Tag as “Important”**
- **Remove tag “Important”**

I'll probably just remove the changing app icon feature because it's difficult to test and maintain. Also, some people asked me how to disable it.

**Comment by andrej-zirko** [comment] 2020-05-15 19:19
Disabling the two commands fixes the issue for me. It now performs as expected.

Thank you very much.

**Comment by hluk** [comment] 2020-05-16 04:19
The performance problems are caused by the tray in Gnome (or the Qt integration it uses).

So, alternative to removing the commands I mentioned above, is to disable tray icon (in Tray configuration tab).

**Comment by panzelva** [comment] 2020-05-16 17:31
Disabling tray icon worked for me :)

**Comment by wada3n** [comment] 2020-05-16 23:53
Bonjour à toutes :)
I'm using ubuntu 20.04 also and there are no problems.
Note that I use kvantum engine for QT apps, could the default style of QT be the reason ?? 
that's Strange.

**Comment by andrej-zirko** [comment] 2020-05-17 09:32
The issue might be with scaling as this "env QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCALE_FACTOR=1 QT_SCREEN_SCALE_FACTORS=1" has worked for me as well.

I have high res screen (14" 2560x1440) and thus the scaling is by default set to 200%. I'd assume it might get even worse with fractional scaling.

**Comment by philippotto** [comment] 2020-10-09 13:56
Just want note that this workaround...

> **Workaround** now is to disable these menu items in Command dialog (F6 shortcut). By default, **the commands to disable** are:
> 
> * **Tag as “Important”**
> * **Remove tag “Important”**

... does not fix the performance problem for me. Each copy-action still invokes the "scissor-animation" in the tray with a noticeable lag.


> So, alternative to removing the commands I mentioned above, is to disable tray icon (in Tray configuration tab).

This worked for me :) It would be great to keep the tray, though (without the changing icon).

Awesome software, by the way!

**Comment by hluk** [comment] 2020-10-09 15:12
This was fixed in recent versions -- there is no tray icon animation. You can install the latest version from PPA (see the [documentation](https://copyq.readthedocs.io/en/latest/installation.html) for details).

**Comment by TomaszWaszczyk** [comment] 2020-12-21 12:17
Have the same ;/;/////////////////

**Comment by clappis** [comment] 2020-12-22 02:18
Have the same problem

```
CopyQ Clipboard Manager v3.13.0
Qt: 5.12.8
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 20.04.1 LTS
```

**Comment by hluk** [comment] 2020-12-22 05:49
I assume this issue was related to the icon animation which got removed in newer version so this has already been fixed.

Please open new issue if you still see problems and provide more information (with logs and information about when the issue occurs and how to reproduce it if possible).

NOTE: If you are using Wayland, you should check #27.

**Closed by hluk** 2020-12-22 05:49 UTC
Labels: bug
