### ISSUE TITLE
'can't open application' error on macOS Big Sur 

### ISSUE THREAD

**Issue by MemeFormer** [hluk/CopyQ#2716] opened 2024-05-11 15:28 UTC
## **Describe the bug**

when trying to open after fresh install with `brew install --cask copyq` I get this:

<img width="262" alt="Screen Shot 2024-05-11 at 5 07 18 PM" src="https://github.com/hluk/CopyQ/assets/130863507/102082ef-3936-446e-8c0e-b9792f3334bb">

<img width="266" alt="Screen Shot 2024-05-11 at 5 07 02 PM" src="https://github.com/hluk/CopyQ/assets/130863507/95385452-7feb-4bf0-993a-804257d11548">

## **Version, OS and Environment**

<img width="285" alt="Screen Shot 2024-05-11 at 5 08 02 PM" src="https://github.com/hluk/CopyQ/assets/130863507/09953471-4fdc-4883-9775-ca05cdd9137e">

## **Application Version:**

well, about that.. 
**even if**

<img width="654" alt="Screen Shot 2024-05-11 at 5 18 27 PM" src="https://github.com/hluk/CopyQ/assets/130863507/c0c26174-1882-4533-96f1-6b06c45732a9">

**and**

<img width="784" alt="Screen Shot 2024-05-11 at 5 19 09 PM" src="https://github.com/hluk/CopyQ/assets/130863507/c59ff58d-2db6-4b44-ad5c-0b1f8d342d33">

**there is**

<img width="425" alt="Screen Shot 2024-05-11 at 5 19 42 PM" src="https://github.com/hluk/CopyQ/assets/130863507/2665b6c0-7225-45e5-9197-95f506a24598">

**???**

**Comment by zishuzy** [comment] 2024-05-12 10:26
Me too.

**Comment by rsshilli** [comment] 2024-05-13 19:04
It looks broke on Sonoma as well.
![image](https://github.com/hluk/CopyQ/assets/2487045/bf5ef668-09fc-4526-934c-d0f119663c51)

**Comment by rsshilli** [comment] 2024-05-13 19:09
Oh. From https://github.com/hluk/CopyQ/issues/1331 I learned this trick. It fixed it for me:
```
xattr -d com.apple.quarantine /Applications/CopyQ.app
codesign --force --deep --sign - /Applications/CopyQ.app
```

**Comment by MemeFormer** [comment] 2024-05-22 20:57
### Troubleshooting and Solution for CopyQ Installation Issue on macOS BigSur 11.7.10

**Issue:** Unable to run CopyQ after installation on macOS due to a specific `Dyld Error Message` indicating missing symbols related to Qt libraries.

#### Initial Steps and Encountered Issues:

1. **Confirmed Installation Location:**
   - Verified the location of CopyQ installation using:
     ```sh
     ls /Applications | grep CopyQ
     mdfind "kMDItemDisplayName == 'CopyQ' && kMDItemKind == 'Application'"
     open -a CopyQ
     ```

2. **Encountered Error:**
   - Dyld Error Message:
     ```
     Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
     Referenced from: /Applications/CopyQ.app/Contents/MacOS/../Frameworks/QtWidgets.framework/Versions/A/QtWidgets (which was built for Mac OS X 12.0)
     Expected in: /usr/lib/libc++.1.dylib
     ```

3. **Initial Troubleshooting Steps:**
   - Attempted to reinstall CopyQ via Homebrew:
     ```sh
     brew install --cask copyq
     ```

4. **Further Issues:**
   - Homebrew upgrade process got stuck multiple times during `llvm` build.
   - Encountered errors when trying to install Qt due to missing full Xcode installation:
     ```sh
     brew install qt
     brew link --force qt
     ```

#### Final Solution:

1. **Resolution via .dmg Installer:**
   - Decided to use an older version of CopyQ available as a `.dmg` file.
   - Downloaded and installed [CopyQ](https://github.com/hluk/CopyQ/releases/download/v6.3.0/CopyQ.dmg.zip) `6.3.0-gbf2d498e-v6.3.0` from the [CopyQ GitHub releases page](https://github.com/hluk/CopyQ/releases).
   - The installation went smoothly with no issues.

2. **Clarification on Alternative Suggestion:**
   - A commenter suggested dealing with macOS security prompts using command line, but this was unrelated to the underlying issue. 
   - These security prompts can generally be bypassed by right-clicking (or Ctrl+clicking) the application and selecting "Open".

#### Additional Notes:

- **Homebrew Fix Not Possible:**
  - Due to the extensive time and resource requirements for building `llvm` and installing Qt, updating Homebrew dependencies wasn't feasible in this case.
  
- **Specific Error Analysis:**
  - The initial error was related to a mismatch or missing Qt library built for a different macOS version. This pointed us towards updating dependencies, which led to discovering the Xcode requirement.

- **Potential for Newer .dmg Versions:**
  - While version `6.3.0` worked, other newer versions might also work. Users are encouraged to try different versions if necessary.

### Conclusion

Using an older `.dmg` version of CopyQ proved to be a successful workaround, bypassing the complex dependency issues faced with Homebrew installations. This approach may save time and avoid the intricacies of manually resolving build errors for others encountering similar problems.

**Comment by hluk** [comment] 2024-05-23 08:05
I hope some of the issues are fixed in #2661. :crossed_fingers:

**Comment by joshpetit** [comment] 2024-06-19 20:51
> Oh. From #1331 I learned this trick. It fixed it for me:
> 
> ```
> xattr -d com.apple.quarantine /Applications/CopyQ.app
> codesign --force --deep --sign - /Applications/CopyQ.app
> ```

To make this more easily findable on google, this fixes the
"copyq is damaged and can't be opened" error

**Comment by hluk** [comment] 2024-06-25 12:42
Closing as duplicate of #2652.

I'm updating installation steps in #2757.

**Closed by hluk** 2024-06-25 12:42 UTC
Labels: bug, macOS, help wanted
