### ISSUE TITLE
Encryption Problem

### ISSUE THREAD

**Issue by bor2** [hluk/CopyQ#933] opened 2018-04-29 18:16 UTC
Hello there,
I'm not sure if it's a bug or me.   I downloaded and installed the latest version of Gpg4win ( 3.1.0 2018-04-13)  but the Encryption plugin is not recognizing GnuPG on my computer.  Rebooted the comp, restarted CopyQ - nothing happens.  Same thing on my laptop.  My understanding was that once installed it should be visible to the Encryption plugin.  What am I doing wrong? Thanks
Boris

**Comment by hluk** [comment] 2018-04-29 19:00
Did you check [this quide](http://copyq.readthedocs.io/en/latest/password-protection.html)?

Are there any errors in log (F12 shortcut)?

**Comment by bor2** [comment] 2018-04-30 02:34
Hi Lukas,
Thank you for a quick response.  I sure did read the guide.  On the desktop, there are no errors in the log when I press F12. I believe this is due to the fact that the encryption command is disabled, i.e. there is no button to click to encrypt because the encryption engine is not accessible.  This is CopyQ version 3.4.0. which I installed today.  The laptop has an older version 3.3.1.  which allows you to click the Encrypt button despite the fact that there is no encryption engine connected and I get this

Note [2016-11-22 17:51:45.533]: No plugins loaded
ERROR [2016-11-22 18:13:26.358]: Remote process: Connection timeout!
ERROR [2016-11-22 18:15:52.978]: Failed to read message from client!
ERROR [2016-11-22 18:17:00.477]: Failed to read message from client!
ERROR [2016-11-22 18:17:19.884]: Failed to read message from client!
ERROR [2016-11-22 18:26:02.429]: Failed to read message from client!
ERROR [2016-11-22 18:26:40.632]: Failed to read message from client!
ERROR [2016-11-22 18:55:37.726]: Failed to read message from client!
Note [2016-11-24 13:08:37.829]: No plugins loaded
Note [2016-11-28 07:33:48.517]: No plugins loaded
Note [2016-11-30 03:50:57.887]: No plugins loaded
Note [2018-04-28 16:01:11.852]: No plugins loaded
ERROR [2018-04-28 16:14:45.212]: Remote process: Connection timeout!
ERROR [2018-04-28 16:15:34.164]: Remote process: Connection timeout!
Note [2018-04-28 18:29:58.225] Client-34372: ScriptError: Exception in command "eval": Failed to execute GPG!
Note [2018-04-28 18:29:58.225] Client-34372:    
Note [2018-04-28 18:29:58.225] Client-34372:    --- backtrace ---
Note [2018-04-28 18:29:58.225] Client-34372:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 18:29:58.225] Client-34372:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 18:29:58.225] Client-34372:    --- end backtrace ---
Note [2018-04-28 18:29:58.240] Server-35504: Command “Encrypt (needs GnuPG)”
Note [2018-04-28 18:29:58.240] Server-35504:    Exit code: 4
Note [2018-04-28 18:29:58.240] Server-35504:    ScriptError: Failed to execute GPG!
Note [2018-04-28 18:29:58.240] Server-35504:    
Note [2018-04-28 18:29:58.240] Server-35504:    --- backtrace ---
Note [2018-04-28 18:29:58.240] Server-35504:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 18:29:58.240] Server-35504:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 18:29:58.240] Server-35504:    --- end backtrace ---
Note [2018-04-28 18:29:58.240] Server-35504:    
Note [2018-04-28 18:29:58.240] Server-35504:    1. copyq:  plugins.itemencrypted.encryptItems()
Note [2018-04-28 18:31:33.975] Client-44964: ScriptError: Exception in command "eval": Failed to execute GPG!
Note [2018-04-28 18:31:33.975] Client-44964:    
Note [2018-04-28 18:31:33.975] Client-44964:    --- backtrace ---
Note [2018-04-28 18:31:33.975] Client-44964:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 18:31:33.975] Client-44964:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 18:31:33.975] Client-44964:    --- end backtrace ---
Note [2018-04-28 18:31:33.991] Server-35504: Command “Encrypt (needs GnuPG)”
Note [2018-04-28 18:31:33.991] Server-35504:    Exit code: 4
Note [2018-04-28 18:31:33.991] Server-35504:    ScriptError: Failed to execute GPG!
Note [2018-04-28 18:31:33.991] Server-35504:    
Note [2018-04-28 18:31:33.991] Server-35504:    --- backtrace ---
Note [2018-04-28 18:31:33.991] Server-35504:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 18:31:33.991] Server-35504:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 18:31:33.991] Server-35504:    --- end backtrace ---
Note [2018-04-28 18:31:33.991] Server-35504:    
Note [2018-04-28 18:31:33.991] Server-35504:    1. copyq:  plugins.itemencrypted.encryptItems()
Note [2018-04-28 18:31:40.288] Client-40584: ScriptError: Exception in command "eval": Failed to execute GPG!
Note [2018-04-28 18:31:40.288] Client-40584:    
Note [2018-04-28 18:31:40.288] Client-40584:    --- backtrace ---
Note [2018-04-28 18:31:40.288] Client-40584:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 18:31:40.288] Client-40584:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 18:31:40.288] Client-40584:    --- end backtrace ---
Note [2018-04-28 18:31:40.304] Server-35504: Command “Encrypt (needs GnuPG)”
Note [2018-04-28 18:31:40.304] Server-35504:    Exit code: 4
Note [2018-04-28 18:31:40.304] Server-35504:    ScriptError: Failed to execute GPG!
Note [2018-04-28 18:31:40.304] Server-35504:    
Note [2018-04-28 18:31:40.304] Server-35504:    --- backtrace ---
Note [2018-04-28 18:31:40.304] Server-35504:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 18:31:40.304] Server-35504:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 18:31:40.304] Server-35504:    --- end backtrace ---
Note [2018-04-28 18:31:40.304] Server-35504:    
Note [2018-04-28 18:31:40.304] Server-35504:    1. copyq:  plugins.itemencrypted.encryptItems()
Warning [2018-04-28 18:32:31.940] Server-44996: CopyQ server is already running.
Note [2018-04-28 18:38:58.579] Client-42568: ScriptError: Exception in command "eval": Failed to execute GPG!
Note [2018-04-28 18:38:58.579] Client-42568:    
Note [2018-04-28 18:38:58.579] Client-42568:    --- backtrace ---
Note [2018-04-28 18:38:58.579] Client-42568:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 18:38:58.579] Client-42568:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 18:38:58.579] Client-42568:    --- end backtrace ---
Note [2018-04-28 18:38:58.594] Server-35504: Command “Encrypt (needs GnuPG)”
Note [2018-04-28 18:38:58.594] Server-35504:    Exit code: 4
Note [2018-04-28 18:38:58.594] Server-35504:    ScriptError: Failed to execute GPG!
Note [2018-04-28 18:38:58.594] Server-35504:    
Note [2018-04-28 18:38:58.594] Server-35504:    --- backtrace ---
Note [2018-04-28 18:38:58.594] Server-35504:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 18:38:58.594] Server-35504:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 18:38:58.594] Server-35504:    --- end backtrace ---
Note [2018-04-28 18:38:58.594] Server-35504:    
Note [2018-04-28 18:38:58.594] Server-35504:    1. copyq:  plugins.itemencrypted.encryptItems()
Note [2018-04-28 20:19:16.546] Client-53896: ScriptError: Exception in command "eval": Failed to execute GPG!
Note [2018-04-28 20:19:16.546] Client-53896:    
Note [2018-04-28 20:19:16.546] Client-53896:    --- backtrace ---
Note [2018-04-28 20:19:16.546] Client-53896:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 20:19:16.546] Client-53896:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 20:19:16.546] Client-53896:    --- end backtrace ---
Note [2018-04-28 20:19:16.561] Server-35504: Command “Encrypt (needs GnuPG)”
Note [2018-04-28 20:19:16.561] Server-35504:    Exit code: 4
Note [2018-04-28 20:19:16.561] Server-35504:    ScriptError: Failed to execute GPG!
Note [2018-04-28 20:19:16.561] Server-35504:    
Note [2018-04-28 20:19:16.561] Server-35504:    --- backtrace ---
Note [2018-04-28 20:19:16.561] Server-35504:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 20:19:16.561] Server-35504:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 20:19:16.561] Server-35504:    --- end backtrace ---
Note [2018-04-28 20:19:16.561] Server-35504:    
Note [2018-04-28 20:19:16.561] Server-35504:    1. copyq:  plugins.itemencrypted.encryptItems()
Note [2018-04-28 20:37:43.052] Client-2128: ScriptError: Exception in command "eval": Failed to execute GPG!
Note [2018-04-28 20:37:43.052] Client-2128:    
Note [2018-04-28 20:37:43.052] Client-2128:    --- backtrace ---
Note [2018-04-28 20:37:43.052] Client-2128:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 20:37:43.052] Client-2128:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 20:37:43.052] Client-2128:    --- end backtrace ---
Note [2018-04-28 20:37:43.067] Server-35504: Command “Encrypt (needs GnuPG)”
Note [2018-04-28 20:37:43.067] Server-35504:    Exit code: 4
Note [2018-04-28 20:37:43.067] Server-35504:    ScriptError: Failed to execute GPG!
Note [2018-04-28 20:37:43.067] Server-35504:    
Note [2018-04-28 20:37:43.067] Server-35504:    --- backtrace ---
Note [2018-04-28 20:37:43.067] Server-35504:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 20:37:43.067] Server-35504:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 20:37:43.067] Server-35504:    --- end backtrace ---
Note [2018-04-28 20:37:43.067] Server-35504:    
Note [2018-04-28 20:37:43.067] Server-35504:    1. copyq:  plugins.itemencrypted.encryptItems()
ERROR [2018-04-28 20:45:47.662] Server-35504: ERROR: Socket disconnected before receiving message
Note [2018-04-28 20:45:48.607] Server-35504: Command “copyq monitorClipboard”
Note [2018-04-28 20:45:48.607] Server-35504:    Error: Process crashed
Note [2018-04-28 20:45:48.607] Server-35504:    1. copyq monitorClipboard
Note [2018-04-28 20:48:41.446] Client-11432: ScriptError: Exception in command "eval": Failed to execute GPG!
Note [2018-04-28 20:48:41.446] Client-11432:    
Note [2018-04-28 20:48:41.446] Client-11432:    --- backtrace ---
Note [2018-04-28 20:48:41.446] Client-11432:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 20:48:41.446] Client-11432:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 20:48:41.446] Client-11432:    --- end backtrace ---
Note [2018-04-28 20:48:41.461] Server-5096: Command “Encrypt (needs GnuPG)”
Note [2018-04-28 20:48:41.461] Server-5096:    Exit code: 4
Note [2018-04-28 20:48:41.461] Server-5096:    ScriptError: Failed to execute GPG!
Note [2018-04-28 20:48:41.461] Server-5096:    
Note [2018-04-28 20:48:41.461] Server-5096:    --- backtrace ---
Note [2018-04-28 20:48:41.461] Server-5096:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 20:48:41.461] Server-5096:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 20:48:41.461] Server-5096:    --- end backtrace ---
Note [2018-04-28 20:48:41.461] Server-5096:    
Note [2018-04-28 20:48:41.461] Server-5096:    1. copyq:  plugins.itemencrypted.encryptItems()
Note [2018-04-28 21:17:43.198] Server-5096: Command “copyq monitorClipboard”
Note [2018-04-28 21:17:43.198] Server-5096:    Error: Process crashed
Note [2018-04-28 21:17:43.198] Server-5096:    1. copyq monitorClipboard
Note [2018-04-28 21:21:19.746] Client-11344: ScriptError: Exception in command "eval": Failed to execute GPG!
Note [2018-04-28 21:21:19.746] Client-11344:    
Note [2018-04-28 21:21:19.746] Client-11344:    --- backtrace ---
Note [2018-04-28 21:21:19.746] Client-11344:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 21:21:19.746] Client-11344:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 21:21:19.746] Client-11344:    --- end backtrace ---
Note [2018-04-28 21:21:19.761] Server-7884: Command “Encrypt (needs GnuPG)”
Note [2018-04-28 21:21:19.761] Server-7884:    Exit code: 4
Note [2018-04-28 21:21:19.761] Server-7884:    ScriptError: Failed to execute GPG!
Note [2018-04-28 21:21:19.761] Server-7884:    
Note [2018-04-28 21:21:19.761] Server-7884:    --- backtrace ---
Note [2018-04-28 21:21:19.761] Server-7884:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 21:21:19.761] Server-7884:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 21:21:19.761] Server-7884:    --- end backtrace ---
Note [2018-04-28 21:21:19.761] Server-7884:    
Note [2018-04-28 21:21:19.761] Server-7884:    1. copyq:  plugins.itemencrypted.encryptItems()
Note [2018-04-28 21:38:40.140] Client-12364: ScriptError: Exception in command "eval": Failed to execute GPG!
Note [2018-04-28 21:38:40.140] Client-12364:    
Note [2018-04-28 21:38:40.140] Client-12364:    --- backtrace ---
Note [2018-04-28 21:38:40.140] Client-12364:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 21:38:40.140] Client-12364:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 21:38:40.140] Client-12364:    --- end backtrace ---
Note [2018-04-28 21:38:40.155] Server-7884: Command “Encrypt (needs GnuPG)”
Note [2018-04-28 21:38:40.155] Server-7884:    Exit code: 4
Note [2018-04-28 21:38:40.155] Server-7884:    ScriptError: Failed to execute GPG!
Note [2018-04-28 21:38:40.155] Server-7884:    
Note [2018-04-28 21:38:40.155] Server-7884:    --- backtrace ---
Note [2018-04-28 21:38:40.155] Server-7884:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 21:38:40.155] Server-7884:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 21:38:40.155] Server-7884:    --- end backtrace ---
Note [2018-04-28 21:38:40.155] Server-7884:    
Note [2018-04-28 21:38:40.155] Server-7884:    1. copyq:  plugins.itemencrypted.encryptItems()
Note [2018-04-28 21:50:42.575] Client-8896: ScriptError: Exception in command "eval": Failed to execute GPG!
Note [2018-04-28 21:50:42.575] Client-8896:    
Note [2018-04-28 21:50:42.575] Client-8896:    --- backtrace ---
Note [2018-04-28 21:50:42.575] Client-8896:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 21:50:42.575] Client-8896:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 21:50:42.575] Client-8896:    --- end backtrace ---
Note [2018-04-28 21:50:42.591] Server-7884: Command “Encrypt (needs GnuPG)”
Note [2018-04-28 21:50:42.591] Server-7884:    Exit code: 4
Note [2018-04-28 21:50:42.591] Server-7884:    ScriptError: Failed to execute GPG!
Note [2018-04-28 21:50:42.591] Server-7884:    
Note [2018-04-28 21:50:42.591] Server-7884:    --- backtrace ---
Note [2018-04-28 21:50:42.591] Server-7884:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 21:50:42.591] Server-7884:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 21:50:42.591] Server-7884:    --- end backtrace ---
Note [2018-04-28 21:50:42.591] Server-7884:    
Note [2018-04-28 21:50:42.591] Server-7884:    1. copyq:  plugins.itemencrypted.encryptItems()
Note [2018-04-28 21:55:31.706] Client-14056: ScriptError: Exception in command "eval": Failed to execute GPG!
Note [2018-04-28 21:55:31.706] Client-14056:    
Note [2018-04-28 21:55:31.706] Client-14056:    --- backtrace ---
Note [2018-04-28 21:55:31.706] Client-14056:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 21:55:31.706] Client-14056:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 21:55:31.706] Client-14056:    --- end backtrace ---
Note [2018-04-28 21:55:31.722] Server-7884: Command “Encrypt (needs GnuPG)”
Note [2018-04-28 21:55:31.722] Server-7884:    Exit code: 4
Note [2018-04-28 21:55:31.722] Server-7884:    ScriptError: Failed to execute GPG!
Note [2018-04-28 21:55:31.722] Server-7884:    
Note [2018-04-28 21:55:31.722] Server-7884:    --- backtrace ---
Note [2018-04-28 21:55:31.722] Server-7884:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 21:55:31.722] Server-7884:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 21:55:31.722] Server-7884:    --- end backtrace ---
Note [2018-04-28 21:55:31.722] Server-7884:    
Note [2018-04-28 21:55:31.722] Server-7884:    1. copyq:  plugins.itemencrypted.encryptItems()
ERROR [2018-04-28 22:08:45.456] : ItemEncrypt ERROR: GnuPG stderr:
ERROR [2018-04-28 22:08:45.456] :    gpg: keyring `C:/Users/Boris/AppData/Roaming/gnupg/secring.gpg' created
ERROR [2018-04-28 22:08:45.456] :    gpg: keyring `C:\\Users\\Boris\\AppData\\Roaming\\copyq\\copyq.pub' created
ERROR [2018-04-28 22:08:45.456] :    gpg: copyq: skipped: No public key
ERROR [2018-04-28 22:08:45.456] :    gpg: [stdin]: encryption failed: No public key
ERROR [2018-04-28 22:08:45.456] :    
Note [2018-04-28 22:08:45.456] Client-9992: ScriptError: Exception in command "eval": Failed to execute GPG!
Note [2018-04-28 22:08:45.456] Client-9992:    
Note [2018-04-28 22:08:45.456] Client-9992:    --- backtrace ---
Note [2018-04-28 22:08:45.456] Client-9992:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 22:08:45.456] Client-9992:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 22:08:45.456] Client-9992:    --- end backtrace ---
Note [2018-04-28 22:08:45.472] Server-11680: Command “Encrypt (needs GnuPG)”
Note [2018-04-28 22:08:45.472] Server-11680:    Exit code: 4
Note [2018-04-28 22:08:45.472] Server-11680:    ERROR: ItemEncrypt ERROR: GnuPG stderr:
Note [2018-04-28 22:08:45.472] Server-11680:    ERROR:    gpg: keyring `C:/Users/Boris/AppData/Roaming/gnupg/secring.gpg' created

Note [2018-04-28 22:08:45.472] Server-11680:    ERROR:    gpg: keyring `C:\\Users\\Boris\\AppData\\Roaming\\copyq\\copyq.pub' created

Note [2018-04-28 22:08:45.472] Server-11680:    ERROR:    gpg: copyq: skipped: No public key

Note [2018-04-28 22:08:45.472] Server-11680:    ERROR:    gpg: [stdin]: encryption failed: No public key

Note [2018-04-28 22:08:45.472] Server-11680:    ERROR:    
Note [2018-04-28 22:08:45.472] Server-11680:    ScriptError: Failed to execute GPG!
Note [2018-04-28 22:08:45.472] Server-11680:    
Note [2018-04-28 22:08:45.472] Server-11680:    --- backtrace ---
Note [2018-04-28 22:08:45.472] Server-11680:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 22:08:45.472] Server-11680:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 22:08:45.472] Server-11680:    --- end backtrace ---
Note [2018-04-28 22:08:45.472] Server-11680:    
Note [2018-04-28 22:08:45.472] Server-11680:    1. copyq:  plugins.itemencrypted.encryptItems()
ERROR [2018-04-28 22:11:03.537] : ItemEncrypt ERROR: GnuPG stderr:
ERROR [2018-04-28 22:11:03.537] :    gpg: copyq: skipped: No public key
ERROR [2018-04-28 22:11:03.537] :    gpg: [stdin]: encryption failed: No public key
ERROR [2018-04-28 22:11:03.537] :    
Note [2018-04-28 22:11:03.553] Client-6132: ScriptError: Exception in command "eval": Failed to execute GPG!
Note [2018-04-28 22:11:03.553] Client-6132:    
Note [2018-04-28 22:11:03.553] Client-6132:    --- backtrace ---
Note [2018-04-28 22:11:03.553] Client-6132:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 22:11:03.553] Client-6132:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 22:11:03.553] Client-6132:    --- end backtrace ---
Note [2018-04-28 22:11:03.569] Server-11680: Command “Encrypt (needs GnuPG)”
Note [2018-04-28 22:11:03.569] Server-11680:    Exit code: 4
Note [2018-04-28 22:11:03.569] Server-11680:    ERROR: ItemEncrypt ERROR: GnuPG stderr:
Note [2018-04-28 22:11:03.569] Server-11680:    ERROR:    gpg: copyq: skipped: No public key

Note [2018-04-28 22:11:03.569] Server-11680:    ERROR:    gpg: [stdin]: encryption failed: No public key

Note [2018-04-28 22:11:03.569] Server-11680:    ERROR:    
Note [2018-04-28 22:11:03.569] Server-11680:    ScriptError: Failed to execute GPG!
Note [2018-04-28 22:11:03.569] Server-11680:    
Note [2018-04-28 22:11:03.569] Server-11680:    --- backtrace ---
Note [2018-04-28 22:11:03.569] Server-11680:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 22:11:03.569] Server-11680:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 22:11:03.569] Server-11680:    --- end backtrace ---
Note [2018-04-28 22:11:03.569] Server-11680:    
Note [2018-04-28 22:11:03.569] Server-11680:    1. copyq:  plugins.itemencrypted.encryptItems()
ERROR [2018-04-28 22:19:21.046] : ItemEncrypt ERROR: GnuPG stderr:
ERROR [2018-04-28 22:19:21.046] :    gpg: copyq: skipped: No public key
ERROR [2018-04-28 22:19:21.046] :    gpg: [stdin]: encryption failed: No public key
ERROR [2018-04-28 22:19:21.046] :    
Note [2018-04-28 22:19:21.061] Client-6864: ScriptError: Exception in command "eval": Failed to execute GPG!
Note [2018-04-28 22:19:21.061] Client-6864:    
Note [2018-04-28 22:19:21.061] Client-6864:    --- backtrace ---
Note [2018-04-28 22:19:21.061] Client-6864:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 22:19:21.061] Client-6864:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 22:19:21.061] Client-6864:    --- end backtrace ---
Note [2018-04-28 22:19:21.077] Server-11680: Command “Encrypt (needs GnuPG)”
Note [2018-04-28 22:19:21.077] Server-11680:    Exit code: 4
Note [2018-04-28 22:19:21.077] Server-11680:    ERROR: ItemEncrypt ERROR: GnuPG stderr:
Note [2018-04-28 22:19:21.077] Server-11680:    ERROR:    gpg: copyq: skipped: No public key

Note [2018-04-28 22:19:21.077] Server-11680:    ERROR:    gpg: [stdin]: encryption failed: No public key

Note [2018-04-28 22:19:21.077] Server-11680:    ERROR:    
Note [2018-04-28 22:19:21.077] Server-11680:    ScriptError: Failed to execute GPG!
Note [2018-04-28 22:19:21.077] Server-11680:    
Note [2018-04-28 22:19:21.077] Server-11680:    --- backtrace ---
Note [2018-04-28 22:19:21.077] Server-11680:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 22:19:21.077] Server-11680:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 22:19:21.077] Server-11680:    --- end backtrace ---
Note [2018-04-28 22:19:21.077] Server-11680:    
Note [2018-04-28 22:19:21.077] Server-11680:    1. copyq:  plugins.itemencrypted.encryptItems()
ERROR [2018-04-28 22:19:36.515] : ItemEncrypt ERROR: GnuPG stderr:
ERROR [2018-04-28 22:19:36.515] :    gpg: copyq: skipped: No public key
ERROR [2018-04-28 22:19:36.515] :    gpg: [stdin]: encryption failed: No public key
ERROR [2018-04-28 22:19:36.515] :    
Note [2018-04-28 22:19:36.515] Client-13336: ScriptError: Exception in command "eval": Failed to execute GPG!
Note [2018-04-28 22:19:36.515] Client-13336:    
Note [2018-04-28 22:19:36.515] Client-13336:    --- backtrace ---
Note [2018-04-28 22:19:36.515] Client-13336:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 22:19:36.515] Client-13336:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 22:19:36.515] Client-13336:    --- end backtrace ---
Note [2018-04-28 22:19:36.530] Server-11680: Command “Encrypt (needs GnuPG)”
Note [2018-04-28 22:19:36.530] Server-11680:    Exit code: 4
Note [2018-04-28 22:19:36.530] Server-11680:    ERROR: ItemEncrypt ERROR: GnuPG stderr:
Note [2018-04-28 22:19:36.530] Server-11680:    ERROR:    gpg: copyq: skipped: No public key

Note [2018-04-28 22:19:36.530] Server-11680:    ERROR:    gpg: [stdin]: encryption failed: No public key

Note [2018-04-28 22:19:36.530] Server-11680:    ERROR:    
Note [2018-04-28 22:19:36.530] Server-11680:    ScriptError: Failed to execute GPG!
Note [2018-04-28 22:19:36.530] Server-11680:    
Note [2018-04-28 22:19:36.530] Server-11680:    --- backtrace ---
Note [2018-04-28 22:19:36.530] Server-11680:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 22:19:36.530] Server-11680:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 22:19:36.530] Server-11680:    --- end backtrace ---
Note [2018-04-28 22:19:36.530] Server-11680:    
Note [2018-04-28 22:19:36.530] Server-11680:    1. copyq:  plugins.itemencrypted.encryptItems()
Note [2018-04-28 22:23:44.234] Server-11680: Command “copyq monitorClipboard”
Note [2018-04-28 22:23:44.234] Server-11680:    Exit code: 1073807364
Note [2018-04-28 22:23:44.234] Server-11680:    1. copyq monitorClipboard
Note [2018-04-28 22:25:50.817] Client-9168: ScriptError: Exception in command "eval": Failed to execute GPG!
Note [2018-04-28 22:25:50.817] Client-9168:    
Note [2018-04-28 22:25:50.817] Client-9168:    --- backtrace ---
Note [2018-04-28 22:25:50.817] Client-9168:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 22:25:50.817] Client-9168:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 22:25:50.817] Client-9168:    --- end backtrace ---
Note [2018-04-28 22:25:50.832] Server-4076: Command “Encrypt (needs GnuPG)”
Note [2018-04-28 22:25:50.832] Server-4076:    Exit code: 4
Note [2018-04-28 22:25:50.832] Server-4076:    ScriptError: Failed to execute GPG!
Note [2018-04-28 22:25:50.832] Server-4076:    
Note [2018-04-28 22:25:50.832] Server-4076:    --- backtrace ---
Note [2018-04-28 22:25:50.832] Server-4076:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 22:25:50.832] Server-4076:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 22:25:50.832] Server-4076:    --- end backtrace ---
Note [2018-04-28 22:25:50.832] Server-4076:    
Note [2018-04-28 22:25:50.832] Server-4076:    1. copyq:  plugins.itemencrypted.encryptItems()
Note [2018-04-28 22:51:58.827] Client-7040: ScriptError: Exception in command "eval": Failed to execute GPG!
Note [2018-04-28 22:51:58.827] Client-7040:    
Note [2018-04-28 22:51:58.827] Client-7040:    --- backtrace ---
Note [2018-04-28 22:51:58.827] Client-7040:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 22:51:58.827] Client-7040:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 22:51:58.827] Client-7040:    --- end backtrace ---
Note [2018-04-28 22:51:58.843] Server-6220: Command “Encrypt (needs GnuPG)”
Note [2018-04-28 22:51:58.843] Server-6220:    Exit code: 4
Note [2018-04-28 22:51:58.843] Server-6220:    ScriptError: Failed to execute GPG!
Note [2018-04-28 22:51:58.843] Server-6220:    
Note [2018-04-28 22:51:58.843] Server-6220:    --- backtrace ---
Note [2018-04-28 22:51:58.843] Server-6220:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2018-04-28 22:51:58.843] Server-6220:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2018-04-28 22:51:58.843] Server-6220:    --- end backtrace ---
Note [2018-04-28 22:51:58.843] Server-6220:    
Note [2018-04-28 22:51:58.843] Server-6220:    1. copyq:  plugins.itemencrypted.encryptItems()
Hope this can help
Boris

**Comment by hluk** [comment] 2018-05-01 10:28
This is duplicate of #823.

Gpg4win (3.0.0 and newer) stopped providing `gpg` utility needed by CopyQ.

As workaround, instead of the classic Gpg4win you can install [gpg4win-vanilla](https://chocolatey.org/packages/gpg4win-vanilla) or older Gpg4win (2.3.3). I've just fixed this in [the documentation](http://copyq.readthedocs.io/en/latest/password-protection.html).

Some additional fixes are required in new version of CopyQ. You can install the fixed version from [here](https://ci.appveyor.com/project/hluk/copyq/build/job/70w382ytw1xmbv0g/artifacts).

**Closed by hluk** 2018-05-01 10:28 UTC
