### ISSUE TITLE
copyQ font size suddenly tiny (UI and History list items) UBUNTU 20.04.4

### ISSUE THREAD

**Issue by sfd99** [hluk/CopyQ#1487] opened 2020-09-28 10:35 UTC
quote from HeRo002 
_" > I just installed Ubuntu 20.04 on a new partition, then I installed CopyQ v3.10.0 . Then suddenly the font size seemed VERY small. I am not 100% sure if it had actually changed, but I think so. So in Preferences under Appearance I started pressing the 'Abc'-buttons and changing the font size, but my changes were ignored by CopyQ, whether I checked: Set colors for tabs, tool bar and menus or not."_

THIS IS EXACTLY my Problem w/ latest CopyQ also,
under **UBUNTU 20.04.4**...
Installed  copyQ 5 days ago from [Ubuntu Software]. 
Great app. No problems.

_Suddenly_,
all the font sizes 
(CopyQ UI menus and History copied items f/clipboard),
have become **tiny**. 
Almost unreadable...
(I did not change any setting before this).

Just like the above User,
I tried increasing the Font Sizes
in the **[abc]** buttons under **Appearance**.

But none of my new (larger) font sizes "takes".
_ie:_
as soon as I click [OK] 
and then [Apply],
my font size size settings are forgotten
and the old, original tiny font sizes reappear...
Nothing changes.

I think CopyQ is a WONDERFUL program.
But isn't there a _simple_ way to set the font sizes
of the UI and the History list of copied items?.

Checked the Manual
and the Q&As, 
but no solutions work for me.

_HELP!_ 
Can't increase the font sizes,
they are too small to read... :-(
How do I easily fix this font size problem?.

_thanks!_

**SFd99
SF
Ubuntu Linux 20.04.4
latest Chromium browser**

**Comment by hluk** [comment] 2020-09-29 16:28
Can you share output of `copyq version` command?

I'm probably going to close this in favour of #1489 (looks like same issue).

**Comment by sfd99** [comment] 2020-09-30 00:05
_Hi Lukas!._

here's the requested  info:

*ray@ray-XPS-8930:~$ copyq version 
CopyQ Clipboard Manager v3.10.0
Qt: 5.12.5
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 20.04.1 LTS
---

I d/l and installed copyQ 
directly from
the official "**Ubuntu Software Center**"...

**Comment by hluk** [comment] 2020-09-30 13:32
OK, thanks. Let me close this as duplicate of #1489 ... even though this one was first :) ... Please, see the comments there.

**Closed by hluk** 2020-09-30 13:32 UTC
Labels: bug
