### ISSUE TITLE
invisible character added at the front

### ISSUE THREAD

**Issue by omin** [hluk/CopyQ#681] opened 2017-03-29 10:07 UTC
It seems like when I use CopyQ to copy/paste, there is an invisible character that's added at the front of the string. Try pasting something from CopyQ to Photoshop multiple times.

eg. When I paste "a" 3 times, I need to hit backspace 5 times to delete all "a"s.

OS X 10.11.6
CopyQ v2.9.0

**Comment by hluk** [comment] 2017-04-01 11:46
I think this is issue with trailing null character in copied text -- some apps do this. Most apps seem to ignore it when pasting text -- out of the apps I've tested only Chromium doesn't ignore the character.

Does this happen even if you create and copy new item in CopyQ?

**Comment by omin** [comment] 2017-04-01 18:56
Yes it does happen when I create and copy new items in CopyQ. It doesn't happen with system default copy/paste so I think there's definitely an issue we should fix.

**Comment by hluk** [comment] 2017-04-02 05:15
So you paste item by selecting it from menu or main window, not with Ctrl+V or Shift+Insert?

**Comment by omin** [comment] 2017-04-02 05:55
Happens on both. Just tried using Paste as Plain Text from the menu.

**Comment by hluk** [comment] 2017-04-02 06:33
So this doesn't happen with Command+V? That would mean that the command to paste the text generates the invisible characters -- it tries to [send Command+V](https://github.com/hluk/CopyQ/blob/d27fe7b438c49fe07bf472f0e99a168ddc3f86a9/src/platform/mac/macplatformwindow.mm#L41) to target window.

The code for sending the shortcut [differs a bit in FlyCut](https://github.com/TermiT/Flycut/blob/717496b77817d8bd7bacfc7702f2668936d83975/AppController.m#L709). Perhaps our code doesn't handle keyboard layouts well.

**Comment by omin** [comment] 2017-04-02 06:36
It does happen with Command + V. Btw it doesn't happen with FlyCut and that's the only reason I'm currently using FlyCut for my use case (need to copy multiple values for dimensions in designs).

**Comment by hluk** [comment] 2017-04-02 07:06
Can you check if the item "a" is just 1 byte long? You can do this by selecting the item, opening Item Content dialog with <kbd>F4</kbd> shortcut and selecting "text/plain" from the list (the label under item content should read "**Size:** 1 bytes").

**Comment by omin** [comment] 2017-04-02 07:14
Yes, it is 1 byte.

**Comment by hluk** [comment] 2017-04-02 07:50
Also check clipboard content after copying the item -- it's in menu "File - Show Clipboard Content" (though this information may not be very accurate since it goes through Qt library).

BTW, thanks for quick replies!

**Comment by omin** [comment] 2017-04-02 08:22
np!
![image](https://cloud.githubusercontent.com/assets/3143154/24585564/d17f5aee-1742-11e7-8a2e-ed10e2ad9496.png)

**Comment by hluk** [comment] 2017-04-02 08:23
And size of the "text/plain"?

**Comment by omin** [comment] 2017-04-02 08:24
I was just adding that to the comment above. It's still 1 byte.

**Comment by hluk** [comment] 2017-04-02 08:30
OK, thanks. Hmm, the "text/plain" format can still contain some additional characters -- it's just not shown in the dialog since it's retrieved using Qt library.

I'll try to test this locally if possible (need to get my hands on OS X first).

**Comment by hluk** [comment] 2017-04-02 12:25
I cannot test it in Photoshop and in other apps it seems to work fine. Is this problem in any other app that is installed by default?

**Comment by hluk** [comment] 2017-04-06 06:27
Can you test it with [new version](https://github.com/hluk/CopyQ/releases)? (BTW, I also update installation [instructions](https://github.com/hluk/CopyQ#os-x).)

**Comment by omin** [comment] 2017-04-07 05:11
It still happens on v3.0.0
![image](https://cloud.githubusercontent.com/assets/3143154/24786377/e750b7ec-1b15-11e7-9fe8-598062f55ad6.png)

**Comment by hluk** [comment] 2017-04-07 06:19
I cannot reproduce it on OS X 10.11.6 with any apps and unfortunately I cannot test it in Photoshop.

What system language and keyboard layout do you use? What is does `locale` print in terminal?

**Comment by omin** [comment] 2017-04-07 07:28
```$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

**Comment by omin** [comment] 2017-04-07 07:54
![image](https://cloud.githubusercontent.com/assets/3143154/24790840/bb547748-1b2c-11e7-9095-4a57c61b9c82.png)

**Comment by hluk** [comment] 2017-04-07 07:55
The only suspicious thing is that "text/html" (probably converted from "text/rtf") is copied from TextEdit. When copying text back line break is added. This could be it (line entry may not show the line break character). Though clipboard content dialog should list "text/html" which is not true in your case.

**Comment by TomJahncke** [comment] 2017-05-22 19:06
I am having the same issue.  MacOs v. 10.12.5.  CopyQ 3.0.1 (had the same issue with 3.0.0 and 2.x)

I can reproduce with applications like Intellij 

Any assistance / workarounds would be very appreciated.

**Comment by hluk** [comment] 2017-05-24 06:47
OK, I can reproduce it with InterlliJ.

The inserted character seems to be BOM for UTF character encoding.

Trying to fix it...

**Comment by hluk** [comment] 2017-05-24 09:53
It should be finally fixed in [pre-release](https://github.com/hluk/CopyQ/releases/tag/osx-test).

**Comment by TomJahncke** [comment] 2017-05-24 14:52
Hi Lukas,

Thank you for working on this and replying ... I installed the pre-release
and now the functional to copy to the clipboard is not working at all on my
Mac.

FYI, the Help menu only says version 3.0.1.  Is there a way to tell that I
have installed the pre-release version?

Here is the error I see when I put an entry into my clipboard (I get the
same error in Intellij, ATOM and Chrome).

[image: Inline image 1]

**Closed** 2017-05-30 07:13 UTC
Labels: bug, OSX

**Comment by TomJahncke** [comment] 2017-05-30 11:17
I upgraded to 3.0.2, the issue has been resolved!  Thank you!
