### ISSUE TITLE
MacOS tray shortcut opens main window

### ISSUE THREAD

**Issue by Engazan** [hluk/CopyQ#1543] opened 2020-12-21 18:26 UTC
**Describe the bug**
Tray menu shortcut will show Main Menu ( 

**To Reproduce**
Main menu Shortcut - CONTROL SHIFT W
Tray menu Shortcut - CONTROL SHIFT I
1. show tray menu (shortcut)

**Expected behavior**
it should open just tray like on windows version 

**Version, OS and Environment**
 - Application Version [3.13]
 - MacOS 11.1

**Comment by hluk** [comment] 2020-12-22 09:18
Duplicate of #1533.

**Closed by hluk** 2020-12-22 09:18 UTC
Labels: bug
