### ISSUE TITLE
CopyQ 8.0.0 still does not copy images from Firefox

### ISSUE THREAD

**Issue by iG8R** [hluk/CopyQ#2635] opened 2024-03-14 16:58 UTC
**Describe the bug**
CopyQ 8.0.0 still does not copy images from Firefox.
Log:
```
Warning [2024-03-14 18:25:08.768] <monitorClipboard-24660>: [qt.qpa.mime] QtWarning: Retrying to obtain clipboard. <--- copying an image in Firefox
Note [2024-03-14 18:25:14.659] <Server-3800>: Fetching icon and title: https://static-cdn.jtvnw.net/ttv-boxart/496902_IGDB-285x380.jpg <--- copying an image in Chrome
Note [2024-03-14 18:25:14.665] <Server-3800>: Fetching: https://static-cdn.jtvnw.net/ttv-boxart/496902_IGDB-285x380.jpg
```

**To Reproduce**
1. Try to "Copy mage" on any page in Firefox

**Expected behavior**
Images, not blank placeholders, should be stored in CopyQ.

**Screenshots**
![image](https://github.com/hluk/CopyQ/assets/11407417/396d340d-0871-4d14-8fdd-80be1042b957)

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - CopyQ 8.0.0
 - Microsoft Windows [Version 10.0.19045.2673]
 - Firefox 123.0.1 (64-bit)
 - Chrome 122.0.6261.129 (Official Build) (64-bit)

**Comment by hluk** [comment] 2024-03-24 05:44
Duplicate of #2084.

**Closed by hluk** 2024-03-24 05:44 UTC
Labels: bug
