### ISSUE TITLE
Paste items by its row number

### ISSUE THREAD

**Issue by DRYN07** [hluk/CopyQ#2405] opened 2023-07-21 07:36 UTC
It is possible that it is just a shortcut conflict but is there a way to instantly paste content by its row number? I opened the clipboard window and tried to press 1 / CTRL+1 / ALT+1, etc but did not find a way to paste items. A lot of time I want to insert 1-3 row's content but I don't want always to open and click on them.

Oh and I did not find any shortcuts for this.

Is there any way to do this?

**Comment by hluk** [comment] 2023-07-22 12:02
Duplicate of #2388.

**Closed by hluk** 2023-07-22 12:02 UTC
Labels: feature
