### ISSUE TITLE
Frequent crash when "copy on select" is enabled.

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#555] opened 2016-10-12 11:53 UTC
I've enabled `Store text selected using mouse`. Using gvim to select a bunch of text frequently crashes copyq with the error msg : 
```
Command “copyq: if (monitoring()) {updateTitle('')}”
Error: Process crashed

---
copyq:  if (monitoring()) {updateTitle('')}
---
```

Archlinux
i3wm
CopyQ Clipboard Manager v2.7.1-34-g7ef153f (hluk@email.cz)
Built with: Qt 5.7.0, LibQxt 0.7.0

**Comment by hluk** [comment] 2016-10-12 16:17
Duplicate of #424 (seems to be some issue in Qt).

**Closed by hluk** 2016-10-12 16:17 UTC
