### ISSUE TITLE
[Question] How to disable 0 in the number list?

### ISSUE THREAD

**Issue by fosam** [hluk/CopyQ#1617] opened 2021-04-08 15:33 UTC
- When having multipe lines in CopyQ, the number list always starts with a zero, this can be confusing.

- **Screenshot:**

![Capture 08_04_2021_17_12_10](https://user-images.githubusercontent.com/52612348/114053183-01a0e900-988f-11eb-8559-6ffccd02717d.png)

- As you can see in the screenshot above, there are 10 lines but the numbers on the left state that there are 9, this is because of the 0 that is beig added at the start.

- How to disable this and make the list start with 1 instead of zero? if this is not possible then please give us an option to disable it.

**Comment by hluk** [comment] 2021-04-11 05:11
Duplicate of #1085. There is relatively a lot of requests for this so I'm going to make it a default for the next release.

**Closed by hluk** 2021-04-11 05:11 UTC
Labels: feature

**Comment by fosam** [comment] 2021-04-11 17:32
@hluk Thank you!

Best if it would be possible to toggle this in the preferences so that users who would like to use 0 as default will also have the opportunity for that.

**Comment by hluk** [comment] 2021-04-11 17:45
> Best if it would be possible to toggle this in the preferences so that users who would like to use 0 as default will also have the opportunity for that.

Yeah, if people start asking about this, but plan for now is to keep the option hidden (`copyq config row_index_from_one false`) and possibly remove it in the future (to clean up some code).

**Comment by fosam** [comment] 2021-04-11 18:25
Fix in v4.0.0 confirmed.

I think it would be better to have a way to switch between 0 and 1, because there are uses when one needs to use 0 and 1.

I actually never needed to start with one until i asked about it here, i will definitely need to switch to 0 when i'll work again with the files that are best suitable to have them started with 0 like some code or similar.

But for now let's be happy that we have a hidden option to switch from :)

Keep in mind that CopyQ is the best clipboard manager out there.
