### ISSUE TITLE
Merging multiple copied items into a single one works but out of order

### ISSUE THREAD

**Issue by marioawad** [hluk/CopyQ#2216] opened 2023-01-02 12:42 UTC
Hello,

Thanks for the great application. Been using it on Windows and now on Linux. Simply amazing!

One tiny bug I noticed in the recent versions please. Say for example you copy the below items one after the other.

1
2
3
4
5

Then you go into CopyQ and you select them all and you copy again or just press Enter, it merges them into a single one properly but the order is not always right.

If you select them from top to bottom then the order will be correct:
5
4
3
2
1

If you select them from bottom to top then the order will be incorrect (Expected to be 1,2,3,4,5 as in previous versions of CopyQ):
1
5
4
3
2

Unfortunately the second use case is the more common and useful one. Say you're copying multiple links one after the other for research then you want to have them pasted in the order you have copied them.

Hope you have the time to look into it and thanks again for the amazing work you do.

Thank you.

Version, OS and Environment:
CopyQ Clipboard Manager 6.3.2~focal
Qt: 5.12.8
KNotifications: 5.68.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: KDE neon User - 5.26

**Comment by hluk** [comment] 2023-01-11 07:19
> If you select them from top to bottom then the order will be correct:
> 5
> 4
> 3
> 2
> 1

Do you mean "from bottom to top" (i.e. selecting 5 first then the rest)?

This is broken if making the selection with mouse. Internally, it seems that the Qt framework keeps the initially selected item at first position in the selection list but adds the rest of the items in order they appear.

**Comment by hluk** [comment] 2023-01-12 07:39
Ah, I think I understand the issue now (I was confused by the numbering).

With keyboard this is expected behavior: The items are **copied/merged in the same order they were selected**. This should also work if you select multiple items with Shift - for example Shift+Home would select the items starting from the current row.

With mouse this is not handled in any special way currently. This is not a Qt bug but rather a specific CopyQ behavior.

**Comment by hluk** [comment] 2023-01-13 14:42
I could not reproduce this. Can you provide steps with specific keys and modifiers to press?

**Closed** 2023-01-16 15:15 UTC
Labels: bug
