### ISSUE TITLE
copyq 2.4.9 doesn't open (os x)

### ISSUE THREAD

**Issue by andredasilvapinto** [hluk/CopyQ#393] opened 2015-10-05 18:07 UTC
```
> open CopyQ.app
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/CopyQ.app.
```

OS X 10.10.5

**Comment by andredasilvapinto** [comment] 2015-10-05 18:12
2.4.8 works

**Comment by nirmalksamuel** [comment] 2015-10-08 14:35
Thanks for the comment.  Downloaded 2.4.8 for OS X for fresh copy just now.  Rebooted my machine to be sure. Installed 2.4.8.  This has same problem i described elsewhere - does not open, nothing is shown  in macbook Dock or at top.  Tried to start it from Terminal using command line CopyQ. It can not find the application anywhere.  Is there any version of this that has been tested to work on OS X ? (Will add this comment to the other bug report, if i can find it)

**Comment by nirmalksamuel** [comment] 2015-10-08 15:21
Please re-open the closed issue "Problem installing/running dmg file on OS X #389" - it is related and has more details on this issue.

**Comment by andredasilvapinto** [comment] 2015-10-08 16:49
Well, 2.4.8 definitely works on *my* OS X. You probably have a different problem.

**Comment by xpnoiboix** [comment] 2015-10-08 19:37
2.4.9 os x yosemite here does not open either, it does nothing when i try to open the app, will try 2.4.8 now

**Comment by nirmalksamuel** [comment] 2015-10-10 12:08
xpnoiboix,   Have you tried  2.4.8  yet ? It would be nice to get more tests/feedbacks  because  my  OS X mavericks is brand new installation (at apple store)  and it does not have much further installations on it yet.   I am using it as a home machine for mostly web surfing,  not as my development machine.  So, I was under the impression that it is unlikely  that something else is going on in this macbook mavericks.  During my testing, copyQ 2.4.8 shows very similar bug like  2.4.9.  We need more than 2 people testing & reporting, to get attention of developers on this product.

**Comment by vchethan** [comment] 2015-10-16 05:45
I have tried 2.4.8 and 2.4.9 version on my mac (Version: 10.10.4) and faced the same issue.

**Comment by nirmalksamuel** [comment] 2015-10-17 20:54
OK - that confirms my original report on 2 broken releases. Perhaps andredasilvapinto has an older installation of 2.4.8 on OS X which may continue to work still.  I am tempted to install the 2.4.7 now, but I think i will hold out - it will make me check these pages for update, in case they need a tester for confirmation.  Once i install 2.4.7, i know i will ignore this page among my other obligations.

**Comment by rygwdn** [comment] 2015-10-18 16:20
This is a common issue on newer OSX when launching from a terminal/process with the wrong permissions - usually tmux. Does it happen when using `open` to open other programs? Try using `reattach-to-user-namespace` as described in https://github.com/atom/atom/issues/3093

**Comment by nirmalksamuel** [comment] 2015-10-21 00:25
The original bug report  `>open  /Applications/CopyQ.app`   works for me, with download done just now.  But, i am on OS X 10.9.5, so someone with latest release can confirm this.  Pardon me reproducing the message below from another thread, but the other thread is closed and no one may notice it there.....

I downloaded from the 2.4.9 release link given by hluk. It is showing the icon as well as opens now. I am new to copyQ, so can not test functionality, but initial look at preferences shows i will come to like this software. Now....if only i can find a documentation to quickly introduce me to various aspects of this, i will be able to navigate the preferences faster. Quick google search does not yield anything for documentation. I am sure there is one lurking around. Can you point me to it ? Thanks to the entire dev team of this work.

**Comment by hluk** [comment] 2015-10-21 08:29
@nirmalksamuel See [response about docs](https://github.com/hluk/CopyQ/issues/389#issuecomment-149810125).

**Comment by andredasilvapinto** [comment] 2015-11-12 20:56
@nirmalksamuel 
```
$ md5 CopyQ-2.4.8.dmg 
MD5 (CopyQ-2.4.8.dmg) = 9dce9d438a64909e96b273f500a54ab6
```

**Comment by nirmalksamuel** [comment] 2015-11-13 04:31
What is the md5 for 2.4.9 ?  Here is what i get ....
$ md5 CopyQ-2.4.9.dmg 
MD5 (CopyQ-2.4.9.dmg) = 45f7c99fae7badd77aa50e72a8b101ae
But i have conflicting md5 value ( 98be4c2ffd63617f5f3b06c53445cff0 ) given at a site that came up as a hit when i did search google for md5 copy 2.4.9.

**Comment by rygwdn** [comment] 2015-11-14 14:34
I think this can be closed now, https://github.com/hluk/CopyQ/issues/386 is fixed, and the original report (can't use `open CopyQ.app`) isn't a bug with CopyQ and can be worked around with `reattach-to-user-namespace`

**Comment by hluk** [comment] 2015-11-14 14:58
Thanks Ryan. Closing issue.

**Closed by hluk** 2015-11-14 14:58 UTC
