### ISSUE TITLE
Error While Copying

### ISSUE THREAD

**Issue by anshumangoyal** [hluk/CopyQ#611] opened 2016-12-27 07:31 UTC
This is very common problem that I am getting.

On Windows 10, when i press key to show the clipboard window, I get this message as error most of the time. Is there any special setting that has to be done for Windows 10? Why does it fails to set the clipboard? Cannot configure the same.

Command “copyq: var text = clipboa…pySelection(text) paste()”
Exit code: 1
CopyQ ERROR [2016-12-27 12:54:13.681]: Error: Failed to set clipboard! 
CopyQ ERROR [2016-12-27 12:54:13.681]:     
CopyQ ERROR [2016-12-27 12:54:13.681]:    --- backtrace --- 
CopyQ ERROR [2016-12-27 12:54:13.681]:    <eval>() at 3 
CopyQ ERROR [2016-12-27 12:54:13.681]:    eval([object Object]) at -1 
CopyQ ERROR [2016-12-27 12:54:13.681]:    <global>() at -1 
CopyQ ERROR [2016-12-27 12:54:13.681]:    --- end backtrace --- 

---
copyq:  
var text = clipboard()
copy(text)
copySelection(text)
paste()
---

**Comment by hluk** [comment] 2016-12-29 09:53
Closing as duplicate of #604 (need to rename the issue).

**Closed by hluk** 2016-12-29 09:53 UTC
