### ISSUE TITLE
mate-panel will restart with copyq

### ISSUE THREAD

**Issue by jing2uo** [hluk/CopyQ#1201] opened 2019-08-22 02:50 UTC
**Describe the bug**

mate-applet-appmenu can provide global menu on mate-panel, but when I open copyq, mate-panel will restart very often.  copyq will lost focus, I cant select any item (

**To Reproduce**
1. add mate-applet-appmenu to mate-panel 
2. open copyq 
3. select any item

**Expected behavior**
copyq work normal with appmenu 

**Screenshots**

The screenshot is not convenient to see the problem, I recorded this video...

[2019-08-22 10-44-29.flv.zip](https://github.com/hluk/CopyQ/files/3528075/2019-08-22.10-44-29.flv.zip)

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - CopyQ Clipboard Manager v3.9.1
 - Qt: 5.11.3
 - Compiler: GCC
 - Arch: x86_64-little_endian-lp64
 - OS: Debian GNU/Linux bullseye/sid
 - Desktop environment: mate-desktop 1.22.1 
                                       mate-applet-appmenu 0.7.3+dfsg1-1

**Additional context**
copyq and mate-panel work fine when appmenu-applet was deleted.

there is some log in ~/.xsession-errors :

https://gist.github.com/jing2uo/73717ae774f0bf08e1e9eb8e26f88524

**Comment by hluk** [comment] 2019-08-22 13:30
> 1. add mate-applet-appmenu to mate-panel
> 2. open copyq

What's mate-applet-appmenu? Can you explain in more details how to reproduce this?

I see tray icon in the panel but don't experience any issues when opening menu or main window.

This is probably an issue in Mate tray icon/menu integration (or in Qt framework).

**Comment by jing2uo** [comment] 2019-08-23 02:35
mate-applet-appment will provide global menu,  like os x ,all applications's menu will display on the top panel. 
repo:  https://github.com/rilian-la-te/vala-panel-appmenu

if you have debian+mate environment, this is the steps  to reproduce :  
1 .apt install mate-applet-appmenu appmenu-qt appmenu-gtk2-module appmenu-gtk3-module appmenu-gtk-module-common 
2. right click on the mate-panel, add to panel .... select global menu
3. open copyq ,you will find the menu is on mate-panel, not copyq's main window, looks like this:
![image](https://user-images.githubusercontent.com/3081432/63562638-ea659880-c590-11e9-9725-b5f57a3d4f07.png)
4. when select any item in copyq , mate-panel will restart very often.  tray icon is ok, but whole mate-panel will open-close-open-close …

I am sorry that my English is not good. CopyQ is awesome and greatly helped me, thanks for you work !

**Comment by jing2uo** [comment] 2019-08-23 02:43
Other QT5 applications works normal , like Virtualbox goldendict vlc zeal ...

**Comment by hluk** [comment] 2019-08-23 08:37
Thanks for detailed description.

I cannot reproduce this on Ubuntu 18.04 -- most probably different component versions and theming.

![image](https://user-images.githubusercontent.com/38054/63579029-0158ba80-c592-11e9-8464-6401b8e7d278.png)

What do you see in the context menu (when you right click a clipboard item in CopyQ)? The Item menu contains basically the same entries.

I am inclined to close this issue since it's problem with some other component related to appmenu.

**Comment by hluk** [comment] 2019-08-23 08:42
Oh, never mind, I can reproduce the crashes occasionally, I'll try to investigate further.

**Comment by hluk** [comment] 2019-08-23 09:53
Looks like `/usr/lib/mate-panel/appmenu-mate` crashes when the menus contain separators (maybe at some point when these are being removed).

Not sure what to do with this - looks like this needs to be fixed elsewhere.

**Comment by jing2uo** [comment] 2019-08-23 10:05
Can the log  in ~/.xsession-errors provide some help? 

https://gist.github.com/jing2uo/73717ae774f0bf08e1e9eb8e26f88524

**Comment by hluk** [comment] 2019-08-23 11:00
> Can the log in ~/.xsession-errors provide some help?

Nope. As I mentioned the workaround would be to remove separators in menus which would make the menus less clear.

You better report the bug for [vala-panel-appmenu](https://gitlab.com/vala-panel-project/vala-panel-appmenu/issues).

**Comment by jing2uo** [comment] 2019-08-23 12:43
![image](https://user-images.githubusercontent.com/3081432/63593380-735aef00-c5e6-11e9-8965-92629b0c763e.png)
Is this the separator you said?

**Comment by hluk** [comment] 2019-08-23 13:05
> Is this the separator you said?

Yes. If I remove it from menu [1] everything seems to work.

[1] I.e. remove all [addSeparator() calls](https://github.com/hluk/CopyQ/blob/9ec64d9251482b9a3a4011a13413f97de24b176c/src/gui/mainwindow.cpp#L783).

**Comment by jing2uo** [comment] 2019-08-23 13:23
I check the menu of chromium / goldendict / caja, these apps also have the separators..

**Comment by hluk** [comment] 2019-08-23 14:56
Yeah, I noticed that also Qt Creator has also menus with separators. Perhaps the important difference is that in CopyQ the Item menu is dynamic so sometimes (e.g. selecting other clipboard item or tab) the menu is cleared and the menu entries with separators are created again.

**Comment by hluk** [comment] 2019-08-23 15:05
Seems like there is some data race in the appmenu (it's constructing the menu while CopyQ is updating it).

**Comment by jing2uo** [comment] 2019-08-27 05:03
So, should I submit a bug to appmenu ? or,  you will fix this .  🏵️

**Comment by hluk** [comment] 2019-08-27 06:53
> So, should I submit a bug to appmenu ? or, you will fix this .

If you can, please submit bug report for appmenu. I really have no idea how to fix this in CopyQ, unless I just remove all menu separators (and that's not a good idea).

**Closed by hluk** 2019-08-27 06:53 UTC
Labels: bug

**Comment by hmnd** [comment] 2020-04-19 08:27
@jing2uo Did you end up creating a bug report for appmenu perhaps? If so, could you link it please? I appear to be experiencing the same issue now with budgie-panel.

**Comment by pa-0** [comment] 2024-08-21 19:40
FYI looks like this was fixed in the vala-panel source: [Vala-Panel Commits](https://gitlab.com/vala-panel-project/vala-panel-appmenu/-/commit/1250eeac2ecb2a3f1121d7ccf3624bf7ced8c133)
