### ISSUE TITLE
Cannot paste multiple images 

### ISSUE THREAD

**Issue by waseemv** [hluk/CopyQ#2490] opened 2023-09-21 14:04 UTC
**Describe the bug**
Not able to copy and paste multiple images.
This works fine for text items

**To Reproduce**
Select more than one image
Press Ctrl+C, then, Ctrl+V

**Expected behavior**
Should paste the selected images
This is what happens if the items are text.

**Screenshots**

**Version, OS and Environment**
CopyQ 7.1.0
Windows 11

**Additional context**
(I tested this with another Clipboard manager, Ditto. It has an option called "Paste Special", if I select that, then hit Ctrl+V, it pastes all the images in one go.)

**Comment by hluk** [comment] 2023-09-26 11:40
Not a bug. This was never supported. Also it looks like a duplicate of #2490.

**Closed by hluk** 2023-09-26 11:40 UTC
