### ISSUE TITLE
Fedora 32 cannot open neither by terminal or GUI shortcut

### ISSUE THREAD

**Issue by MintYale** [hluk/CopyQ#1510] opened 2020-11-04 10:02 UTC
**Describe the bug**
As the title said. Cannot open/use copyq neither by terminal or GUI shortcut on fedora 32. Searched the known issues only to find there seems no same issue reported yet nor solutions,or maybe I missed it, if someone tell me the issue No. I would appreciate it. 

**To Reproduce & Version, OS and Environment**
```
[mint@LAPTOP-CO6J92OR ~]$ neofetch
          /:-------------:\          mint@LAPTOP-CO6J92OR.lan 
       :-------------------::        ------------------------ 
     :-----------/shhOHbmp---:\      OS: Fedora 32 (Workstation Edition) x86_64 
   /-----------omMMMNNNMMD  ---:     Host: 20UF0008CD ThinkPad X13 Gen 1 
  :-----------sMMMMNMNMP.    ---:    Kernel: 5.8.17-200.fc32.x86_64 
 :-----------:MMMdP-------    ---\   Uptime: 6 hours, 35 mins 
,------------:MMMd--------    ---:   Packages: 3298 (rpm), 8 (flatpak) 
:------------:MMMd-------    .---:   Shell: bash 5.0.17 
:----    oNMMMMMMMMMNho     .----:   Resolution: 1920x1080 
:--     .+shhhMMMmhhy++   .------/   DE: GNOME 3.36.7 
:-    -------:MMMd--------------:    WM: Mutter 
:-   --------/MMMd-------------;     WM Theme: Jade-1 
:-    ------/hMMMy------------:      Theme: Jade-1 [GTK2/3] 
:-- :dMNdhhdNMMNo------------;       Icons: Fedora [GTK2/3] 
:---:sdNMMMMNds:------------:        Terminal: gnome-terminal 
:------:://:-------------::          CPU: AMD Ryzen 5 PRO 4650U with Radeon Graphics (12) @ 2.100GHz 
:---------------------://            GPU: AMD ATI 07:00.0 Renoir 
                                     Memory: 4677MiB / 15285MiB 

[mint@LAPTOP-CO6J92OR ~]$ copyq --version
CopyQ Clipboard Manager v3.13.0
Qt: 5.14.2
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Fedora 32 (Workstation Edition)

[mint@LAPTOP-CO6J92OR ~]$ copyq

(copyq:13711): Gtk-WARNING **: 17:51:25.565: Theme parsing error: colors.css:71:44: Invalid number for color value

(copyq:13711): Gtk-WARNING **: 17:51:25.565: Theme parsing error: colors.css:72:44: Invalid number for color value

(copyq:13711): Gtk-WARNING **: 17:51:25.565: Theme parsing error: colors.css:74:53: Invalid number for color value

(copyq:13711): Gtk-WARNING **: 17:51:25.565: Theme parsing error: colors.css:75:53: Invalid number for color value

(copyq:13711): Gtk-WARNING **: 17:51:25.565: Theme parsing error: colors.css:76:56: Invalid number for color value

(copyq:13711): Gtk-WARNING **: 17:51:25.565: Theme parsing error: colors.css:77:65: Invalid number for color value

(copyq:13711): Gtk-WARNING **: 17:51:25.568: Theme parsing error: gtk.css:1891:0: Expected a valid selector
Segmentation fault (core dumped)
```

**Comment by hluk** [comment] 2020-11-08 06:25
This looks like a problem with a platform theme similar to #1401. Nothing much I can do about it.

You can try overriding the theme with:

```
env QT_QPA_PLATFORMTHEME="" copyq
```

**Comment by TnS-hun** [comment] 2020-11-08 21:00
It works fine with that override. Thank you.

**Comment by hluk** [comment] 2020-11-09 06:26
I'm closing this because it's a bug outside of the application. Try updating the theme installed on your system or using a different one.

**Closed by hluk** 2020-11-09 06:26 UTC

**Comment by MintYale** [comment] 2020-11-09 16:05
> I'm closing this because it's a bug outside of the application. Try updating the theme installed on your system or using a different one.

OK. I tried `env QT_QPA_PLATFORMTHEME="" copyq` as you suggested,  somehow it did't work. (But thanks all the same~)
I google about this and find that maybe there is something wrong this these two files: ~/.config/gtk-3.0/colors.css   ~/.config/gtk-3.0/gtk.css 

In the colors.css the rgb() of line 71,72,74~77  has no parameters , so I add some:
```
...
70 @define-color content_view_bg #fcfcfc;
71 @define-color theme_titlebar_background rgb(71,80,87);
72 @define-color theme_titlebar_foreground rgb(252,252,252);
73 @define-color theme_titlebar_background_light #eff0f1;
74 @define-color theme_titlebar_foreground_backdrop rgb(189,195,199);
75 @define-color theme_titlebar_background_backdrop rgb(239,240,241);
76 @define-color theme_titlebar_foreground_insensitive rgb(189,195,199);
77 @define-color theme_titlebar_foreground_insensitive_backdrop rgb(189,195,199);
```

Now I run `copyq` or `env QT_QPA_PLATFORMTHEME="" copyq` , there is still one error-message left( As following quote. Before adding the rgb() parameters there were more) . Sadly this one I can't handle it... I am a web developer and like Linux a lot yet almost new to Linux...I don't use Linux back then so I am not familiar with this. I wonder if someone happens to know this can  
kindly show me how to solve this OR this is a old bug that should be reported to Linux-GTK-dev-team?
```
[mint@localhost gtk-3.0]$ copyq

(copyq:28357): Gtk-WARNING **: 23:44:35.075: Theme parsing error: gtk.css:1891:0: Expected a valid selector
Segmentation fault (core dumped)
[mint@localhost gtk-3.0]$ env QT_QPA_PLATFORMTHEME="" copyq

(copyq:28469): Gtk-WARNING **: 23:45:03.975: Theme parsing error: gtk.css:1891:0: Expected a valid selector
Segmentation fault (core dumped)
[mint@localhost gtk-3.0]$
```
By the way, run `emacs` shows the same error-message, but it can start and works well.
```
[mint@localhost gtk-3.0]$ emacs

(emacs:28703): Gtk-WARNING **: 23:57:54.587: Theme parsing error: gtk.css:1891:0: Expected a valid selector
[mint@localhost gtk-3.0]$ 
```

**Comment by hluk** [comment] 2020-11-09 18:03
AFAIK emacs is not an application using Qt framework. This is likely a bug somewhere in a layer that allows Qt apps to use Gtk theme.

Try installing `qt5ct`, select different theme using `qt5ct` utility and start CopyQ with `env QT_QPA_PLATFORMTHEME=qt5ct copyq`.

Also, if possible, provide output of `coredumpctl dump copyq` -- to see where the app crashed -- maybe the issue is really elsewhere.

**Comment by MintYale** [comment] 2020-11-11 18:16
> AFAIK emacs is not an application using Qt framework. This is likely a bug somewhere in a layer that allows Qt apps to use Gtk theme.
> 
> Try installing `qt5ct`, select different theme using `qt5ct` utility and start CopyQ with `env QT_QPA_PLATFORMTHEME=qt5ct copyq`.
> 
> Also, if possible, provide output of `coredumpctl dump copyq` -- to see where the app crashed -- maybe the issue is really elsewhere.

Still doesn't work...
The  output of `coredumpctl dump copyq`  is as follows(I cannot understand this so far ╥﹏╥...):
```
[mint@localhost ~]$ coredumpctl dump copyq
           PID: 5608 (copyq)
           UID: 1000 (mint)
           GID: 1000 (mint)
        Signal: 11 (SEGV)
     Timestamp: Thu 2020-11-12 02:01:28 CST (26s ago)
  Command Line: copyq
    Executable: /usr/bin/copyq
 Control Group: /user.slice/user-1000.slice/user@1000.service/app-gnome-extraterm-3992.scope
          Unit: user@1000.service
     User Unit: app-gnome-extraterm-3992.scope
         Slice: user-1000.slice
     Owner UID: 1000 (mint)
       Boot ID: ef10cf821903434b994b6c659f55d269
    Machine ID: 26523771bc364f848b4c9a76bd31586f
      Hostname: localhost.localdomain
       Storage: /var/lib/systemd/coredump/core.copyq.1000.ef10cf821903434b994b6c659f55d269.5608.1605117688000000.zst
       Message: Process 5608 (copyq) of user 1000 dumped core.
                
                Stack trace of thread 5608:
                #0  0x00007f0227b81e5a XKeysymToKeycode (libX11.so.6 + 0x91e5a)
                #1  0x000055ca47e347ef _ZN24QxtGlobalShortcutPrivate13nativeKeycodeEN2Qt3KeyE6QFlagsINS0_16KeyboardModifierEE (copyq + 0xf07ef)
                #2  0x000055ca47e34f41 _ZN24QxtGlobalShortcutPrivate11setShortcutERK12QKeySequence (copyq + 0xf0f41)
                #3  0x000055ca47e41041 _ZN15ClipboardServer20createGlobalShortcutERK12QKeySequenceRK7Command (copyq + 0xfd041)
                #4  0x000055ca47e41a3d _ZN15ClipboardServer15onCommandsSavedERK7QVectorI7CommandE (copyq + 0xfda3d)
                #5  0x00007f02267a3266 _Z10doActivateILb0EEvP7QObjectiPPv (libQt5Core.so.5 + 0x288266)
                #6  0x000055ca47ece86c _ZN10MainWindow14updateCommandsE7QVectorI7CommandEb (copyq + 0x18a86c)
                #7  0x000055ca47ecee33 _ZN10MainWindow21updateEnabledCommandsEv (copyq + 0x18ae33)
                #8  0x000055ca47ed1702 _ZN10MainWindow12loadSettingsER9QSettingsR9AppConfig (copyq + 0x18d702)
                #9  0x000055ca47e3ee91 _ZN15ClipboardServer12loadSettingsEv (copyq + 0xfae91)
                #10 0x000055ca47e4061d _ZN15ClipboardServerC2EP12QApplicationRK7QString (copyq + 0xfc61d)
                #11 0x000055ca47e1906a main (copyq + 0xd506a)
                #12 0x00007f022602c1a2 __libc_start_main (libc.so.6 + 0x281a2)
                #13 0x000055ca47e197ee _start (copyq + 0xd57ee)
                
                Stack trace of thread 5614:
                #0  0x00007f0225ff16c2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6c2)
                #1  0x00007f020ad32f4b util_queue_thread_func (radeonsi_dri.so + 0x491f4b)
                #2  0x00007f020ad32a17 impl_thrd_routine (radeonsi_dri.so + 0x491a17)
                #3  0x00007f0225feb3f9 start_thread (libpthread.so.0 + 0x93f9)
                #4  0x00007f0226105b03 __clone (libc.so.6 + 0x101b03)
                
                Stack trace of thread 5613:
                #0  0x00007f0225ff16c2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6c2)
                #1  0x00007f020ad32f4b util_queue_thread_func (radeonsi_dri.so + 0x491f4b)
                #2  0x00007f020ad32a17 impl_thrd_routine (radeonsi_dri.so + 0x491a17)
                #3  0x00007f0225feb3f9 start_thread (libpthread.so.0 + 0x93f9)
                #4  0x00007f0226105b03 __clone (libc.so.6 + 0x101b03)
                
                Stack trace of thread 5615:
                #0  0x00007f0225ff16c2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6c2)
                #1  0x00007f020ad32f4b util_queue_thread_func (radeonsi_dri.so + 0x491f4b)
                #2  0x00007f020ad32a17 impl_thrd_routine (radeonsi_dri.so + 0x491a17)
                #3  0x00007f0225feb3f9 start_thread (libpthread.so.0 + 0x93f9)
                #4  0x00007f0226105b03 __clone (libc.so.6 + 0x101b03)
                
                Stack trace of thread 5617:
                #0  0x00007f0225ff16c2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6c2)
                #1  0x00007f020ad32f4b util_queue_thread_func (radeonsi_dri.so + 0x491f4b)
                #2  0x00007f020ad32a17 impl_thrd_routine (radeonsi_dri.so + 0x491a17)
                #3  0x00007f0225feb3f9 start_thread (libpthread.so.0 + 0x93f9)
                #4  0x00007f0226105b03 __clone (libc.so.6 + 0x101b03)
                
                Stack trace of thread 5619:
                #0  0x00007f0225ff16c2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6c2)
                #1  0x00007f020ad32f4b util_queue_thread_func (radeonsi_dri.so + 0x491f4b)
                #2  0x00007f020ad32a17 impl_thrd_routine (radeonsi_dri.so + 0x491a17)
                #3  0x00007f0225feb3f9 start_thread (libpthread.so.0 + 0x93f9)
                #4  0x00007f0226105b03 __clone (libc.so.6 + 0x101b03)
                
                Stack trace of thread 5629:
                #0  0x00007f0225ff16c2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6c2)
                #1  0x00007f020ad32f4b util_queue_thread_func (radeonsi_dri.so + 0x491f4b)
                #2  0x00007f020ad32a17 impl_thrd_routine (radeonsi_dri.so + 0x491a17)
                #3  0x00007f0225feb3f9 start_thread (libpthread.so.0 + 0x93f9)
                #4  0x00007f0226105b03 __clone (libc.so.6 + 0x101b03)
                
                Stack trace of thread 5627:
                #0  0x00007f0225ff16c2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6c2)
                #1  0x00007f020ad32f4b util_queue_thread_func (radeonsi_dri.so + 0x491f4b)
                #2  0x00007f020ad32a17 impl_thrd_routine (radeonsi_dri.so + 0x491a17)
                #3  0x00007f0225feb3f9 start_thread (libpthread.so.0 + 0x93f9)
                #4  0x00007f0226105b03 __clone (libc.so.6 + 0x101b03)
                
                Stack trace of thread 5630:
                #0  0x00007f0225ff16c2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6c2)
                #1  0x00007f020ad32f4b util_queue_thread_func (radeonsi_dri.so + 0x491f4b)
                #2  0x00007f020ad32a17 impl_thrd_routine (radeonsi_dri.so + 0x491a17)
                #3  0x00007f0225feb3f9 start_thread (libpthread.so.0 + 0x93f9)
                #4  0x00007f0226105b03 __clone (libc.so.6 + 0x101b03)
                
                Stack trace of thread 5623:
                #0  0x00007f0225ff16c2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6c2)
                #1  0x00007f020ad32f4b util_queue_thread_func (radeonsi_dri.so + 0x491f4b)
                #2  0x00007f020ad32a17 impl_thrd_routine (radeonsi_dri.so + 0x491a17)
                #3  0x00007f0225feb3f9 start_thread (libpthread.so.0 + 0x93f9)
                #4  0x00007f0226105b03 __clone (libc.so.6 + 0x101b03)
                
                Stack trace of thread 5609:
                #0  0x00007f02260faa0f __poll (libc.so.6 + 0xf6a0f)
                #1  0x00007f0225339d1e g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa2d1e)
                #2  0x00007f02252e641f g_main_context_iteration (libglib-2.0.so.0 + 0x4f41f)
                #3  0x00007f02267bfa2f _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a4a2f)
                #4  0x00007f022677365b _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x25865b)
                #5  0x00007f02265e22e7 _ZN7QThread4execEv (libQt5Core.so.5 + 0xc72e7)
                #6  0x00007f0215960a47 _ZN22QDBusConnectionManager3runEv (libQt5DBus.so.5 + 0x17a47)
                #7  0x00007f02265e34bc _ZN14QThreadPrivate5startEPv (libQt5Core.so.5 + 0xc84bc)
                #8  0x00007f0225feb3f9 start_thread (libpthread.so.0 + 0x93f9)
                #9  0x00007f0226105b03 __clone (libc.so.6 + 0x101b03)
                
                Stack trace of thread 5626:
                #0  0x00007f0225ff16c2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6c2)
                #1  0x00007f020ad32f4b util_queue_thread_func (radeonsi_dri.so + 0x491f4b)
                #2  0x00007f020ad32a17 impl_thrd_routine (radeonsi_dri.so + 0x491a17)
                #3  0x00007f0225feb3f9 start_thread (libpthread.so.0 + 0x93f9)
                #4  0x00007f0226105b03 __clone (libc.so.6 + 0x101b03)
                
                Stack trace of thread 5620:
                #0  0x00007f0225ff16c2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6c2)
                #1  0x00007f020ad32f4b util_queue_thread_func (radeonsi_dri.so + 0x491f4b)
                #2  0x00007f020ad32a17 impl_thrd_routine (radeonsi_dri.so + 0x491a17)
                #3  0x00007f0225feb3f9 start_thread (libpthread.so.0 + 0x93f9)
                #4  0x00007f0226105b03 __clone (libc.so.6 + 0x101b03)
                
                Stack trace of thread 5624:
                #0  0x00007f0225ff16c2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6c2)
                #1  0x00007f020ad32f4b util_queue_thread_func (radeonsi_dri.so + 0x491f4b)
                #2  0x00007f020ad32a17 impl_thrd_routine (radeonsi_dri.so + 0x491a17)
                #3  0x00007f0225feb3f9 start_thread (libpthread.so.0 + 0x93f9)
                #4  0x00007f0226105b03 __clone (libc.so.6 + 0x101b03)
                
                Stack trace of thread 5622:
                #0  0x00007f0225ff16c2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6c2)
                #1  0x00007f020ad32f4b util_queue_thread_func (radeonsi_dri.so + 0x491f4b)
                #2  0x00007f020ad32a17 impl_thrd_routine (radeonsi_dri.so + 0x491a17)
                #3  0x00007f0225feb3f9 start_thread (libpthread.so.0 + 0x93f9)
                #4  0x00007f0226105b03 __clone (libc.so.6 + 0x101b03)
                
                Stack trace of thread 5621:
                #0  0x00007f0225ff16c2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6c2)
                #1  0x00007f020ad32f4b util_queue_thread_func (radeonsi_dri.so + 0x491f4b)
                #2  0x00007f020ad32a17 impl_thrd_routine (radeonsi_dri.so + 0x491a17)
                #3  0x00007f0225feb3f9 start_thread (libpthread.so.0 + 0x93f9)
                #4  0x00007f0226105b03 __clone (libc.so.6 + 0x101b03)
                
                Stack trace of thread 5618:
                #0  0x00007f0225ff16c2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6c2)
                #1  0x00007f020ad32f4b util_queue_thread_func (radeonsi_dri.so + 0x491f4b)
                #2  0x00007f020ad32a17 impl_thrd_routine (radeonsi_dri.so + 0x491a17)
                #3  0x00007f0225feb3f9 start_thread (libpthread.so.0 + 0x93f9)
                #4  0x00007f0226105b03 __clone (libc.so.6 + 0x101b03)
                
                Stack trace of thread 5616:
                #0  0x00007f0225ff16c2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6c2)
                #1  0x00007f020ad32f4b util_queue_thread_func (radeonsi_dri.so + 0x491f4b)
                #2  0x00007f020ad32a17 impl_thrd_routine (radeonsi_dri.so + 0x491a17)
                #3  0x00007f0225feb3f9 start_thread (libpthread.so.0 + 0x93f9)
                #4  0x00007f0226105b03 __clone (libc.so.6 + 0x101b03)
                
                Stack trace of thread 5625:
                #0  0x00007f0225ff16c2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6c2)
                #1  0x00007f020ad32f4b util_queue_thread_func (radeonsi_dri.so + 0x491f4b)
                #2  0x00007f020ad32a17 impl_thrd_routine (radeonsi_dri.so + 0x491a17)
                #3  0x00007f0225feb3f9 start_thread (libpthread.so.0 + 0x93f9)
                #4  0x00007f0226105b03 __clone (libc.so.6 + 0x101b03)
                
                Stack trace of thread 5628:
                #0  0x00007f0225ff16c2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6c2)
                #1  0x00007f020ad32f4b util_queue_thread_func (radeonsi_dri.so + 0x491f4b)
                #2  0x00007f020ad32a17 impl_thrd_routine (radeonsi_dri.so + 0x491a17)
                #3  0x00007f0225feb3f9 start_thread (libpthread.so.0 + 0x93f9)
                #4  0x00007f0226105b03 __clone (libc.so.6 + 0x101b03)
Refusing to dump core to tty (use shell redirection or specify --output).
[mint@localhost ~]$ 
```

**Comment by hluk** [comment] 2020-11-11 18:30
Oh, that looks like an issue with CopyQ/Wayland integration. I believe I fixed it just recently (https://github.com/hluk/CopyQ/commit/1cfac3f83).

The recent fixes for Wayland were not released yet (the changes are still in `wayland` development branch in this repo).

You can try starting CopyQ with: `env QT_QPA_PLATFORM=xcb copyq`

For details see: https://copyq.readthedocs.io/en/latest/known-issues.html#on-linux-global-shortcuts-and-pasting-doesn-t-work

**Comment by MintYale** [comment] 2020-11-14 18:47
> Oh, that looks like an issue with CopyQ/Wayland integration. I believe I fixed it just recently ([1cfac3f](https://github.com/hluk/CopyQ/commit/1cfac3f83)).
> 
> The recent fixes for Wayland were not released yet (the changes are still in `wayland` development branch in this repo).
> 
> You can try starting CopyQ with: `env QT_QPA_PLATFORM=xcb copyq`
> 
> For details see: https://copyq.readthedocs.io/en/latest/known-issues.html#on-linux-global-shortcuts-and-pasting-doesn-t-work

THANKS! `env QT_QPA_PLATFORM=xcb copyq` works just well. 

A little small flaw is that the terminal window should be always left there. If it works just like its windows version or GPaste, started with GUI icon, leaving a little icon on the status bar, would be so much more GREATER! Looking forward this to being handled perfectly in the coming versions.

BTW, I find that some apps suffering the same issue can also run this `env QT_QPA_PLATFORM=xcb {APP_NAME}` such as  **albert** and **flameshot**. I wonder if we can set X11 for some specific apps while others still use Wayland ? Or we can only wait for updating of  those apps ?

**Comment by hluk** [comment] 2020-11-15 07:12
The terminal window where you run the command doesn't have to stay open. You can use following instead and close the window:

```bash
env QT_QPA_PLATFORM=xcb copyq & disown
```

The `QT_QPA_PLATFORM` affects only Qt applications. In some cases, adding Wayland support is not trivial and often compositors (window managers) don't support common features. It might be take some time until the support is perfect in some apps.

I started using Sway Wayland compositor recently and fixed the most significant problems in CopyQ. So hopefully, the next version will support Wayland much better.

**Comment by hluk** [comment] 2020-11-15 08:58
If you want to stay updated with the Wayland support progress, see #27.

On Fedora, you can install development version of CopyQ with the Wayland fixes:

```bash
sudo dnf install 'dnf-command(copr)'
sudo dnf copr enable lholecek/copyq
sudo dnf install copyq
```

Few notes:
- Clipboard support depends on the compositor you use
- Global shortcuts won't work
- Getting current window title (some commands may depend on this) is not supported
- Sending copy/paste to current window doesn't work but you can override the functionality by using `ydotool`

To support sending copy/paste and getting current window title I use following command in CopyQ:

```ini
[Command]
Command="
    /*
    This adds support for Sway Wayland compositor.
    
    Requires `ydotool` utility to send copy/paste shortcuts to applications.
    */
    function swayGetTree() {
        var p = execute('swaymsg', '-t', 'get_tree')
        return JSON.parse(str(p.stdout))
    }
    
    function swayFindFocused(tree) {
        var nodes = tree['nodes'].concat(tree['floating_nodes'])
        for (var i in nodes) {
            var node = nodes[i]
            if (node['focused'])
                return node
            var focusedNode = swayFindFocused(node)
            if (focusedNode)
                return focusedNode
        }
        return undefined
    }
    
    function sendShortcut(shortcut) {
        execute('ydotool', 'key', shortcut)
    }
    
    global.currentWindowTitle = function() {
        var tree = swayGetTree()
        var focusedNode = swayFindFocused(tree)
        return focusedNode ? focusedNode['name'] : ''
    }
    
    global.paste = function() {
        sendShortcut('shift+insert')
    }
    
    var copy_ = global.copy
    global.copy = function() {
        if (arguments.length == 0) {
            sendShortcut('ctrl+c')
        } else {
            copy_.apply(this, arguments)
        }
    }
    
    // FIXME: Is there better way to focus previous window?
    global.focusPrevious = function() {
        hide()
    }
    
    var onClipboardChanged_ = onClipboardChanged
    onClipboardChanged = function() {
        var title = currentWindowTitle()
        if (title)
            setData(mimeWindowTitle, title)
        onClipboardChanged_()
    }"
Icon=\xf2d0
IsScript=true
Name=Sway Support
```

**Comment by MintYale** [comment] 2020-11-15 13:35
@hluk Thanks for your patience to response. I can see that you are a conscientious and professional developer. I like your excellent work CopyQ a lot and actually use its Windows edition in my work everyday. I'll keep watching this project. Hopefully I will learn to develop desktop-apps in the next coming years, then I should be able to read the src code and think about the true cause and solution of some issues too. Though I am a web/server programmer so far, I believe the basic factors of IT science are the same. Right now I can read the code of this repo, yet I don't know any API/frameworks of desktop-app-developing. Maybe you can show me some basic tutorial/doc website of how to make a desktop-app from zero?(I use fedora 33 and Windows 10) My mother tongue is not English but I can read any kind of English docs, just spending more time on it, if I have to.

**Comment by hluk** [comment] 2020-11-15 15:45
@MintYale CopyQ is written in C++ programming language and it's not the best starting point for beginners -- not only because of manual memory management (is easy to leak memory or cause a crash by accessing an invalid memory) but also because building a C++ app is relatively difficult.

I would suggest starting with Python and Qt framework for a quick dive into desktop application development. On Fedora, you can install `python3-pyside2` (or `python3-qt5`) package and [start writing a Qt app](https://www.qt.io/qt-for-python).

The Qt API usage is very similar in C++ and Python and translates quite easily between the languages. Python is ideal candidate for prototyping or testing some features before getting it into the C++ app.
