### ISSUE TITLE
App crashes everytime at startup on MacOS even after doing steps in README

### ISSUE THREAD

**Issue by adamency** [hluk/CopyQ#2818] opened 2024-08-21 09:25 UTC
**Describe the bug**

After installing the app via

```
brew install --cask copyq
```

I got the message saying the app "is damaged".

So I ran the 2 commands suggested in the README

```
xattr -d com.apple.quarantine /Applications/CopyQ.app
codesign --force --deep --sign - /Applications/CopyQ.app
```

And now the message is different but the app still never launches successfully:

<img width="273" alt="Screenshot 2024-08-21 at 11 23 42" src="https://github.com/user-attachments/assets/bb75f292-5228-4871-ad6c-f579c388d155">

**To Reproduce**

Already explained above

**Expected behavior**

App works

**Screenshots**

**Version, OS and Environment**

- Application Version (for example 7.1.0)
9.0.0
- OS (for example Windows 11, Ubuntu 22.04, macOS Sonoma 14.4)
MacOS Ventura 13.5
- Desktop environment, window manager (if applicable)

**Additional context**

**Comment by hluk** [comment] 2024-09-14 07:41
Closing as duplicate of #2637.

**Closed by hluk** 2024-09-14 07:41 UTC
Labels: bug
