### ISSUE TITLE
Doesnot run on Ubuntu 18.04 Beta 2

### ISSUE THREAD

**Issue by shamim2018** [hluk/CopyQ#927] opened 2018-04-15 16:55 UTC
Tried Flatpack, Snap and Gnome software versions. All installed successfully. But don't launch.

**Comment by hluk** [comment] 2018-04-16 15:44
Can you post log file? It's usually in `$HOME/.local/share/copyq/copyq/copyq.log` (you might be able to get the path by running `copyq info log`).

**Comment by VitalyArtemiev** [comment] 2018-06-03 15:15
Hello.
I am running Ubuntu 18.04 LTS, having a similar problem. After the installation copyq was running as expected, gnome integration worked (icon showed up in the top panel), etc. However, after a reboot it failed to start. I couldn't start it using the shortcut or "copyq" command. It's listed in the process list but the window doesn't show up. I was able to start it by killing the processes and using "sudo copyq" from terminal, however, the gnome shell integration and some other features didn't work.

Find the log attached. The "server already running" messages are probably due to me trying to launch it without killing the process first.

[copyq.log](https://github.com/hluk/CopyQ/files/2066060/copyq.log)

**Comment by VitalyArtemiev** [comment] 2018-06-10 10:52
The window shows up, however, as I said before, shell integration doesn't work. When I first installed and launched it, it showed up on the top bar (tray). This doesn't happen anymore, regardless of the settings.

**Comment by hluk** [comment] 2018-06-16 11:20
Is this still an issue? I cannot reproduce it on Ubuntu 18.04.

**Comment by hluk** [comment] 2018-06-23 06:45
I'm closing this one. I don't have enough information and cannot reproduce this issue.

@VitalyArtemiev Your issue seems different, since the application runs but the tray icon won't show. Perhaps Qt 5 apps need some additional libraries installed for tray icon to work.

**Closed by hluk** 2018-06-23 06:45 UTC
Labels: help wanted
