### ISSUE TITLE
If autostart is enabled copyq font is really big

### ISSUE THREAD

**Issue by ranamalo** [hluk/CopyQ#465] opened 2016-03-13 04:43 UTC
I am using Debian Jessie gnome3.  If I check the Autostart option in File -> Preferences  -> General tab, when I bring up the copyq main page the font is very large.  In fact if you go into preference you can't see everything because of the size of the font.  However if I disable autostart and start copyq up manually once in a gnome session it looks fine.

**Comment by ranamalo** [comment] 2016-03-13 04:44
Let me know if you need any more info.

**Comment by hluk** [comment] 2016-03-13 15:43
It seems that Gnome 3 is providing wrong resolution/DPI at start.

Perhaps you can fix that by changing line with `Exec=...` in the autostart file `~/.config/autostart/copyq.desktop` to one of following.

```ini
Exec=sh -c "QT_DEVICE_PIXEL_RATIO=1 copyq"
```
```ini
Exec=sh -c "QT_HIGDPI_SCALE_FACTOR=1 copyq"
```

**Comment by ranamalo** [comment] 2016-03-14 03:12
Thanks for the reply.  Neither of those worked.

**Comment by hluk** [comment] 2016-03-15 06:41
Then perhaps following would work.

```ini
Exec=sh -c "sleep 5; copyq"
```

**Comment by baniobloom** [comment] 2017-12-19 15:05
The problem is I change the resolution of the screen once I log in.  Other applications readjust their resolution automatically, but copyq does not.

**Comment by hluk** [comment] 2017-12-19 16:37
@baniobloom OK, perhaps there is some signal or configuration CopyQ ignores. I'll try to reproduce it by changing font size or DPI in system.

**Comment by hluk** [comment] 2018-09-16 10:54
Closing. If you still have this issue please reopen and provide details.

**Closed by hluk** 2018-09-16 10:54 UTC
Labels: bug
