### ISSUE TITLE
Copyq icon selected to appear on the taskbar doesn't

### ISSUE THREAD

**Issue by skonvols2k** [hluk/CopyQ#1315] opened 2020-02-14 09:25 UTC
**Describe the bug**
If "Always show all icons in the notification area" is "off" and "copyq.exe" is selected to appear ("on") it will not appear on the bar at next reboot.

**To Reproduce**
1. set "Always show all icons in the notification area" on "off"
2. select "on" for copyq.exe
3. confirm that the icon is visible
4. reboot the os
5. check if the copyq icon is hidden or visible

**Expected behavior**
icon should remain visible if selected so.

**Screenshots**

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version [e.g. 3.7.2] 3.10
 - OS [e.g. Windows] Windows 10
 - Desktop environment, window manager (if applicable)

**Additional context**

**Comment by hluk** [comment] 2020-02-15 09:51
Closing as duplicate of #1258.

Quick solution is to use builds mentioned in https://github.com/hluk/CopyQ/issues/1258#issuecomment-581394634.

**Comment by hluk** [comment] 2020-02-15 09:52
Sorry, the correct builds are mentioned in https://github.com/hluk/CopyQ/issues/1258#issuecomment-581787642.

**Closed by hluk** 2020-02-15 09:51 UTC
Labels: bug
