### ISSUE TITLE
Copying spreadsheet cells in LibreOffice CopyQ running causes application windows to flash and hang

### ISSUE THREAD

**Issue by ppesek** [hluk/CopyQ#613] opened 2016-12-31 07:43 UTC
Copying multiple (at least a few) normal spreadsheet cells (misc text content) in LibreOffice 5.1 with CopyQ 2.8.1 (MacOS 10.12) causes window flashes in any application and prevents text entry until CopyQ is killed.  Once that is done, the problem resolves until it is run again.  Copying anything else to the clipboard before restarting CopyQ ends the problem.  Content which I attempted to copy in LibreOffice doesn't appear in the CopyQ menu.  

I presume the application is somehow unable to tolerate the content it is receiving.  I was able to reproduce bug with multiple random spreadsheet files.

**Comment by hluk** [comment] 2016-12-31 09:03
Seem to be related to #580.

LibreOffice Calc creates images of the copied cells which can take some time and CopyQ needs to receive all relevant data (text, html and images).

Currently the only workaround is to disable "Images" in "Items" config tab (also disable "Data" or remove any "image/*" formats from "Data" plugin configuration).

Does this happen only when copying large amount of cells?

**Comment by ppesek** [comment] 2017-01-01 21:34
Not only "large"--so I tried some tests--10 cells works fine.  At 12, the app simply crashes--same for 15, 20 etc.  At some point after that intermediate phase, its doesn't crash (50ish+ at least), but starts the flashing behavior which goes on (seemingly) indefinitely until I kill the process.  I suspect there is more going on here than it simply needing time to 'gonculate' lot's of data.

**Comment by hluk** [comment] 2017-01-02 08:09
I cannot reproduce this (on Linux). Can you send some document and steps to reproduce (if this doesn't happen on any document)?

**Comment by ppesek** [comment] 2017-01-03 10:43
[bugtest.xlsx](https://github.com/hluk/CopyQ/files/682060/bugtest.xlsx)

Simply copy enough of the cells with CopyQ running on default settings.  
Disabling "Images" and "Data" as suggested above fixes the problem.

**Comment by ppesek** [comment] 2017-01-03 10:47
Interestingly, if I have just plain text in the cells (not formulas), it doesn't happen...

**Comment by ppesek** [comment] 2017-01-22 20:06
This is fixed under 2.8.2

**Comment by hluk** [comment] 2017-01-23 06:29
Thanks for the info. Closing.

**Closed by hluk** 2017-01-23 06:29 UTC
