### ISSUE TITLE
Empty tray menu in Cinnamon using Qt5

### ISSUE THREAD

**Issue by KenjiTakahashi** [hluk/CopyQ#431] opened 2016-01-02 01:03 UTC
This was reported by several users to CopyQ [AUR package](https://aur.archlinux.org/packages/copyq/) of which I'm maintainer.
I'm not sure whether it is CopyQ or Cinnamon, so I'm just gonna start here.
Like said in the title, CopyQ built with Qt5, running in Cinnamon. When clicking the tray icon, an empty "menu widget" appears (see screenshot). Also it seems that the tray icon itself is rendered weirdly - it's smaller and a bit to the side(?) (see second screenshot with Qt4 version for comparison).
Compiled with Qt4 works, also tried on MATE and Xfce - works as well. Seems like something's on CopyQ<->Qt5<->Cinnamon.
To add to the plot, the empty widget part "fixes itself" after invoking "copyq menu" from terminal (icon stays weird).

![qt5](https://cloud.githubusercontent.com/assets/431488/12072780/9efad9ca-b0f2-11e5-99fd-efb71b387a44.png)
![qt4](https://cloud.githubusercontent.com/assets/431488/12072781/a87de082-b0f2-11e5-8788-cb69f0cc5b71.png)

All of this was tested by me using Manjaro 15.12 Cinnamon, CopyQ 2.5.0, Cinnamon 2.8.6.

**Comment by hluk** [comment] 2016-01-02 09:28
Some desktop environments replace Qt tray with their version and try to reconstruct the menu when user clicks the tray icon. The menu invoked with `copyq menu` is the probably the original version.

There are [a lot of bug reports](https://github.com/linuxmint/Cinnamon/search?q=tray&type=Issues) for tray in Cinnamon.

Perhaps using [different tray applet](http://cinnamon-spices.linuxmint.com/applets/view/154) can solve some issues.

**Comment by KenjiTakahashi** [comment] 2016-01-03 17:53
I think you might very well be right.
I'm wondering, though, why it fixes itself after calling `copyq menu`? Perhaps it triggers some routine that is "known" to the applet and it then decides to continue loading as expected?

**Comment by hluk** [comment] 2016-01-03 18:27
If you run the command you use CopyQ directly but if you click the tray icon it calls some wrapper libraries. I think this still involves libraries [sni-qt](https://launchpad.net/sni-qt) and [libdbusmenu](https://launchpad.net/libdbusmenu).

There is arch package for [libdbusmenu-qt5](https://www.archlinux.org/packages/extra/x86_64/libdbusmenu-qt5/) which handles creating tray menu for Qt 5 apps so the problem is likely somewhere there.

**Comment by KenjiTakahashi** [comment] 2016-01-03 19:55
I understand that. What I meant is that after invoking the command, the applet based menu starts working as well. After further investigation, though, it is not really "working", it gets "refreshed".
It goes like this. When I first start CopyQ, tray menu is empty. After calling the command, tray menu starts appearing OK. After I add new item to clipboard (e.g. copy some text), tray menu displays as before (new item does not appear). After calling the command again, tray menu gets updated with new item.

BTW: I've tried using the "collapsible" version you've linked above, but strangely enough, CopyQ icon does not appear there at all...
BTW2: I'm not sure I'll have enough urge to get to the bottom of this as I don't use Cinnamon (in fact, I don't use tray at all). I've linked this issue in the AUR page, perhaps one of the users will be willing to do the digging. Just sayin' :-).

**Comment by hluk** [comment] 2016-01-03 20:24
Oh, I think I know what is the problem. The wrapper library [libdbusmenu-qt](https://code.launchpad.net/libdbusmenu-qt) is not triggering Qt signal that is emitted before showing the menu -- in CopyQ the items in tray menu are [created/updated](https://github.com/hluk/CopyQ/blob/3ff85714625ea2c3df04ae3dab229bf4057f9b94/src/gui/mainwindow.cpp#L318-L319) right before the menu pops up. This seems to be bug in the library and as you mention only with Qt 5.

**Comment by raqua** [comment] 2016-03-15 07:48
I am affected by this bug as well. I understand, that this is not a bug in CopyQ, but is this issue in libdbusmenu-qt reported somewhere so we can get that fixed? I would be happy to report it, but I do not really understand much about it, so maybe if you could report it ... I would really appreciate it. Thanks for considersing that and thanks for otherwise great SW.

**Comment by hluk** [comment] 2016-03-15 08:32
@raqua You can post the bug report [here](https://bugs.launchpad.net/ubuntu/+source/libdbusmenu-qt) (I don't have an account for bug posting there and I'm quite skeptical about the wrapper libraries for tray).

**Comment by genachka** [comment] 2016-12-17 16:40
As referenced in #595 for me, I'm not even seeing an empty icon on 16.04 with Cinnamon 3.2.2 using CopyQ 3.8.x. As noted in that issue, a workaround with CopyQ 3.7.1 of exiting CopyQ after login and starting it up again the icon would display. But with CopyQ 3.8.x that no longer works. The only way I can get to CopyQ is the keyboard shortcut which is a bit frustrating.

**Comment by hluk** [comment] 2016-12-17 16:48
Oh sorry, I closed #595 as duplicate of this but this is just empty tray menu and not missing tray icon.

Is `libdbusmenu-qt`/`libdbusmenu-qt5` and `sni-qt` still needed to be installed? If it is, I should add those as dependencies for Debian/Ubuntu package.

**Comment by genachka** [comment] 2016-12-17 16:53
Looks like I already have them installed:
libdbusmenu-qt5 is already the newest version (0.9.3+16.04.20160218-0ubuntu1).
sni-qt is already the newest version (0.2.7+15.10.20150729-0ubuntu1).

**Comment by hluk** [comment] 2016-12-17 17:00
OK, seems that `sni-qt` shouldn't be needed with newer Qt libraries ([info here](https://blog.martin-graesslin.com/blog/2014/06/where-are-my-systray-icons/)).

@genachka Try to start `copyq` from console and see if there are any warnings or errors.

**Comment by genachka** [comment] 2016-12-17 17:28
I exited and confirmed the process wasn't running. Started from console, copied to clipboard, pasted from clipboard, open via keyboard hotkeys. Nothing generated any errors or warnings on console.

**Comment by hluk** [comment] 2016-12-19 09:11
I tested this in Cinnamon 2.8.6 on Ubuntu 16.04 and on Cinnamon 3.2.0 on Arch Linux.

If I start CopyQ after the panel and tray is started, everything looks fine. When starting CopyQ on login, tray icon is missing.

As workaround I edit file `~/.config/autostart/copyq.desktop` and replace 

```ini
Exec="/usr/bin/copyq"
```

with

```ini
Exec=sh -c "sleep 5; /usr/bin/copyq"
```

Not sure why you cannot see icon even after restart. Seems like something in Cinnamon is broken or a dependency is missing. Problem could also be that the icon is in SVG format (`/usr/share/icons/hicolor/scalable/apps/copyq-normal.svg`).

**Comment by hluk** [comment] 2016-12-19 09:38
As mentioned in #589, the icon could be in incompatible format, so you can try to run following to re-convert the icon.

```sh
sudo convert -background none /usr/share/icons/hicolor/scalable/apps/copyq-normal.svg{,}
```

**Comment by genachka** [comment] 2016-12-19 15:54
`I tested this in Cinnamon 2.8.6 on Ubuntu 16.04 and on Cinnamon 3.2.0 on Arch Linux.`
Any chance you can also try it with Cinnamon 3.2.2? That's what I'm on and may help figuring this out.

Converting icon via (`sudo convert -background none /usr/share/icons/hicolor/scalable/apps/copyq-normal.svg{,}`) didn't make a difference. :(

**Comment by hluk** [comment] 2016-12-21 09:17
Cau you test this with `copyq-2.8.2-beta` package? Packages are [here](http://download.opensuse.org/repositories/home:/lukho:/copyq/). It should install icons in PNG format too.

**Comment by genachka** [comment] 2016-12-21 21:09
Unfortunately it didn't help. :(

**Comment by genachka** [comment] 2017-01-05 17:45
I thought I may have grabbed the previous version from that link and so I just tried again and am getting dependency errors though it looks like I did have the right version before:
```
Preparing to unpack copyq_2.8.2.beta.1.r1.g609b8ca1_amd64.deb ...
Unpacking copyq (2.8.2.beta.1.r1.g609b8ca1) over (2.8.2.beta.1.r1.g609b8ca1) ...
dpkg: dependency problems prevent configuration of copyq:
 copyq depends on libqt5core5a (>= 5.6.0~beta); however:
  Version of libqt5core5a:amd64 on system is 5.5.1+dfsg-16ubuntu7.2.
 copyq depends on libqt5gui5 (>= 5.6.0~beta) | libqt5gui5-gles (>= 5.6.0~beta); however:
  Version of libqt5gui5:amd64 on system is 5.5.1+dfsg-16ubuntu7.2.
  Package libqt5gui5-gles is not installed.
 copyq depends on libqt5script5 (>= 5.6.0~beta); however:
  Version of libqt5script5:amd64 on system is 5.5.1+dfsg-2build1.
 copyq depends on libqt5widgets5 (>= 5.6.0~beta); however:
  Version of libqt5widgets5:amd64 on system is 5.5.1+dfsg-16ubuntu7.2.

dpkg: error processing package copyq (--install):
 dependency problems - leaving unconfigured
```

**Comment by hluk** [comment] 2017-01-06 07:29
@genachka I just tested tray icon with Cinnamon 3.2.7 on Arch Linux and icon is still visible in tray.

Can you check if option "Disable tray" is unchecked under "Tray" config tab?

Also you can try removing following icons (which are replaced with PNG formats in new version):
- `/usr/share/icons/hicolor/scalable/apps/copyq-normal.svg`
- `/usr/share/icons/hicolor/scalable/apps/copyq-busy.svg`

**Comment by genachka** [comment] 2017-01-06 15:11
"Disable tray" is unchecked. I deleted the two .svg icons but when I double checked to see if there were .png versions of them I don't see them there. Did the new package not install them?

**Comment by hluk** [comment] 2017-01-06 15:59
@genachka I probably won't be able to do anything with this -- looks like bug in Cinnamon with Qt 5 apps (strangely I don't see this issue on Arch Linux). Do you have any icons in tray (especially Dropbox, Skype or other apps using Qt 5)?

**Comment by genachka** [comment] 2017-01-06 16:19
I do have Skype (for Linux Alpha) and Shutter and Remmina and Chrome icons on the tray, though I don't know which of these are Qt 5?

**Comment by matteotanca** [comment] 2017-10-30 08:16
install libqt4-svg to solve this.

**Comment by hluk** [comment] 2017-10-30 10:08
Is this still an issue? Last time I checked the app with Cinnamon everything worked fine.

@matteotanca The app uses Qt 5, not Qt 4, so libqt4-svg shouldn't be needed. (Actually, only OpenSUSE package uses Qt 4 but I'll be dropping it altogether in near future.)

**Comment by genachka** [comment] 2017-10-30 10:10
@matteotanca already had that installed, doesn't help me.

@hluk Yes, still an issue for me.

**Comment by raqua** [comment] 2017-10-30 10:24
Works fine for me on Cinnamon and Arch Linux.

**Comment by genachka** [comment] 2017-10-30 10:26
@raqua which Cinnamon version? I'm on 3.4.6 under Ubuntu 16.04 and have no tray icon.

**Comment by raqua** [comment] 2017-10-30 10:29
I am not currently at my home computer, but I guess I am on the latest Cinnamon version for Arch linux, which should be 3.4.6.
Right now, I am on Mint 18 with Cinnamon 3.4.6 and it works fine too.

**Comment by hluk** [comment] 2017-10-30 11:34
@genachka Do you use any extensions for tray?

**Comment by genachka** [comment] 2017-10-30 13:04
Nope, no extensions.

**Comment by matteotanca** [comment] 2017-10-31 13:47
In Ubuntu 16.04 LTX if you uninstall  libqt4-svg you have not tray icon. If you install it then tray icon is visible, so maybe its still using qt4 for some reason.

**Comment by hluk** [comment] 2017-10-31 15:28
@matteotanca What does `copyq --version` print? (Qt 4 or Qt 5?)

Maybe the library that provides indicator compatibility for Qt 5 tray requires Qt 4 -- it's still odd that it needs library for SVG (libqt4-svg) because the tray icons are installed also in PNG format (looks like it picked wrong format).

**Comment by genachka** [comment] 2017-10-31 16:05
@matteotanca I already had libqt4-svg installed, still no icon:
`libqt4-svg is already the newest version (4:4.8.7+dfsg-5ubuntu2).`

**Closed** 2017-12-19 13:22 UTC

**Comment by genachka** [comment] 2018-01-30 16:36
@matteotanca followed your steps, didn't help me. I then purged and cleaned copyq from my environment and upgraded to 17.10. In 17.10 it now works. Don't know for sure if it was because of clean up or just something that is different with the upgrade to 17.10 but in the end it works now.
