### ISSUE TITLE
I always get Plain text, never formatted.

### ISSUE THREAD

**Issue by SmileyStiles** [hluk/CopyQ#768] opened 2017-08-21 18:33 UTC
When I copy some text, it gets cleaned of all formatting before it ends up in the clipboard tab.  If I edit the clip from the clipboard using the F2 editor and add some formatting like bigger font, color, bold, etc. and then paste that, it gets cleaned of all formatting.
Also I have the "Save and display HTML and rich text" option checked.
I'm using Windows 7 and CopyQ 3.0.3

**Comment by hluk** [comment] 2017-08-22 12:53
Are you using "Show simple items" option? (It's in "History" config tab.)

**Comment by SmileyStiles** [comment] 2017-08-22 17:24
No I do not have that checked.  That still kills my double-clicking.

**Comment by hluk** [comment] 2017-08-22 18:06
Can you check if the edited item contains `text/html` format? You can list the formats for selected items by pressing F4 key (or "Show Content..." from context menu or "Item" menu).

**Comment by SmileyStiles** [comment] 2017-08-22 20:01
It does. It has text/html and text/plain.

**Comment by hluk** [comment] 2017-08-23 10:28
Try to move "Text" item in "Item" config tab to the top (the plugins in the list are used in order of appearance).
![image](https://user-images.githubusercontent.com/38054/29611580-4f69d912-87fe-11e7-8ec3-1a4356c1862c.png)

**Comment by SmileyStiles** [comment] 2017-08-23 17:13
Sorry, that didn't help.  As far as I can tell it had no effect at all.

**Comment by hluk** [comment] 2017-08-23 17:44
How do you copy/paste the item? If it's with Enter or double-click, do you have any commands which override Enter/Return shortcut?

**Comment by SmileyStiles** [comment] 2017-08-23 17:51
It is the Enter and double-click, but no formatting text shows up in the preview when I originally copy it.  The only Automatic command that I have is to move images to a separate tab.
[Command]
Name=Move Images to Other Tab
Input=image/png
Automatic=true
Remove=true
Icon=\xf03e
Tab=&Images

I do have a global shortcut that I open CopyQ with and it looks like this:
[Command]
Name=Show/hide main window
Command="
    copyq: toggle()
"
Icon=\xf022
GlobalShortcut=ctrl+`

**Comment by ionsquare** [comment] 2018-03-28 18:10
I'm having the same problem in Ubuntu 16.04 with CopyQ v3.0.0

**Comment by hluk** [comment] 2018-04-01 05:34
I think this could be connected to option "Paste mouse selection with clipboard". If you select a text, this option copies it also to clipboard. The problem is when you press Ctrl+C after making the selection. In this case the clipboard can still get overridden with selection which is always plain text.

I recently fix that by checking if clipboard changed after selection and omitting the synchronization (400aa065f384f63283257a3bd88d28c035bb362a). Will be available in next version (hopefully released soon).

**Comment by ionsquare** [comment] 2018-04-12 16:25
It must have been something around the underlying format of the text I was copying. I was able to workaround the issue by choosing the `Edit` option on the clipboard entry, click save, and now that entry keeps the proper formatting every time.

I think it's safe to close this issue, thanks for waiting for my confirmation.

**Closed** 2018-04-14 07:48 UTC
