### ISSUE TITLE
"CopyQ" is damaged and can't be opened.

### ISSUE THREAD

**Issue by bukacdan** [hluk/CopyQ#2662] opened 2024-04-04 06:38 UTC
**Describe the bug**
"CopyQ" is damaged and can't be opened.

**To Reproduce**
1. Install CopyQ either from brew or .dmg from github
2. Lauch app
3. "CopyQ" is damaged and can't be opened.

**Expected behavior**
Application should launch.

**Screenshots**
<img width="261" alt="Screenshot 2024-04-04 at 14 34 32" src="https://github.com/hluk/CopyQ/assets/45018832/d84481c0-4afe-4402-8356-2d66c612c89b">

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - CopyQ 8.0
 - MacOS Sonoma 14.3.1 (23D60)
 - MacBook Pro M1

**Comment by marcosandremartins** [comment] 2024-04-06 19:18
**Same here**

- CopyQ 8.0
- MacOS Sonoma 14.4.1
-  MacBook Air M2

**Comment by pmiriyev** [comment] 2024-04-09 20:50
same here

**Comment by hanexthink** [comment] 2024-04-11 08:05
same here
<img width="372" alt="image" src="https://github.com/hluk/CopyQ/assets/35567025/a54e0981-3572-4e81-b0a3-4970f9601cf3">
<img width="392" alt="image" src="https://github.com/hluk/CopyQ/assets/35567025/ac7524c8-7855-4187-8e74-95ed81c4b5eb">

**Comment by SzVLsY** [comment] 2024-04-11 15:01
same

xattr -d com.apple.quarantine /Applications/"CopyQ.app"

This usually helps, but then I get the error that Copy Q exited unexpectedly

**Comment by jody-frankowski** [comment] 2024-04-13 16:02
Since Big Sur, native ARM applications require to be signed (afaik, AMD64 ones through Rosetta2 still don't):

```sh
xattr -rd com.apple.quarantine /Applications/CopyQ.app
codesign -f --deep -s - /Applications/CopyQ.app
```

The first time you try to paste you should see a system pop-up prompting to allow Accessibility access. If you don't, try manually removing/adding the app through the System Settings.

**Comment by hluk** [comment] 2024-04-14 05:54
Closing as duplicate of  #2652.

**Closed by hluk** 2024-04-14 05:54 UTC
Labels: bug, macOS, help wanted
