### ISSUE TITLE
Please use Sqllite.

### ISSUE THREAD

**Issue by luapfr** [hluk/CopyQ#2390] opened 2023-07-03 23:19 UTC
Due to the huge amount of current items more than 67000 I had to abandon copyq and use ClipAngel.

Any predictions of using database like sqllite?

I see that you focused on having many features, but you neglected something more important, which is storage.

You don't need to create a compatibility between a version with binary data and Sqllite data, we would all know that it would be a fresh install without leveraging the data.

**Comment by Slackadays** [comment] 2023-07-05 00:27
Dupe of #510, and it looks like almost no clipboard managers offer this feature (specifically unlimited history) despite the fact that many of them already use sqlite. However, ClipAngel (your choice), Ditto, and [cb](https://github.com/Slackadays/Clipboard) do offer it.

**Comment by luapfr** [comment] 2023-07-05 01:25
You don't need to have unlimited history but 100,000 clips would be great.
 I reach this amount every 3 months.

Think carefully about this possibility, because as you mentioned, most already use sqllite, just need copyq.

**Closed** 2023-07-22 12:02 UTC
Labels: feature

**Comment by luapfr** [comment] 2023-07-22 12:54
Did you close the topic without any position on it?

I love copyQ but when it passes 7000 items it's a horrible job because it's very slow.

I don't understand why not switch to sqllite.

**Comment by hluk** [comment] 2023-07-23 07:02
It might be a good idea to migrate to SQLite. Unfortunately, it is not a simple change and I do not have time to do this any time soon. Any help with that would be appreciated.

See also previous discussions: #510, #1471, #1144, #2165

**Comment by luapfr** [comment] 2023-07-23 13:13
I would really like to be able to help you with this programming unfortunately I got the source codes and I couldn't understand anything.
 I'm a programmer in Delphi.
 
  But I see that the colleague could take a break in new features to create this new structure based on sqlite.
