### ISSUE TITLE
Not able to past http or https from clipboard

### ISSUE THREAD

**Issue by natashh** [hluk/CopyQ#893] opened 2018-03-09 20:25 UTC
Anyone habe got a problem with pasting http or https text from the app ?

**Comment by natashh** [comment] 2018-03-09 20:26
![image](https://user-images.githubusercontent.com/12864518/37228333-88dba8dc-23e0-11e8-98b0-d45405a683cc.png)

**Comment by natashh** [comment] 2018-03-09 20:27
I see it when I enter is not pasting. What can be wrong?

**Comment by natashh** [comment] 2018-03-09 20:30
I see the problem only in Chrome. When I am coping from Chrome pasting is not working, from Firefox it is ok.

**Comment by natashh** [comment] 2018-03-09 20:44
The interesting thing is I am able to copy/paste uri in Chrome, but not able to copy it outside Chrome in example past to notepad.

**Comment by hluk** [comment] 2018-03-10 12:04
I'm closing this as duplicate of #724. This will be probably fixed in next version.

**Closed by hluk** 2018-03-10 12:04 UTC
