### ISSUE TITLE
The package for ArchLinux was updated from v3.1.2 to v3.2.0 and now the application crashes on startup.

### ISSUE THREAD

**Issue by glowingsword** [hluk/CopyQ#908] opened 2018-03-24 10:55 UTC
$ copyq -v
CopyQ Clipboard Manager v3.2.0 (hluk@email.cz)
Built with: Qt 5.10.1, LibQxt 0.7.0

$ COPYQ_LOG_LEVEL=trace copyq
TRACE: Created session mutex: copyq_mutex
DEBUG: Server "/home/glowingsword/.config/copyq/.copyq_s" started.
DEBUG: Geometry: Window "ProcessManagerDialog": New geometry for "Options/ProcessManagerDialog_geometry_1920x1080"
DEBUG: Geometry: Window "MainWindow": Restore geometry "Options/MainWindow_geometry": 645x421,0,0 -> 645x535,575,302
TRACE: Loading plugin: /usr/lib/copyq/plugins/libitemdata.so
TRACE: Loading plugin: /usr/lib/copyq/plugins/libitemencrypted.so
TRACE: Loading plugin: /usr/lib/copyq/plugins/libitemfakevim.so
TRACE: Loading plugin: /usr/lib/copyq/plugins/libitemimage.so
TRACE: Loading plugin: /usr/lib/copyq/plugins/libitemnotes.so
TRACE: Loading plugin: /usr/lib/copyq/plugins/libitempinned.so
TRACE: Loading plugin: /usr/lib/copyq/plugins/libitemsync.so
TRACE: Loading plugin: /usr/lib/copyq/plugins/libitemtags.so
TRACE: Loading plugin: /usr/lib/copyq/plugins/libitemtext.so
TRACE: Loading plugin: /usr/lib/copyq/plugins/libitemweb.so
DEBUG: Loading configuration
DEBUG: Tab "&clipboard": Loading items
DEBUG: Tab "&clipboard": 114 items loaded
DEBUG: Configuration loaded
DEBUG: Starting monitor
DEBUG: Executing: copyq monitorClipboard
DEBUG: Got save state request from session manager.
TRACE: Socket 1: Creating socket.
TRACE: Socket 1: Sending message to client (exit code: 9).
TRACE: Write message (13 bytes).
TRACE: Message written.
TRACE: Socket 1: Message sent to client.
TRACE: Socket 1: Sending message to client (exit code: 9).
TRACE: Write message (34 bytes).
TRACE: Message written.
TRACE: Socket 1: Message sent to client.
TRACE: Socket 1: Sending message to client (exit code: 9).
TRACE: Write message (13 bytes).
TRACE: Message written.
TRACE: Socket 1: Message sent to client.
TRACE: Socket 1: Sending message to client (exit code: 9).
TRACE: Write message (34 bytes).
TRACE: Message written.
TRACE: Socket 1: Message sent to client.
DEBUG: Executing: copyq provideClipboard
TRACE: Socket 2: Creating socket.
TRACE: Socket 2: Sending message to client (exit code: 9).
TRACE: Write message (219 bytes).
TRACE: Message written.
TRACE: Socket 2: Message sent to client.
TRACE: Socket 2: Sending message to client (exit code: 9).
TRACE: Write message (34 bytes).
TRACE: Message written.
TRACE: Socket 2: Message sent to client.
TRACE: Socket 1: Sending message to client (exit code: 9).
TRACE: Write message (13 bytes).
TRACE: Message written.
TRACE: Socket 1: Message sent to client.
TRACE: Getting clipboard data.
TRACE: Got clipboard data.
TRACE: Skipping format: text/plain
TRACE: Skipping format: application/x-copyq-owner
TRACE: Skipping format: TARGETS
TRACE: Skipping format: MULTIPLE
TRACE: Skipping format: TIMESTAMP
TRACE: Skipping format: SAVE_TARGETS
TRACE: Socket 1: Sending message to client (exit code: 9).
TRACE: Write message (22 bytes).
TRACE: Message written.
TRACE: Socket 1: Message sent to client.
DEBUG: New item: Adding
TRACE: Socket 1: Sending message to client (exit code: 9).
TRACE: Write message (13 bytes).
TRACE: Message written.
TRACE: Socket 1: Message sent to client.
Segmentation fault (core dumped)

In strace I see that all crash on 

openat(AT_FDCWD, "/home/glowingsword/.config/copyq/copyq_geometry.ini", O_RDONLY|O_CLOEXEC) = 27
statx(27, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=STATX_ATTR_COMPRESSED, stx_mode=S_IFREG|0644, stx_size=1706, ...}) = 0
statx(27, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=STATX_ATTR_COMPRESSED, stx_mode=S_IFREG|0644, stx_size=1706, ...}) = 0
statx(27, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=STATX_ATTR_COMPRESSED, stx_mode=S_IFREG|0644, stx_size=1706, ...}) = 0
read(27, "[Options]\nAboutDialog_geometry=@ByteArray(\\x1\\xd9\\xd0\\xcb\\0\\x2\\0\\0\\0\\0\\x2\\xbf\\0\\0\\0\\xcf\\0\\0\\x4\\xc0\\0\\0\\x3\\xa9\\0\\0\\x2\\xbf\\0\\0\\0\\xf4\\0\\0\\x4\\xc0\\0\\0\\x3\\xa9\\0\\0\\0\\0\\0\\0\\0\\0\\a\\x80)\nAboutDialog_geometry_1920x1080=@ByteArray(\\x1\\xd9\\xd0\\xcb\\0\\x2\\0\\0\\0\\0\\x2\\xbf\\0\\0\\0\\xcf\\0\\0\\x4\\xc0\\0\\0\\x3\\xa9\\0\\0\\x2\\xbf\\0\\0\\0\\xf4\\0\\0\\x4\\xc0\\0\\0\\x3\\xa9\\0\\0\\0\\0\\0\\0\\0\\0\\a\\x80)\nCommandDialog_geometry_global=@ByteArray(\\x1\\xd9\\xd0\\xcb\\0\\x2\\0\\0\\0\\0\\x1\\x66\\0\\0\\0\\xd1\\0\\0\\x6+\\0\\0\\x3\\xcb\\0\\0\\x1\\x66\\0\\0\\0\\xf6\\0\\0\\x6+\\0\\0\\x3\\xcb\\0\\0\\0\\0\\0\\0\\0\\0\\a\\x80)\nCommandDialog_geometry_global_1920x1080=@ByteArray(\\x1\\xd9\\xd0\\xcb\\0\\x2\\0\\0\\0\\0\\x1\\x66\\0\\0\\0\\xd1\\0\\0\\x6+\\0\\0\\x3\\xcb\\0\\0\\x1\\x66\\0\\0\\0\\xf6\\0\\0\\x6+\\0\\0\\x3\\xcb\\0\\0\\0\\0\\0\\0\\0\\0\\a\\x80)\nMainWindow_geometry=@ByteArray(\\x1\\xd9\\xd0\\xcb\\0\\x2\\0\\0\\0\\0\\0\\0\\0\\0\\0\\x1b\\0\\0\\a\\x7f\\0\\0\\x4\\x37\\0\\0\\x2?\\0\\0\\x1.\\0\\0\\x4\\xc3\\0\\0\\x3\\x44\\0\\0\\0\\0\\x2\\0\\0\\0\\a\\x80)\nMainWindow_geometry_1920x1080=@ByteArray(\\x1\\xd9\\xd0\\xcb\\0\\x2\\0\\0\\0\\0\\0\\0\\0\\0\\0\\x1b\\0\\0\\a\\x7f\\0\\0\\x4\\x37\\0\\0\\x2?\\0\\0\\x1.\\0\\0\\x4\\xc3\\0\\0\\x3\\x44\\"..., 16384) = 1706
read(27, "", 14678)                     = 0
statx(AT_FDCWD, "/home/glowingword/.config/copyq/copyq_geometry.ini", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=STATX_ATTR_COMPRESSED, stx_mode=S_IFREG|0644, stx_size=1706, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2445, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2445, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2445, ...}) = 0
close(27)                               = 0
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
poll([{fd=3, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
writev(3, [{iov_base="\2\0\4\0\5\0\340\1\0@\0\0\r\0\340\1", iov_len=16}], 1) = 16
poll([{fd=3, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
writev(3, [{iov_base="\2\0\4\0\5\0\340\1\0@\0\0\r\0\340\1", iov_len=16}], 1) = 16
poll([{fd=3, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
writev(3, [{iov_base="\24\0\6\0\5\0\340\1#\0\0\0#\0\0\0\0\0\0\0\t\0\0\0", iov_len=24}], 1) = 24
futex(0x7ffccd8ae148, FUTEX_WAIT_PRIVATE, 0, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x55973b6b1bf8, FUTEX_WAKE_PRIVATE, 1) = 0
poll([{fd=3, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
writev(3, [{iov_base="\22\0\17\0\5\0\340\1#\0\0\0#\0\0\0 \0\0\0\t\0\0\0\3\0\0\0\1\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\22\0\30\0\5\0\340\1(\0\0\0)\0\0\0 \0\0\0\22\0\0\0\23\2\0\0?\2\0\0.\1\0\0\205\2\0\0\27\2\0\0D\0\0\0`\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\n\0\0\0\23\0\3\0\5\0\340\1D\0\0\0\24\0\6\0\5\0\340\1\200\1\0\0\200\1\0\0\0\0\0\0\24\0\0\0", iov_len=192}], 1) = 192
futex(0x7ffccd8ae118, FUTEX_WAIT_PRIVATE, 0, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x55973b6b1bf8, FUTEX_WAKE_PRIVATE, 1) = 0
poll([{fd=3, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
writev(3, [{iov_base="\22\0\v\0\5\0\340\1\200\1\0\0\200\1\0\0 \0\0\0\5\0\0\0\3\0\0\0>\0\0\0~\0\0\0\0\0\0\0\0\0\0\0\24\0\6\0\5\0\340\1A\1\0\0\4\0\0\0\0\0\0\0\0\4\0\0", iov_len=68}], 1) = 68
futex(0x7ffccd8ae0f8, FUTEX_WAIT_PRIVATE, 0, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x55973b6b1bf8, FUTEX_WAKE_PRIVATE, 1) = 0
poll([{fd=3, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
writev(3, [{iov_base="\22\0\10\0\5\0\340\1A\1\0\0\4\0\0\0 \0\0\0\2\0\0\0H\1\0\0G\1\0\0", iov_len=32}], 1) = 32
futex(0x55973b6b1bf8, FUTEX_WAIT_PRIVATE, 2, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x55973b6b1bf8, FUTEX_WAKE_PRIVATE, 1) = 0
poll([{fd=3, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
writev(3, [{iov_base="\1\0\10\0\26\0\340\1\5\0\340\1\377\377\377\377\1\0\1\0\0\0\1\0\202\3\0\0\0\0\0\0\22\0\7\0\5\0\340\1Y\1\0\0!\0\0\0 \0\0\0\1\0\0\0\26\0\340\1\23\0\3\0\5\0\340\1X\1\0\0\22\0\7\0\26\0\340\1X\1\0\0\6\0\0\0 \0\0\0\1\0\0\0uEy\0\10\0\2\0\5\0\340\1+\0\1\0", iov_len=112}], 1) = 112
futex(0x7ffccd8ae158, FUTEX_WAIT_PRIVATE, 0, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x55973b6b1bf8, FUTEX_WAKE_PRIVATE, 1) = 0
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC, 0) = 27
connect(27, {sa_family=AF_UNIX, sun_path=@"/tmp/.X11-unix/X0"}, 20) = 0
getpeername(27, {sa_family=AF_UNIX, sun_path=@"/tmp/.X11-unix/X0"}, [124->20]) = 0
uname({sysname="Linux", nodename="arch", ...}) = 0
access("/run/user/1001/gdm/Xauthority", R_OK) = 0
openat(AT_FDCWD, "/run/user/1001/gdm/Xauthority", O_RDONLY) = 30
fstat(30, {st_mode=S_IFREG|0700, st_size=96, ...}) = 0
read(30, "\1\0\0\4arch\0\0\0\22MIT-MAGIC-COOKIE-1\0\20\341\201\223Z\203\nY\7\200\17.\30\333\214\233\365\377\377\0\4arch\0\0\0\22MIT-MAGIC-COOKIE-1\0\20\341\201\223Z\203\nY\7\200\17.\30\333\214\233\365", 4096) = 96
read(30, "", 4096)                      = 0
close(30)                               = 0
getsockname(27, {sa_family=AF_UNIX}, [124->2]) = 0
fcntl(27, F_GETFL)                      = 0x2 (flags O_RDWR)
fcntl(27, F_SETFL, O_RDWR|O_NONBLOCK)   = 0
fcntl(27, F_SETFD, FD_CLOEXEC)          = 0
poll([{fd=27, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=27, revents=POLLOUT}])
writev(27, [{iov_base="l\0\v\0\0\0\22\0\20\0\0\0", iov_len=12}, {iov_base="", iov_len=0}, {iov_base="MIT-MAGIC-COOKIE-1", iov_len=18}, {iov_base="\0\0", iov_len=2}, {iov_base="\341\201\223Z\203\nY\7\200\17.\30\333\214\233\365", iov_len=16}, {iov_base="", iov_len=0}], 6) = 48
recvfrom(27, 0x55973bc29e20, 8, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=27, events=POLLIN}], 1, -1)   = 1 ([{fd=27, revents=POLLIN}])
recvfrom(27, "\1\0\v\0\0\0\3\f", 8, 0, NULL, NULL) = 8
recvfrom(27, "\320\253\265\0\0\0 \3\377\377\37\0\0\1\0\0\24\0\377\377\1\7\0\0  \10\377\0\0\0\0The X.Org Foundation\1\1 \0\0\0\0\0\4\10 \0\0\0\0\0\10\10 \0\0\0\0\0\17\20 \0\0\0\0\0\20\20 \0\0\0\0\0\30  \0\0\0\0\0   \0\0\0\0\0;\5\0\0 \0\0\0\377\377\377\0\0\0\0\0003\0\332\0\0\0178\4\370\3\35\1\1\0\1\0!\0\0\0\1\0\30\7\30\0\340\1\0\0\0\0!\0\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0\"\0\0\0\5\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0E\3\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0F\3\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0G\3\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0H\3\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0I\3\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0J\3\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0K\3\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0L\3\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0M\3\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0N\3\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0O\3\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0P\3\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0Q\3\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0R\3\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0S\3\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0T\3\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0U\3\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0V\3\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0W\3\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0X\3\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0Y\3\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0Z\3\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0[\3\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0\\\3\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0]\3\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0^\3\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0_\3\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0`\3\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0a\3\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0b\3\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0c\3\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0d\3\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0e\3\0\0\4\10\0\1\0\0\377\0\0\377\0\0\377\0\0\0\0\0\0\0f\3\0\0"..., 12300, 0, NULL, NULL) = 12300
poll([{fd=27, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=27, revents=POLLOUT}])
writev(27, [{iov_base="b\0\5\0\f\0\0\0BIG-REQUESTS", iov_len=20}], 1) = 20
poll([{fd=27, events=POLLIN}], 1, -1)   = 1 ([{fd=27, revents=POLLIN}])
recvmsg(27, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\1\0\1\0\0\0\0\0\1\205\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 32
poll([{fd=27, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=27, revents=POLLOUT}])
writev(27, [{iov_base="\205\0\1\0", iov_len=4}], 1) = 4
poll([{fd=27, events=POLLIN}], 1, -1)   = 1 ([{fd=27, revents=POLLIN}])
recvmsg(27, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\1\0\2\0\0\0\0\0\377\377?\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 32
recvmsg(27, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=27, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=27, revents=POLLOUT}])
writev(27, [{iov_base="7\0\5\0\0\0 \3;\5\0\0\10\0\0\0\377\377\377\0\24\0\6\0;\5\0\0\27\0\0\0\37\0\0\0\0\0\0\0\0\341\365\5", iov_len=44}, {iov_base=NULL, iov_len=0}, {iov_base="", iov_len=0}], 3) = 44
poll([{fd=27, events=POLLIN}], 1, -1)   = 1 ([{fd=27, revents=POLLIN}])
recvmsg(27, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\1\10\4\0*\0\0\0\37\0\0\0\0\0\0\0\250\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0Xft.antialias:\t1\nXft.autohint:\tfalse\nXft.dpi:\t96\nXft.hinting:\t1\nXft.hintstyle:\thintfull\nXft.lcdfilter:\tlcddefault\nXft.rgba:\trgb\nXcursor.size:\t24\nXcursor.theme:\tAdwaita\n", iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 200
recvmsg(27, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=27, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=27, revents=POLLOUT}])
writev(27, [{iov_base="b\0\5\0\t\0 \3", iov_len=8}, {iov_base="XKEYBOARD", iov_len=9}, {iov_base="\0\0\0", iov_len=3}], 3) = 20
poll([{fd=27, events=POLLIN}], 1, -1)   = 1 ([{fd=27, revents=POLLIN}])
recvmsg(27, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\1\0\5\0\0\0\0\0\1\207U\211\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 32
recvmsg(27, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(27, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=27, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=27, revents=POLLOUT}])
writev(27, [{iov_base="\207\0\2\0\1\0\0\0", iov_len=8}, {iov_base=NULL, iov_len=0}, {iov_base="", iov_len=0}], 3) = 8
poll([{fd=27, events=POLLIN}], 1, -1)   = 1 ([{fd=27, revents=POLLIN}])
recvmsg(27, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\1\1\6\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 32
recvmsg(27, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(27, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=27, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=27, revents=POLLOUT}])
writev(27, [{iov_base="\20\0\7\0\22\0\0\0_NET_ACTIVE_WINDOW\0\0", iov_len=28}, {iov_base=NULL, iov_len=0}, {iov_base="", iov_len=0}], 3) = 28
poll([{fd=27, events=POLLIN}], 1, -1)   = 1 ([{fd=27, revents=POLLIN}])
recvmsg(27, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\1\0\7\0\0\0\0\0006\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 32
recvmsg(27, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(27, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=27, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=27, revents=POLLOUT}])
writev(27, [{iov_base="\3\0\2\0\5\0\340\1\16N\2\0\5\0\340\1", iov_len=16}, {iov_base=NULL, iov_len=0}, {iov_base="", iov_len=0}], 3) = 16
poll([{fd=27, events=POLLIN}], 1, -1)   = 1 ([{fd=27, revents=POLLIN}])
recvmsg(27, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\1\0\10\0\3\0\0\0\202\3\0\0\1\0\1\1\377\377\377\377\0\0\0\0\0\0\0\0\4\0\340\1\177\240b\0\0\0\0\0\0\0\0\0\1\30\t\0\0\0\0\0;\5\0\0\0\0\0\0\205\2\27\2\0\0\0\0\0\0\0\0\0\0\0\0", iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 76
recvmsg(27, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(27, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(27, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(27, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=27, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=27, revents=POLLOUT}])
writev(27, [{iov_base="<\0\2\0\0\0 \3+N\1\0", iov_len=12}, {iov_base=NULL, iov_len=0}, {iov_base="", iov_len=0}], 3) = 12
poll([{fd=27, events=POLLIN}], 1, -1)   = 1 ([{fd=27, revents=POLLIN}])
recvmsg(27, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\1\2\v\0\0\0\0\0\275+\340\3\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 32
recvmsg(27, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(27, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
shutdown(27, SHUT_RDWR)                 = 0
close(27)                               = 0
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
poll([{fd=3, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
writev(3, [{iov_base="\f\0\4\0\5\0\340\1@\0\0\0\0\0\0\0", iov_len=16}], 1) = 16
recvmsg(6, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=5, events=POLLIN}, {fd=6, events=POLLIN}, {fd=7, events=POLLIN}, {fd=12, events=POLLIN}, {fd=15, events=POLLIN}, {fd=17, events=POLLIN}, {fd=18, events=POLLIN}, {fd=26, events=POLLIN}, {fd=28, events=POLLIN|POLLOUT}, {fd=33, events=POLLIN}, {fd=36, events=POLLIN}], 11, 0) = 2 ([{fd=5, revents=POLLIN}, {fd=28, revents=POLLOUT}])
read(5, "\36\0\0\0\0\0\0\0", 16)        = 8
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
poll([{fd=3, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLIN|POLLOUT}])
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\26\0\204\2\5\0\340\1\5\0\340\1\0\0\0\0\n\0-\0\205\2\27\2\0\0\0\0\0\0\0\0", iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 32
futex(0x55973b6b1c48, FUTEX_WAKE_PRIVATE, 1) = 1
writev(3, [{iov_base="\24\0\6\0\5\0\340\1A\1\0\0\4\0\0\0\0\0\0\0\0\4\0\0", iov_len=24}], 1) = 24
futex(0x55973b6b1bf8, FUTEX_WAKE_PRIVATE, 1) = 1
poll([{fd=3, events=POLLIN}], 1, -1)    = 1 ([{fd=3, revents=POLLIN}])
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\226\0\204\2\5\0\340\1\5\0\340\1\0\0\0\0?\2.\1\205\2\27\2\0\0\0\0\0\0\0\0\34\0\204\2\5\0\340\1\217\1\0\0\203Ey\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 64
futex(0x55973b6b1c4c, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x55973b6b1bf8, FUTEX_WAKE_PRIVATE, 1) = 1
poll([{fd=3, events=POLLIN}], 1, -1)    = 1 ([{fd=3, revents=POLLIN}])
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\1 \205\2\2\0\0\0\4\0\0\0\0\0\0\0\2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0H\1\0\0G\1\0\0", iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 40
futex(0x55973b6b1c48, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x55973b6b1bf8, FUTEX_WAKE_PRIVATE, 1) = 1
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
poll([{fd=3, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
writev(3, [{iov_base="(\0\4\0\5\0\340\1;\5\0\0\0\0\0\0", iov_len=16}], 1) = 16
futex(0x7ffccd8aef58, FUTEX_WAIT_PRIVATE, 0, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x55973b6b1bf8, FUTEX_WAKE_PRIVATE, 1) = 0
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
write(28, "\0\0\0\n\0\0\0\t\0\0\0\1\0\1", 14) = 14
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xa00000096} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)

**Comment by hluk** [comment] 2018-03-25 12:57
I'm closing this as duplicate of #909.

**Closed by hluk** 2018-03-25 12:57 UTC
