### ISSUE TITLE
menu clips truncated, any way to make it show more info?

### ISSUE THREAD

**Issue by zeltak** [hluk/CopyQ#335] opened 2015-03-24 20:06 UTC
Hi again

i use the menu popup via a hotkey. the problem is i cant find anyway to make the text expand a bit to actually make sense of whats in the line. it currently looks like this:

https://paste.xinu.at/M4J/

as you can see there is no way to make sense of what text is in each line. anywhere to config that? if not can there be an option to widen the lines/popup window size

thx

z

**Comment by hluk** [comment] 2015-03-25 11:48
Wow, the text is really short. Normally a lot more characters is visible.

I guess it has something to do with DPI of font. I'll try to reproduce it and fix it.

**Comment by zeltak** [comment] 2015-03-25 12:45
Dear hluk. yes i use a new HiDPI laptop (2560x144) indeed so this maybe the issue?
using it on gnome3 with latest copyq.

kind regards

Z

**Comment by hluk** [comment] 2015-03-25 13:08
Yup, seems to be the problem. Also, from the look of the icons in menu, Qt 4.8 doesn't seems to care about about DPI much.

I try not to use pixel sizes but I cannot properly test it. I'll try to increase DPI and see if I can reproduce it.

If you see strange inconsistent sizes/geometries elsewhere, please let me know. Thanks.

**Comment by hluk** [comment] 2015-03-25 19:43
Should be fixed with:
- 2c936108126d3291e579f347c42a160c7159f924 (icon sizes and other sizes)
- 45a468682a9d42d84c4515a16bcdf565c05ba347 (text in tray menu)

**Comment by hluk** [comment] 2015-04-13 13:20
Can you check if there are still any DPI issues in CopyQ version 2.4.6?

**Closed** 2015-06-21 07:40 UTC
Labels: bug, waffle:in progress
