### ISSUE TITLE
Win 10 x64 CopyQ icon initially hidden most of the time

### ISSUE THREAD

**Issue by Columbus1000** [hluk/CopyQ#1299] opened 2020-01-26 07:21 UTC
I hope I'm not repeating a known issue; I couldn't see anything obvious referring to it. If I've missed dozens of comments about this before, my apologies; I'm new to Github. 

(So much so, I inadvertently "closed" my first attempt at reporting this possible bug, because I thought that meant "Finished Editing, Submit" rather than "The Issue is Solved". So sorry about this repetition; like I said, I'm a newbie to Github.)

This is my issue:

About 60 to 80% of the time, launching CopyQ in Win 10 x64 leads to its icon inititially being hidden in the "Hidden Icons" group of the Notification Area. Global shortcuts still work fine.

Dragging the icon back to the tray works fine for that session. But only for that session, and after further restarts it's a crap shoot. Most of the time, the icon is hidden, sometimes it's not. This is new behaviour that I have not seen in earlier versions, and I've tried every one (Windows x64 only).

At first I suspected it was due to my main PC being a tad screwy, and perhaps suffering from a corrupt icon cache or something, but installing a brand-new, virgin copy of CopyQ onto a Dell laptop a few minutes ago reveals the exact same behaviour .... so it's not a corrupted data stack etc. It is something to do with this current Windows build, it seems. No amount of dragging to reset the icon's state will "stick" ... it remains a crap shoot, and invisible at boot time about 80% of the time.

This is a frustrating bug, cos it only happens "most" of the time, but that 2nd Dell laptop convinces me I'm onto something. This is Win 10 Pro Version 1909 (OS Build 18363.592). I'll try to atttach a screencap of this phenomenon.

I do hope somebody can confirm this issue. Perhaps it's unique to Version 1909?

I love the program, please keep up the good work.

Greetings from Fremantle, Western Australia

![CopyQ hidden icon](https://user-images.githubusercontent.com/60309420/73131968-3db3a980-404f-11ea-8e03-5f20a35f8545.jpg)

**Comment by hluk** [comment] 2020-01-26 17:41
Thanks for the detailed report. This looks like duplicate of #1258. Unfortunately, it looks like it might be an issue in the Qt framework which the application uses (I believe it broke because of upgrade to newer Qt version).

**Closed by hluk** 2020-01-26 17:41 UTC
Labels: bug

**Comment by Columbus1000** [comment] 2020-01-27 08:45
You're right, of course. It is indeed the exact same issue. I've had complete success with your replacement test versions; I'll report this fact back in that post #1258.
