### ISSUE TITLE
[Feat] Add an expiration time for clipboard history items

### ISSUE THREAD

**Issue by jonathanlermitage** [hluk/CopyQ#1476] opened 2020-09-08 23:35 UTC
I have not found where I can do that, please tell me if this feature exists already: I would like to automatically delete history items after a specific duration, e.g. to delete items that have been stored for more than 30 minutes.  
Thx,

**Comment by hluk** [comment] 2020-09-09 14:20
Duplicate of #344.

**Closed by hluk** 2020-09-09 14:20 UTC
Labels: feature
