### ISSUE TITLE
paste selected item from the tray not working. i hear beep instead

### ISSUE THREAD

**Issue by clydzik** [hluk/CopyQ#2497] opened 2023-10-03 14:16 UTC
When i use copy Q randomly , or 50% of a time when i call a try from the shortcut , choose item to paste it is not pasted; i hear the beep instead.
After a beep i have to hit cmd+v to paste the item.

This is not issue with privileges because sometimes it works; sometimes not.

I tried to find scenario like switching windows and try again. I cannot find a pattern.

Maybe this is issue with multiple monitor setup. It looks like it try to paste to early or in wrong windo

**To Reproduce**
1. open try from shortcut
2. select item to paste
3. press enter to paste
4. i hear beep and selected item is not pasted

**Expected behavior**
it should paste all the time

**Version, OS and Environment**
 - Application Version 7.1.0-g42c02f2d-master
 - OS MacOS Ventrua 13.6
 - two monitor setup

**Comment by hluk** [comment] 2023-10-05 09:07
Not sure about the "beep", but otherwise this seems like a duplicate of #1601.

Configuring the delays may help: `copyq config window_wait_after_raise_ms 50`

**Closed by hluk** 2023-10-05 09:07 UTC
Labels: bug

**Comment by clydzik** [comment] 2023-10-06 07:57
Thanks for the tips.
Unfortunately non of these worked for me.
That is strange since i was able to configure the delays.
But i do not see the effect. I put 1000 to make sure i see them.

I still hear the beep ;) but it seems immediate without any delays.
I tried to set few of these delays to see the effect but somehow i cannot see it ?!

This is actual config:
```
➜  ~ /Applications/CopyQ.app/Contents/MacOS/CopyQ config
activate_closes=true
  Close main window after item is activated
activate_focuses=true
  Focus last window after item is activated
activate_item_with_single_click=false
  Activate item with single click
activate_pastes=true
  Paste to current window after item is activated
always_on_top=false
  Keep main window above other windows
autocompletion=true
  Automatically show popup to complete function, type and variable names in commands
autostart=true
  Run the application on system startup
change_clipboard_owner_delay_ms=150
  Delay to save new clipboard owner window title
check_clipboard=true
  Save clipboard in history
clipboard_notification_lines=0
  Number of lines to show for new clipboard content.
  
  Set to 0 to disable.
clipboard_tab=&clipboard
  Name of tab that will automatically store new clipboard content.
  
  Leave empty to disable automatic storing.
close_on_unfocus=true
  Close main window when other application has focus
close_on_unfocus_delay_ms=500
  Delay to close the main window when unfocused/deactivated
command_history_size=100
  Number of commands to keep in action dialog history
confirm_exit=true
  Confirm application exit
disable_tray=false
  Don't show tray icon; minimize window when closed
edit_ctrl_return=true
  Leave unchecked for Return key to save edited item and Ctrl+Return create new line.
  
  Note: Edited items can be saved with F2 disregarding this option.
editor=open -t -W -n %1
  External editor command (%1 is file to edit).
    Examples:
      gedit %1
      notepad %1
      gvim -f %1
      xterm -e vim %1
expire_tab=0
  Unload each tab from memory after specified number of minutes of inactivity.
  
  Set to 0 not to unload tabs.
filter_case_insensitive=true
  Use case-insensitive item search
filter_regular_expression=false
  Use regular expressions to search items
hide_main_window=false
  Hide main window when closed
hide_main_window_in_task_bar=false
  Avoid showing entry for the main window in the task bar
hide_tabs=false
  Hide tabs (press Alt key to show)
hide_toolbar=false
  Hide toolbar
hide_toolbar_labels=true
  Hide tool&bar labels
item_popup_interval=0
  Interval in seconds to display notification for new clipboard content or if item is copied to clipboard (only if main window is closed).
  
  Set to 0 to disable this.
  
  Set to -1 to keep visible until clicked.
max_process_manager_rows=1000
  Maximum number of rows in process manager dialog
maxitems=9999
  Maximum number of items in each tab
move=true
  Move item to the top of the list after it is activated
native_menu_bar=false
  Use native menu bar, otherwise the menu bar shows in the main window
native_notifications=false
  &Use native notifications
native_tray_menu=false
  Use native tray menu (menu items search may not work)
notification_horizontal_offset=10
  Notification distance from left or right screen edge in screen points
notification_maximum_height=100
  Maximum height for notification in screen points
notification_maximum_width=300
  Maximum width for notification in screen points
notification_position=3
  Position on screen for notifications
notification_vertical_offset=10
  Notification distance from top or bottom screen edge in screen points
number_search=true
  Enable searching for numbers, otherwise pressing a digit key activates item on that position
open_windows_on_current_screen=true
  Enable to open windows on current screen. Disable to open windows where they were last closed
restore_geometry=true
  Restore position and size for the main window and other dialogs
row_index_from_one=true
  Index items/rows in UI starting from 1 instead of 0 (in scripts, rows are always indexed from 0)
save_delay_ms_on_item_added=300000
  Tab save delay after an item is added to the tab
save_delay_ms_on_item_edited=1000
  Tab save delay after an item is edited in the tab
save_delay_ms_on_item_modified=300000
  Tab save delay after an item is modified in the tab
save_delay_ms_on_item_moved=1800000
  Tab save delay after an item is moved in the tab
save_delay_ms_on_item_removed=600000
  Tab save delay after an item is removed from the tab
save_filter_history=false
  Save and restore history of item filters
save_on_app_deactivated=true
  Save unsaved tabs immediately after the app is deactivated (main window loses focus)
script_paste_delay_ms=250
  Delay after pasting from script (when using `paste()`)
show_advanced_command_settings=false
  Show advanced command configuration in Command dialog
show_simple_items=false
  Show single line description of each item.
  
  Use Item Preview to display whole items.
show_tab_item_count=false
  Show number of items in tabs
style=
  Current application style (available styles can be listed with `copyq styles` command)
tab_tree=false
  Show tree with tabs instead of tab bar
tabs=&clipboard
  Ordered list of tabs
text_tab_width=8
  Width of Tab character in number of spaces
text_wrap=true
  Break text if it's too long to fit on line
transparency=0
  Transparency of main window if unfocused.
  
  Note: This is not supported on all systems.
transparency_focused=0
  Transparency of main window if focused.
  
  Note: This is not supported on all systems.
tray_commands=true
  Show command for current clipboard content in tray menu
tray_images=true
  Show image preview next to menu items
tray_item_paste=true
  Paste item to current window after selecting it in menu
tray_items=5
  Number of items in tray menu
tray_menu_open_on_left_click=false
  Open tray menu on left mouse button
tray_tab=&clipboard
  Name of tab to show in tray menu (empty for the first tab)
tray_tab_is_current=true
  Show items from current tab in tray menu
vi=false
  Support for Vi navigation keys (H, J, K, L and more), slash (/) key to search
window_key_press_time_ms=100
  Interval to keep simulated keys (Shift+Insert) pressed for pasting (needed for some apps)
window_paste_with_ctrl_v_regex=
  Regular expression matching window titles where Ctrl+V should be used for pasting instead of the default Shift+Insert
window_wait_after_raised_ms=1000
  Delay after raising target window for pasting
window_wait_before_raise_ms=1000
  Delay before trying to raise target window for pasting
window_wait_for_modifier_released_ms=2000
  Wait for any keyboard modifiers to be released before simulating/sending shortcut for pasting
window_wait_raised_ms=1000
  Wait interval for raising target window for pasting

➜  ~ 
```

**Comment by hluk** [comment] 2023-10-06 10:28
> I still hear the beep ;) but it seems immediate without any delays.

CopyQ does not produce any audio unless you have a custom command that does that (see the command list in Commands dialog - F6 shortcut).
