### ISSUE TITLE
Opening Paste Items window causes loss of caret in text field

### ISSUE THREAD

**Issue by Inirdin** [hluk/CopyQ#2432] opened 2023-08-21 15:09 UTC
**Is your feature request related to a problem? Please describe.**
The currently selected text field gets unselected when opening Paste Items window. Selecting item and hitting enter then does nothing, the item doesn't get pasted into the text field. Happens in Windows Explorer, Adobe software and so on. It happens everywhere where the text field is selected (for lack of better word) "temporarily".

![gif showcasing the issue](https://i.imgur.com/s7oF6Uc.gif)

**Describe the solution you'd like**
When opening and selecting items from the Paste Items window keep caret in selected text field and paste the selected item there.

**Describe alternatives you've considered**
I tried changing the Paste Items shortcut, obviously that didn't help. I could understand that it wouldn't work while selecting with mouse, but the caret disappears even with selecting with keyboard.

**Additional context**
Same issue as #2075.

**Comment by hluk** [comment] 2023-10-04 13:30
Duplicate of  #1468.

**Closed by hluk** 2023-10-04 13:30 UTC
Labels: feature
