### ISSUE TITLE
Pattern matching commands works on selected text without being copied to clipboard.

### ISSUE THREAD

**Issue by Negirno** [hluk/CopyQ#372] opened 2015-08-08 13:54 UTC
Maybe this isn't a bug but rather a feature, but if it's the former, I would like to report it.

It seems that that any CopyQ command which have its Match field filled with something, automatically triggers when selecting said pattern **before** being copied to system clipboard.

Example command:

```
[Command]
Name=Test Command
Match=^something
Automatic=true
Icon=\xf016
Tab=&test
```

When activated, try to select the pattern `something` in any text editor or text field by double clicking on it or dragging the text selection. The selected text will automatically appears in the newly created "test" tab. Sometimes it doesn't work, but selecting something other, and the selecting the pattern again usually does the trick.

This also works with other scripts, for example the Linkify command in the [CopyQ's Command Examples](https://github.com/hluk/CopyQ/wiki/Command-Examples) wiki page. Using that I've got duplicates of the links almost all the time (because I also pressed CTRL-C). I've tested this by selecting text in Firefox, Gedit and Gnome-terminal.

The OS I use is Ubuntu 14.04.3 LTS. If you want additional log/data stuff please provide the command to invoke them, since I'm a Linux-beginner.

Thanks in advance!

**Comment by scottkosty** [comment] 2015-08-09 00:18
> Maybe this isn't a bug but rather a feature, but if it's the former, I would like to report it.

I'm just an outsider, but I wanted to mention that feature reports are often encouraged! Please don't be hesitant to give a feature request. Developers usually like them, as long as they are well-thought out, which this one seems to be.

In fact, a good feature request is a way of contributing to open source software! So thanks for trying to make CopyQ better.

The only part of your request that I would say could be improved the part

> When activated, try to select the pattern something in any text editor or text field by double clicking on it or dragging the text selection. The selected text will automatically appears in the newly created "test" tab. Sometimes it doesn't work, but selecting something other, and the selecting the pattern again usually does the trick.

Instead of saying "in any text editor", give an example (or two) where you know it works. You haven't tried *every* text editor. So it I happen to use a different editor than you then I might not be able to reproduce the behavior you're seeing because I don't know which editor you used. Then, when you say "Sometimes it doesn't work", try to figure out why sometimes it does, sometimes it doesn't. If you can figure it out, write down steps: e.g. 1. do this simple thing. 2. do that simple thing. 3. blah... That way it's easy to get a reproducible example.

As to the actual idea, I don't have any comments, but I'm sure Lukas will.

**Comment by hluk** [comment] 2018-09-16 09:53
Closing (this looks like something fixed in new versions). If you still have this issue please reopen and provide details.

**Closed by hluk** 2018-09-16 09:53 UTC
