### ISSUE TITLE
copied image files won't display previews or paste after item swap

### ISSUE THREAD

**Issue by rockhazard** [hluk/CopyQ#932] opened 2018-04-29 16:34 UTC
CopyQ shows me a block of text when I copy an image from a file manager instead of a preview image. Neither the main window nor preview windows (F7) display the preview of the copied image. Further, if I swap to a different item, when I swap back to the image item it is not stored in the clipboard. However, I can drag the item to a directory where it will show up as a normal image file.

- In preferences, the image plugin  _is_ selected.

- I'm using Shutter for screenshots. Those screenshots **do** show previews.

Here is a sample of the text block that seems to represent a copied image:

> text/plain (55 bytes)
> /home/user/Pictures/image.jpg
> text/uri-list (62 bytes)
> file:///home/user/Pictures/image.jpg

![copyq_3 4_screenshot_preview_but_no_image_file_preview](https://user-images.githubusercontent.com/28168460/39408764-418665bc-4ba9-11e8-9584-d15f5e86427c.png)

Version: CopyQ 3.4.0
OS: Linux Mint 18/Ubuntu 18.04 [vm]/Windows 10 [vm]

**Comment by hluk** [comment] 2018-04-29 18:58
> CopyQ shows me a block of text when I copy an image from a file manager instead of a preview image.

File manager usually store only file path in clipboard, not file content. You would need a specialized command to show the image or even store the file data in items.

> Further, if I swap to a different item, when I swap back to the image item it is not stored in the clipboard.

What do you mean by "swap"?

**Comment by hluk** [comment] 2018-05-01 05:40
Looks like the problem is that when the clipboard contains text, the image is ignored (c7b28c856e6139a8e5657e654b40a5057745f690 and eac0c57d). Inkscape provides SVG as text.

Not sure if I can fix this without breaking #666 again.

**Comment by rockhazard** [comment] 2018-05-01 07:31
Well, at least it's not just a niche issue with only my equipment, and you can reproduce it, despite the ironic issue number you cited. Maybe a solution will be hammered out sometime. Thank you for looking into it!

**Comment by hluk** [comment] 2018-05-01 07:44
Actually, seem that solution is not to ignore the SVG format since spreadsheet processors probably won't provide it and even if they do, it's expected to be relatively small. So this will be fixed in next version.

**Closed** 2018-05-01 09:53 UTC
