### ISSUE TITLE
Pasting images from clipboard to imgur pastes image twice

### ISSUE THREAD

**Issue by realchrisolin** [hluk/CopyQ#547] opened 2016-09-16 15:35 UTC
See http://screencast.com/t/hWCKb7A9n for a quick demonstration. I didn't encounter this issue until I started using CopyQ. Windows 10 (10.0.10586). I can't find the CopyQ version info anywhere, but I'm using the latest stable release.

**Comment by hluk** [comment] 2016-09-18 06:07
CopyQ version can be found in About dialog (press <kbd>F1</kbd>) or run `copyq --version`.

How do you paste items (from CopyQ or with shortcut in browser)? If it's from CopyQ on <kbd>Enter</kbd> key see if you don't use command (<kbd>F6</kbd> to open Commands dialog) that overrides <kbd>Enter</kbd> or <kbd>Return</kbd> shortcut.

(I don't use Flash anymore which seems to be required to view the screencast.)

**Comment by wildcolin** [comment] 2016-09-18 09:15
I'll have to beg you to make an exception in this situation. I have no other way to record my screen and trying to convert the SWF video that Jing creates to a more modern video format distorts the video in a way that makes it completely impossible to follow. There does not appear to be a way to resolve this. You will need to install Flash to watch this screencast. Sorry.

I'm pasting from my clipboard. The video depicts all this from beginning to end. Imgur supports images pasted directly from the clipboard, but when CopyQ is running in the background, the image in the clipboard is pasted twice, which creates an album. This only happens when CopyQ is running in the background and only when pasting from clipboard to Imgur.

Also, I have no "About" dialog available. Pressing F1 does not do anything. https://i.imgur.com/FPEqm46.png

**Comment by hluk** [comment] 2016-09-18 09:44
You need to open main window to use the shortcuts (select **Show/Hide** from the menu). Also check if there are any commands and check current formats in clipboard (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>C</kbd>).

**Comment by wildcolin** [comment] 2016-09-18 09:52
That was far less intuitive than I would expect, but I found it. v2.7.1. Here's a screenshot of the current formats window for an example image: https://i.imgur.com/CH0ju6A.png

**Comment by hluk** [comment] 2016-09-18 10:22
I cannot reproduce this on Windows or Linux.

When I click on "New Post" and then paste an image, single image post is created. This works on Firefox and Chromium after taking screenshot and even after copying item from CopyQ.

It's possible that this is a bug in web browser. Did you try this in other browsers?

**Comment by wildcolin** [comment] 2016-09-18 16:25
I did. Different computers too. I'll try to come up with better replication steps for you.

**Comment by hluk** [comment] 2018-09-16 10:56
Closing for now.

**Closed by hluk** 2018-09-16 10:56 UTC
