### ISSUE TITLE
Sometimes fields of each copy line are selected for no reason

### ISSUE THREAD

**Issue by tukanos** [hluk/CopyQ#842] opened 2017-12-19 13:37 UTC
The following applies to CopyQ 3.12. Using it on Windows 7 x64 SP1.

During my CopyQ use,  sometimes copied text arbitrary selected.  When I double click on the tray icon to show the main window a some lines are already pre-selected as shown on the attached picture:

![image](https://user-images.githubusercontent.com/731154/34159570-063b9180-e4ca-11e7-8151-e5b6cf5daac9.png)

The screenshot was taken right after a double click on the tray icon.

**Comment by hluk** [comment] 2017-12-19 14:36
Do you use any automatic commands? These are rendered with bold text in the list in Command dialog (<kbd>F6</kbd>).

**Comment by tukanos** [comment] 2017-12-20 07:41
I use one, which I compiled from here, and that is to prevent keepass copy to be copied to CopyQ

```
Name=Ignore KeePass
Window=.\\kdbx - KeePass
Command=copyq ignore\nsleep 10\ncopyq copy\ncopyq remove 0
Automatic=true
Remove=true
Icon=\xf084
```

Is there something wrong with the logic there or the functionality?  I want to stress that the text is selected only occasionally.

**Comment by hluk** [comment] 2017-12-20 12:55
The command looks OK.

I remember there was a similar bug in Qt [1] but I think this has been fixed already.

I'll try to reproduce this and let you know.

[1] I think this happened when selecting items after leaving the item list with <kbd>Shift</kbd> key pressed.

**Comment by hluk** [comment] 2017-12-20 13:45
Actually, your command uses `copyq copy` which basically simulates key presses for copying (usually <kbd>Shift</kbd>+<kbd>Insert</kbd>. That's probably the issue.

The command should be something like:
```ini
[Command]
Name=Ignore KeePass
Window=.\\kdbx - KeePass
Command="
    copyq:
    var secondsToWait = 10
    ignore()
    sleep(secondsToWait * 1000)
    copy('')"
Automatic=true
Icon=\xf084
```

**Comment by tukanos** [comment] 2017-12-21 08:38
I see, you are right that something happened after the last upgrade.

I tried your version it is, but it is giving me an Illegal character warning: `\` is underlined at `Icon=\xf084`.

Did you try to run it in your CopyQ?

**Comment by hluk** [comment] 2017-12-27 06:03
@tukanos [Here is description](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them) on how to properly add the command to CopyQ.

**Comment by tukanos** [comment] 2018-01-02 11:24
@hluk I have followed the instructions.  Now the text is not selected and CopyQ works correctly.

For future reference this is now valid way to ignore KeePass copies:

![image](https://user-images.githubusercontent.com/731154/34482347-aec195aa-efb7-11e7-8e86-c7b32acec534.png)

I'm closing the issue.

Thank you for your help!

**Comment by tukanos** [comment] 2018-01-09 13:07
The issue re-appeared, now even with the correct and functional `copyq ignore`

**Comment by tsujan** [comment] 2018-02-11 14:09
I've seen this issue many times under Manjaro (Linux), with different versions of CopyQ.

Now, I have V3.1..2, the latest release and, a few minutes ago, I saw the same thing. I use no custom action/command.

**Comment by tukanos** [comment] 2018-02-14 09:05
@tsujan I'm glad I'm not the only one.  I thought this would be only "my" issue.

**Comment by tsujan** [comment] 2018-02-14 11:04
Actually, I know a way to reproduce it:

(1) Show the window by clicking the tray icon;
(2) Double click the topmost item (that closes the window);
(3) Show the window by clicking the tray icon again and put the cursor over the window *by moving it from the window bottom upward*.

Then, all view items will be selected. An example that was made right now:

![result](https://user-images.githubusercontent.com/981076/36201077-0512f73e-1194-11e8-96d6-b2b728c22b9a.png)

**Comment by tsujan** [comment] 2018-02-14 11:10
> I thought this would be only "my" issue.

LOL! No app issue can be specific to one user; it may just have been detected only by him/her.

**Comment by tukanos** [comment] 2018-02-14 11:35
@tsujan great with the steps.  It does exactly as you have written

**Comment by tukanos** [comment] 2018-02-14 11:36
> LOL! No app issue can be specific to one user; it may just have been detected only by him/her.
Well that is true :).  But since nobody was complaining I thought I'm only one who is bother by it.

**Comment by hluk** [comment] 2018-02-14 19:32
Got it! :) It took me a while to reproduce because the double-click also needs to be a specific. The mouse button needs to be still pressed down when the window is being closed. It seems that the window registers "mouse button released" event only after you move cursor over window again (possibly a Qt bug).

Thanks for the steps to reproduce this. I'm trying to fix it.

**Comment by tsujan** [comment] 2018-02-14 19:37
@hluk Thanks! Looking forward to your fix.

**Comment by tukanos** [comment] 2018-02-15 09:42
@hluk Thank you too!  I hope it won't be that hard to fix it.

**Closed** 2018-02-15 18:19 UTC
Labels: bug

**Comment by tukanos** [comment] 2018-02-19 08:01
I do confirm that with the workaround CopyQ 3.2.0 now works correctly.
