### ISSUE TITLE
Application doesn't exit when using QtCurve theme and Qt 5.9

### ISSUE THREAD

**Issue by AcarBurak** [hluk/CopyQ#735] opened 2017-06-29 11:55 UTC
Exit doesn't kill copyq in Arch with Ot 5.9. It only kills one of the two processes, the config one, the other, main copyq process isn't killed though the tray icon is killed.

However, eveything works fine in Void Linux with Qt 5.8 (with runit instead of systemd if that matters).

**Comment by hluk** [comment] 2017-06-29 16:21
How can I reproduce it?

**Comment by AcarBurak** [comment] 2017-06-29 16:24
Right click on the tray icon,
Exit,
Click Yes.

This kills the tray icon, but a system monitor, for instance htop, shows copyq running.

**Comment by hluk** [comment] 2017-06-29 16:32
Work fine for me on Arch with Qt 5.9.

What does `ps aux|grep copyq` print after the exit?

Is there anything suspicious in log (F12 shortcut in CopyQ)?

**Comment by AcarBurak** [comment] 2017-06-29 17:11
```
ps aux|grep copyq
burak    19767  3.0  1.1 468420 47036 ?        Sl   20:07   0:00 copyq
burak    19777  0.0  0.0  10788  2140 pts/1    S+   20:07   0:00 grep --color=auto copyq
```

`killall copyq` doesn't make a difference either (after exiting).

Can't see anything suspicious in Log either.

**Comment by AcarBurak** [comment] 2017-06-29 17:19
There are two processes:
copyq
/usr/bin/copyq -s monitor /home/burak/.config/copyq/.copyq_m

Exit kills the second one only.

**Comment by hluk** [comment] 2017-06-29 17:31
Seems that the `copyq` process hangs on some exit code. Check the output of `COPYQ_LOG_LEVEL=DEBUG copyq` in terminal, wait a bit and kill the process again (should be possible to do this even with Ctrl+C in the terminal).

**Comment by AcarBurak** [comment] 2017-06-29 17:46
Ctrl+C doesn't kill it, but Ctrl+Z does, yet the main copyq process continues to run as explained previously.

`COPYQ_LOG_LEVEL=DEBUG copyq` produces nothing, but issuing it after (really) killing copyq from the system monitor produces this naturally:
`[1]+  Killed                  copyq`

**Comment by hluk** [comment] 2017-06-29 18:06
Ctrl+Z should just suspend the process (you can resume it with `fg`; there is no way to handle that signal in application).

Try:

```bash
killall copyq
sleep 2
killall -s9 copyq
COPYQ_LOG_LEVEL=DEBUG copyq
```

**Comment by AcarBurak** [comment] 2017-06-29 18:46
Please tell me if the below is not all right (the last kill is executed externally by the system monitor):

```
COPYQ_LOG_LEVEL=DEBUG copyq
DEBUG: QtDebug: using qt5ct plugin (:0, )
DEBUG: Server "/home/burak/.config/copyq/.copyq_s" started.
Note: Loading plugin: /usr/lib/copyq/plugins/libitemdata.so
Note: Loading plugin: /usr/lib/copyq/plugins/libitemencrypted.so
Note: Loading plugin: /usr/lib/copyq/plugins/libitemfakevim.so
Note: Loading plugin: /usr/lib/copyq/plugins/libitemimage.so
Note: Loading plugin: /usr/lib/copyq/plugins/libitemnotes.so
Note: Loading plugin: /usr/lib/copyq/plugins/libitempinned.so
Note: Loading plugin: /usr/lib/copyq/plugins/libitemsync.so
Note: Loading plugin: /usr/lib/copyq/plugins/libitemtags.so
Note: Loading plugin: /usr/lib/copyq/plugins/libitemtext.so
DEBUG: QtDebug: D-Bus global menu: no (:0, )
DEBUG: Loading configuration
DEBUG: Tab "&clipboard": Loading items
DEBUG: Tab "&clipboard": 200 items loaded
DEBUG: QtDebug: D-Bus system tray: no (:0, )
DEBUG: Configuration loaded
DEBUG: Starting monitor
DEBUG: Remote process: Starting new remote process "/usr/bin/copyq -s  monitor /home/burak/.config/copyq/.copyq_m".
DEBUG: Remote process: Started.
DEBUG: Configuring monitor
DEBUG: Terminating 0 clients
DEBUG: Closing server.
DEBUG: Terminating monitor
DEBUG: Monitor terminated
DEBUG: Terminating 0 clients
Killed
```

**Comment by hluk** [comment] 2017-06-29 19:06
It looks OK... well, except it hangs at the end.

Can you rebuild CopyQ (e.g. reinstall from AUR)? It's possible that it was built with different versions of Qt libraries.

You can also try launch the app without using the `qt5ct`:

```bash
QT_QPA_PLATFORMTHEME="" copyq
```

You could also try installing `copyq-git` from AUR instead -- it should be stable (I'm planning on releasing new version soon).

BTW, thanks for providing quick feedback!

**Comment by AcarBurak** [comment] 2017-06-29 19:09
You're welcome. I'll try the git version and disabling qt5ct.

**Comment by AcarBurak** [comment] 2017-06-29 19:10
Hey! Disabling qt5ct has solved it. Sorry for the noise if it's qt5ct's bug. Is it?

**Comment by hluk** [comment] 2017-06-29 19:18
It's hard to say what the issue is, could still be problem with some linked libs. I've seen similar issues where updating all installed packages and reinstalling `copyq` helped.

**Comment by AcarBurak** [comment] 2017-06-29 19:26
AUR git version doesn't make a difference, by the way.

**Comment by AcarBurak** [comment] 2017-06-29 20:12
qtcurve is responsible. If I use qt5ct with the default fusion style I can't reproduce the issue.

**Comment by hluk** [comment] 2017-07-01 08:46
Should be fixed in `copyq-git`.

**Closed** 2017-07-01 08:45 UTC
Labels: bug

**Comment by AcarBurak** [comment] 2017-07-01 10:25
Thank you.
