### ISSUE TITLE
Main window items are too big 

### ISSUE THREAD

**Issue by LubosRemplik** [hluk/CopyQ#1861] opened 2022-01-02 14:32 UTC
**Describe the bug**
Main window items are too big and are not visible

**Expected behavior**
Normal size

**Screenshots**
![image](https://user-images.githubusercontent.com/556169/147878938-9b421343-e101-4243-9204-1399e4cc3004.png)

**Version, OS and Environment**

CopyQ Clipboard Manager 5.0.0-115-gf9c668f7
Qt: 5.15.2
KNotifications: 5.86.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 21.10

**Additional context**
- config: show simple items is true
- config: items, using text and images. In the text "Save and display HTML and rich text" is false
- copy q crashes when I go to Preferences > Apperance. (in cli it says killed), where is the log for more info?

**Comment by hluk** [comment] 2022-01-04 08:10
This looks like a duplicate of #1728.

**Closed by hluk** 2022-01-04 08:10 UTC
Labels: bug

**Comment by LubosRemplik** [comment] 2022-01-04 08:40
> This looks like a duplicate of #1728.

It is, sorry did not notice... will follow there
