### ISSUE TITLE
Search the whole tabs by default

### ISSUE THREAD

**Issue by valuex** [hluk/CopyQ#2423] opened 2023-08-11 01:37 UTC
Some suggestion for search:
1. Now, CopyQ only searches the activated tab's items. How about first let the user search all  tabs's items by default? If the user want to screen out the results by tab tag, he/she could switch to the tab to do so.
2. Add the **shortname** property to the tab, so that when searching, user can type **shortname <delaminator> keywords** to do search more efficiently
3. Add the capability of searching by **Chinese Yinyin first letter** or other language's Romanic abbrivation. For this feature, **TCMatch.dll** would be a good reference. It uses **TCMatch.tbl** to store the letter's unicode and its corresponding Romanic letters.

**Comment by hluk** [comment] 2023-09-28 09:41
Looks like a duplicate of #1288.

**Closed by hluk** 2023-09-28 09:41 UTC
Labels: feature

**Comment by kwanice** [comment] 2025-01-12 13:05
can we have a full search (searching all words and tag in all the tab) by default ?
its not a duplicate, its a feature that should be implemented by default

ex : to make things organised u have a tab for different phone number, or any number
u have another tab for adresses 
etc...
u dont want to go on a specific to make a search, u are on the main tab but if u search stuff from thoses differents tab it will not work
so how to do ?

> Looks like a duplicate of #1288.
